/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0304"
 * 	found in "TAP0304.asn1"
 * 	`asn1c -D E:/repos/tap3reader/src/pdus/tap/3_04`
 */

#ifndef	_ChargedPartyInformation_H_
#define	_ChargedPartyInformation_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ChargedPartyIdList;
struct ChargedPartyHomeIdList;
struct ChargedPartyLocationList;
struct ChargedPartyEquipment;

/* ChargedPartyInformation */
typedef struct ChargedPartyInformation {
	struct ChargedPartyIdList	*chargedPartyIdList;	/* OPTIONAL */
	struct ChargedPartyHomeIdList	*chargedPartyHomeIdList;	/* OPTIONAL */
	struct ChargedPartyLocationList	*chargedPartyLocationList;	/* OPTIONAL */
	struct ChargedPartyEquipment	*chargedPartyEquipment;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ChargedPartyInformation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ChargedPartyInformation;
extern asn_SEQUENCE_specifics_t asn_SPC_ChargedPartyInformation_specs_1;
extern asn_TYPE_member_t asn_MBR_ChargedPartyInformation_1[4];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ChargedPartyIdList.h"
#include "ChargedPartyHomeIdList.h"
#include "ChargedPartyLocationList.h"
#include "ChargedPartyEquipment.h"

#endif	/* _ChargedPartyInformation_H_ */
#include <asn_internal.h>
