/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0304"
 * 	found in "TAP0304.asn1"
 * 	`asn1c -D E:/repos/tap3reader/src/pdus/tap/3_04`
 */

#ifndef	_Currency_H_
#define	_Currency_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Currency */
typedef OCTET_STRING_t	 Currency_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Currency;
asn_struct_free_f Currency_free;
asn_struct_print_f Currency_print;
asn_constr_check_f Currency_constraint;
ber_type_decoder_f Currency_decode_ber;
der_type_encoder_f Currency_encode_der;
xer_type_decoder_f Currency_decode_xer;
xer_type_encoder_f Currency_encode_xer;
jer_type_encoder_f Currency_encode_jer;
oer_type_decoder_f Currency_decode_oer;
oer_type_encoder_f Currency_encode_oer;
per_type_decoder_f Currency_decode_uper;
per_type_encoder_f Currency_encode_uper;
per_type_decoder_f Currency_decode_aper;
per_type_encoder_f Currency_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _Currency_H_ */
#include <asn_internal.h>
