/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0304"
 * 	found in "TAP0304.asn1"
 * 	`asn1c -D E:/repos/tap3reader/src/pdus/tap/3_04`
 */

#ifndef	_HomeIdentifier_H_
#define	_HomeIdentifier_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Name.h"
#include "PlmnId.h"
#include "HomeBid.h"
#include "LocationDescription.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum HomeIdentifier_PR {
	HomeIdentifier_PR_NOTHING,	/* No components present */
	HomeIdentifier_PR_name,
	HomeIdentifier_PR_tadigCode,
	HomeIdentifier_PR_homeBid,
	HomeIdentifier_PR_homeLocationDescription
} HomeIdentifier_PR;

/* HomeIdentifier */
typedef struct HomeIdentifier {
	HomeIdentifier_PR present;
	union HomeIdentifier_u {
		Name_t	 name;
		PlmnId_t	 tadigCode;
		HomeBid_t	 homeBid;
		LocationDescription_t	 homeLocationDescription;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} HomeIdentifier_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_HomeIdentifier;
extern asn_CHOICE_specifics_t asn_SPC_HomeIdentifier_specs_1;
extern asn_TYPE_member_t asn_MBR_HomeIdentifier_1[4];
extern asn_per_constraints_t asn_PER_type_HomeIdentifier_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _HomeIdentifier_H_ */
#include <asn_internal.h>
