/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0304"
 * 	found in "TAP0304.asn1"
 * 	`asn1c -D E:/repos/tap3reader/src/pdus/tap/3_04`
 */

#ifndef	_InternetServiceProviderId_H_
#define	_InternetServiceProviderId_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ProviderIdType.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProviderId;

/* InternetServiceProviderId */
typedef struct InternetServiceProviderId {
	ProviderIdType_t	*internetServiceProviderIdType;	/* OPTIONAL */
	struct ProviderId	*internetServiceProviderId;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} InternetServiceProviderId_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_InternetServiceProviderId;
extern asn_SEQUENCE_specifics_t asn_SPC_InternetServiceProviderId_specs_1;
extern asn_TYPE_member_t asn_MBR_InternetServiceProviderId_1[2];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ProviderId.h"

#endif	/* _InternetServiceProviderId_H_ */
#include <asn_internal.h>
