/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0304"
 * 	found in "TAP0304.asn1"
 * 	`asn1c -D E:/repos/tap3reader/src/pdus/tap/3_04`
 */

#include "LocationIdentifier.h"

#if !defined(ASN_DISABLE_OER_SUPPORT)
static asn_oer_constraints_t asn_OER_type_LocationIdentifier_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_LocationIdentifier_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  5 }	/* (0..5) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
asn_TYPE_member_t asn_MBR_LocationIdentifier_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct LocationIdentifier, choice.countryName),
		(ASN_TAG_CLASS_APPLICATION | (316 << 2)),
		0,
		&asn_DEF_CountryName,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"countryName"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LocationIdentifier, choice.countryE164Id),
		(ASN_TAG_CLASS_APPLICATION | (77 << 2)),
		0,
		&asn_DEF_CountryCode,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"countryE164Id"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LocationIdentifier, choice.countryCode),
		(ASN_TAG_CLASS_APPLICATION | (317 << 2)),
		0,
		&asn_DEF_CountryAsciCode,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"countryCode"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LocationIdentifier, choice.region),
		(ASN_TAG_CLASS_APPLICATION | (318 << 2)),
		0,
		&asn_DEF_Region,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"region"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LocationIdentifier, choice.place),
		(ASN_TAG_CLASS_APPLICATION | (319 << 2)),
		0,
		&asn_DEF_Place,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"place"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LocationIdentifier, choice.ipLocation),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_IpAddress,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"ipLocation"
		},
};
static const unsigned asn_MAP_LocationIdentifier_to_canonical_1[] = { 1, 5, 0, 2, 3, 4 };
static const unsigned asn_MAP_LocationIdentifier_from_canonical_1[] = { 2, 0, 3, 4, 5, 1 };
static const asn_TYPE_tag2member_t asn_MAP_LocationIdentifier_tag2el_1[] = {
    { (ASN_TAG_CLASS_APPLICATION | (77 << 2)), 1, 0, 0 }, /* countryE164Id */
    { (ASN_TAG_CLASS_APPLICATION | (131 << 2)), 5, 0, 0 }, /* iPTextV4Address */
    { (ASN_TAG_CLASS_APPLICATION | (132 << 2)), 5, 0, 0 }, /* iPTextV6Address */
    { (ASN_TAG_CLASS_APPLICATION | (316 << 2)), 0, 0, 0 }, /* countryName */
    { (ASN_TAG_CLASS_APPLICATION | (317 << 2)), 2, 0, 0 }, /* countryCode */
    { (ASN_TAG_CLASS_APPLICATION | (318 << 2)), 3, 0, 0 }, /* region */
    { (ASN_TAG_CLASS_APPLICATION | (319 << 2)), 4, 0, 0 } /* place */
};
asn_CHOICE_specifics_t asn_SPC_LocationIdentifier_specs_1 = {
	sizeof(struct LocationIdentifier),
	offsetof(struct LocationIdentifier, _asn_ctx),
	offsetof(struct LocationIdentifier, present),
	sizeof(((struct LocationIdentifier *)0)->present),
	asn_MAP_LocationIdentifier_tag2el_1,
	7,	/* Count of tags in the map */
	asn_MAP_LocationIdentifier_to_canonical_1,
	asn_MAP_LocationIdentifier_from_canonical_1,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_LocationIdentifier = {
	"LocationIdentifier",
	"LocationIdentifier",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		&asn_OER_type_LocationIdentifier_constr_1,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_LocationIdentifier_constr_1,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		CHOICE_constraint
	},
	asn_MBR_LocationIdentifier_1,
	6,	/* Elements count */
	&asn_SPC_LocationIdentifier_specs_1	/* Additional specs */
};

