/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0304"
 * 	found in "TAP0304.asn1"
 * 	`asn1c -D E:/repos/tap3reader/src/pdus/tap/3_04`
 */

#ifndef	_LocationIdentifier_H_
#define	_LocationIdentifier_H_


#include <asn_application.h>

/* Including external dependencies */
#include "CountryName.h"
#include "CountryCode.h"
#include "CountryAsciCode.h"
#include "Region.h"
#include "Place.h"
#include "IpAddress.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LocationIdentifier_PR {
	LocationIdentifier_PR_NOTHING,	/* No components present */
	LocationIdentifier_PR_countryName,
	LocationIdentifier_PR_countryE164Id,
	LocationIdentifier_PR_countryCode,
	LocationIdentifier_PR_region,
	LocationIdentifier_PR_place,
	LocationIdentifier_PR_ipLocation
} LocationIdentifier_PR;

/* LocationIdentifier */
typedef struct LocationIdentifier {
	LocationIdentifier_PR present;
	union LocationIdentifier_u {
		CountryName_t	 countryName;
		CountryCode_t	 countryE164Id;
		CountryAsciCode_t	 countryCode;
		Region_t	 region;
		Place_t	 place;
		IpAddress_t	 ipLocation;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LocationIdentifier_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LocationIdentifier;
extern asn_CHOICE_specifics_t asn_SPC_LocationIdentifier_specs_1;
extern asn_TYPE_member_t asn_MBR_LocationIdentifier_1[6];
extern asn_per_constraints_t asn_PER_type_LocationIdentifier_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _LocationIdentifier_H_ */
#include <asn_internal.h>
