/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0304"
 * 	found in "TAP0304.asn1"
 * 	`asn1c -D E:/repos/tap3reader/src/pdus/tap/3_04`
 */

#ifndef	_MinChargeableSubscriber_H_
#define	_MinChargeableSubscriber_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Min.h"
#include "Mdn.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* MinChargeableSubscriber */
typedef struct MinChargeableSubscriber {
	Min_t	*min;	/* OPTIONAL */
	Mdn_t	*mdn;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MinChargeableSubscriber_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MinChargeableSubscriber;
extern asn_SEQUENCE_specifics_t asn_SPC_MinChargeableSubscriber_specs_1;
extern asn_TYPE_member_t asn_MBR_MinChargeableSubscriber_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _MinChargeableSubscriber_H_ */
#include <asn_internal.h>
