/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0304"
 * 	found in "TAP0304.asn1"
 * 	`asn1c -D E:/repos/tap3reader/src/pdus/tap/3_04`
 */

#ifndef	_MobileTerminatedCall_H_
#define	_MobileTerminatedCall_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct MtBasicCallInformation;
struct LocationInformation;
struct EquipmentInformation;
struct BasicServiceUsedList;
struct SupplServiceUsedList;
struct CamelServiceUsed;
struct ValueAddedServiceUsedList;
struct DualServiceCode;
struct OperatorSpecInfoList;

/* MobileTerminatedCall */
typedef struct MobileTerminatedCall {
	struct MtBasicCallInformation	*basicCallInformation;	/* OPTIONAL */
	struct LocationInformation	*locationInformation;	/* OPTIONAL */
	struct EquipmentInformation	*equipmentInformation;	/* OPTIONAL */
	struct BasicServiceUsedList	*basicServiceUsedList;	/* OPTIONAL */
	struct SupplServiceUsedList	*supplServiceUsedList;	/* OPTIONAL */
	struct CamelServiceUsed	*camelServiceUsed;	/* OPTIONAL */
	struct ValueAddedServiceUsedList	*valueAddedServiceUsedList;	/* OPTIONAL */
	struct DualServiceCode	*dualServiceRequested;	/* OPTIONAL */
	struct OperatorSpecInfoList	*operatorSpecInformation;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MobileTerminatedCall_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MobileTerminatedCall;
extern asn_SEQUENCE_specifics_t asn_SPC_MobileTerminatedCall_specs_1;
extern asn_TYPE_member_t asn_MBR_MobileTerminatedCall_1[9];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "MtBasicCallInformation.h"
#include "LocationInformation.h"
#include "EquipmentInformation.h"
#include "BasicServiceUsedList.h"
#include "SupplServiceUsedList.h"
#include "CamelServiceUsed.h"
#include "ValueAddedServiceUsedList.h"
#include "DualServiceCode.h"
#include "OperatorSpecInfoList.h"

#endif	/* _MobileTerminatedCall_H_ */
#include <asn_internal.h>
