/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0304"
 * 	found in "TAP0304.asn1"
 * 	`asn1c -D E:/repos/tap3reader/src/pdus/tap/3_04`
 */

#ifndef	_OperatorSpecInformation_H_
#define	_OperatorSpecInformation_H_


#include <asn_application.h>

/* Including external dependencies */
#include "AsciiString.h"

#ifdef __cplusplus
extern "C" {
#endif

/* OperatorSpecInformation */
typedef AsciiString_t	 OperatorSpecInformation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_OperatorSpecInformation;
asn_struct_free_f OperatorSpecInformation_free;
asn_struct_print_f OperatorSpecInformation_print;
asn_constr_check_f OperatorSpecInformation_constraint;
ber_type_decoder_f OperatorSpecInformation_decode_ber;
der_type_encoder_f OperatorSpecInformation_encode_der;
xer_type_decoder_f OperatorSpecInformation_decode_xer;
xer_type_encoder_f OperatorSpecInformation_encode_xer;
jer_type_encoder_f OperatorSpecInformation_encode_jer;
oer_type_decoder_f OperatorSpecInformation_decode_oer;
oer_type_encoder_f OperatorSpecInformation_encode_oer;
per_type_decoder_f OperatorSpecInformation_decode_uper;
per_type_encoder_f OperatorSpecInformation_encode_uper;
per_type_decoder_f OperatorSpecInformation_decode_aper;
per_type_encoder_f OperatorSpecInformation_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _OperatorSpecInformation_H_ */
#include <asn_internal.h>
