/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0304"
 * 	found in "TAP0304.asn1"
 * 	`asn1c -D E:/repos/tap3reader/src/pdus/tap/3_04`
 */

#ifndef	_ProviderId_H_
#define	_ProviderId_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Name.h"
#include "PlmnId.h"
#include "Url.h"
#include "IpAddress.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ProviderId_PR {
	ProviderId_PR_NOTHING,	/* No components present */
	ProviderId_PR_name,
	ProviderId_PR_tadigCode,
	ProviderId_PR_url,
	ProviderId_PR_ipAddress
} ProviderId_PR;

/* ProviderId */
typedef struct ProviderId {
	ProviderId_PR present;
	union ProviderId_u {
		Name_t	 name;
		PlmnId_t	 tadigCode;
		Url_t	 url;
		IpAddress_t	 ipAddress;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProviderId_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ProviderId;
extern asn_CHOICE_specifics_t asn_SPC_ProviderId_specs_1;
extern asn_TYPE_member_t asn_MBR_ProviderId_1[4];
extern asn_per_constraints_t asn_PER_type_ProviderId_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _ProviderId_H_ */
#include <asn_internal.h>
