/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0304"
 * 	found in "TAP0304.asn1"
 * 	`asn1c -D E:/repos/tap3reader/src/pdus/tap/3_04`
 */

#ifndef	_QoSMaxBitRateUplink_H_
#define	_QoSMaxBitRateUplink_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* QoSMaxBitRateUplink */
typedef OCTET_STRING_t	 QoSMaxBitRateUplink_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_QoSMaxBitRateUplink;
asn_struct_free_f QoSMaxBitRateUplink_free;
asn_struct_print_f QoSMaxBitRateUplink_print;
asn_constr_check_f QoSMaxBitRateUplink_constraint;
ber_type_decoder_f QoSMaxBitRateUplink_decode_ber;
der_type_encoder_f QoSMaxBitRateUplink_encode_der;
xer_type_decoder_f QoSMaxBitRateUplink_decode_xer;
xer_type_encoder_f QoSMaxBitRateUplink_encode_xer;
jer_type_encoder_f QoSMaxBitRateUplink_encode_jer;
oer_type_decoder_f QoSMaxBitRateUplink_decode_oer;
oer_type_encoder_f QoSMaxBitRateUplink_encode_oer;
per_type_decoder_f QoSMaxBitRateUplink_decode_uper;
per_type_encoder_f QoSMaxBitRateUplink_encode_uper;
per_type_decoder_f QoSMaxBitRateUplink_decode_aper;
per_type_encoder_f QoSMaxBitRateUplink_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _QoSMaxBitRateUplink_H_ */
#include <asn_internal.h>
