/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0304"
 * 	found in "TAP0304.asn1"
 * 	`asn1c -D E:/repos/tap3reader/src/pdus/tap/3_04`
 */

#include "QoSUsed.h"

#if !defined(ASN_DISABLE_OER_SUPPORT)
static asn_oer_constraints_t asn_OER_type_QoSUsed_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_QoSUsed_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
asn_TYPE_member_t asn_MBR_QoSUsed_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct QoSUsed, choice.gsmQoSUsed),
		(ASN_TAG_CLASS_APPLICATION | (273 << 2)),
		0,
		&asn_DEF_GSMQoSUsed,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"gsmQoSUsed"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct QoSUsed, choice.umtsQoSUsed),
		(ASN_TAG_CLASS_APPLICATION | (271 << 2)),
		0,
		&asn_DEF_UMTSQoSUsed,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"umtsQoSUsed"
		},
};
static const unsigned asn_MAP_QoSUsed_to_canonical_1[] = { 1, 0 };
static const unsigned asn_MAP_QoSUsed_from_canonical_1[] = { 1, 0 };
static const asn_TYPE_tag2member_t asn_MAP_QoSUsed_tag2el_1[] = {
    { (ASN_TAG_CLASS_APPLICATION | (271 << 2)), 1, 0, 0 }, /* umtsQoSUsed */
    { (ASN_TAG_CLASS_APPLICATION | (273 << 2)), 0, 0, 0 } /* gsmQoSUsed */
};
asn_CHOICE_specifics_t asn_SPC_QoSUsed_specs_1 = {
	sizeof(struct QoSUsed),
	offsetof(struct QoSUsed, _asn_ctx),
	offsetof(struct QoSUsed, present),
	sizeof(((struct QoSUsed *)0)->present),
	asn_MAP_QoSUsed_tag2el_1,
	2,	/* Count of tags in the map */
	asn_MAP_QoSUsed_to_canonical_1,
	asn_MAP_QoSUsed_from_canonical_1,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_QoSUsed = {
	"QoSUsed",
	"QoSUsed",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		&asn_OER_type_QoSUsed_constr_1,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_QoSUsed_constr_1,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		CHOICE_constraint
	},
	asn_MBR_QoSUsed_1,
	2,	/* Elements count */
	&asn_SPC_QoSUsed_specs_1	/* Additional specs */
};

