/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0304"
 * 	found in "TAP0304.asn1"
 * 	`asn1c -D E:/repos/tap3reader/src/pdus/tap/3_04`
 */

#include "ScuChargeType.h"

asn_TYPE_member_t asn_MBR_ScuChargeType_1[] = {
	{ ATF_POINTER, 5, offsetof(struct ScuChargeType, messageStatus),
		(ASN_TAG_CLASS_APPLICATION | (144 << 2)),
		0,
		&asn_DEF_MessageStatus,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"messageStatus"
		},
	{ ATF_POINTER, 4, offsetof(struct ScuChargeType, priorityCode),
		(ASN_TAG_CLASS_APPLICATION | (170 << 2)),
		0,
		&asn_DEF_PriorityCode,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"priorityCode"
		},
	{ ATF_POINTER, 3, offsetof(struct ScuChargeType, distanceChargeBandCode),
		(ASN_TAG_CLASS_APPLICATION | (98 << 2)),
		0,
		&asn_DEF_DistanceChargeBandCode,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"distanceChargeBandCode"
		},
	{ ATF_POINTER, 2, offsetof(struct ScuChargeType, messageType),
		(ASN_TAG_CLASS_APPLICATION | (145 << 2)),
		0,
		&asn_DEF_MessageType,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"messageType"
		},
	{ ATF_POINTER, 1, offsetof(struct ScuChargeType, messageDescriptionCode),
		(ASN_TAG_CLASS_APPLICATION | (141 << 2)),
		0,
		&asn_DEF_MessageDescriptionCode,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"messageDescriptionCode"
		},
};
static const int asn_MAP_ScuChargeType_oms_1[] = { 0, 1, 2, 3, 4 };
static const ber_tlv_tag_t asn_DEF_ScuChargeType_tags_1[] = {
	(ASN_TAG_CLASS_APPLICATION | (192 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ScuChargeType_tag2el_1[] = {
    { (ASN_TAG_CLASS_APPLICATION | (98 << 2)), 2, 0, 0 }, /* distanceChargeBandCode */
    { (ASN_TAG_CLASS_APPLICATION | (141 << 2)), 4, 0, 0 }, /* messageDescriptionCode */
    { (ASN_TAG_CLASS_APPLICATION | (144 << 2)), 0, 0, 0 }, /* messageStatus */
    { (ASN_TAG_CLASS_APPLICATION | (145 << 2)), 3, 0, 0 }, /* messageType */
    { (ASN_TAG_CLASS_APPLICATION | (170 << 2)), 1, 0, 0 } /* priorityCode */
};
asn_SEQUENCE_specifics_t asn_SPC_ScuChargeType_specs_1 = {
	sizeof(struct ScuChargeType),
	offsetof(struct ScuChargeType, _asn_ctx),
	asn_MAP_ScuChargeType_tag2el_1,
	5,	/* Count of tags in the map */
	asn_MAP_ScuChargeType_oms_1,	/* Optional members */
	5, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_ScuChargeType = {
	"ScuChargeType",
	"ScuChargeType",
	&asn_OP_SEQUENCE,
	asn_DEF_ScuChargeType_tags_1,
	sizeof(asn_DEF_ScuChargeType_tags_1)
		/sizeof(asn_DEF_ScuChargeType_tags_1[0]) - 1, /* 1 */
	asn_DEF_ScuChargeType_tags_1,	/* Same as above */
	sizeof(asn_DEF_ScuChargeType_tags_1)
		/sizeof(asn_DEF_ScuChargeType_tags_1[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_ScuChargeType_1,
	5,	/* Elements count */
	&asn_SPC_ScuChargeType_specs_1	/* Additional specs */
};

