/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0304"
 * 	found in "TAP0304.asn1"
 * 	`asn1c -D E:/repos/tap3reader/src/pdus/tap/3_04`
 */

#ifndef	_ScuTimeStamps_H_
#define	_ScuTimeStamps_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ChargingPoint.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct DepositTimeStamp;
struct CompletionTimeStamp;

/* ScuTimeStamps */
typedef struct ScuTimeStamps {
	struct DepositTimeStamp	*depositTimeStamp;	/* OPTIONAL */
	struct CompletionTimeStamp	*completionTimeStamp;	/* OPTIONAL */
	ChargingPoint_t	*chargingPoint;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ScuTimeStamps_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ScuTimeStamps;
extern asn_SEQUENCE_specifics_t asn_SPC_ScuTimeStamps_specs_1;
extern asn_TYPE_member_t asn_MBR_ScuTimeStamps_1[3];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "DepositTimeStamp.h"
#include "CompletionTimeStamp.h"

#endif	/* _ScuTimeStamps_H_ */
#include <asn_internal.h>
