/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0304"
 * 	found in "TAP0304.asn1"
 * 	`asn1c -D E:/repos/tap3reader/src/pdus/tap/3_04`
 */

#ifndef	_UMTSQoSInformation_H_
#define	_UMTSQoSInformation_H_


#include <asn_application.h>

/* Including external dependencies */
#include "QoSTrafficClass.h"
#include "QoSMaxBitRateUplink.h"
#include "QoSMaxBitRateDownlink.h"
#include "QoSDeliveryOrder.h"
#include "QoSMaxSDUsize.h"
#include "QoSSDUErrorRatio.h"
#include "QoSResidualBER.h"
#include "QoSErroneousSDUs.h"
#include "QoSTransferDelay.h"
#include "QoSHandlingpriority.h"
#include "QoSAllocRetenPriority.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* UMTSQoSInformation */
typedef struct UMTSQoSInformation {
	QoSTrafficClass_t	*trafficClass;	/* OPTIONAL */
	QoSMaxBitRateUplink_t	*maxBitRateUplink;	/* OPTIONAL */
	QoSMaxBitRateDownlink_t	*maxBitRateDownlink;	/* OPTIONAL */
	QoSDeliveryOrder_t	*deliveryOrder;	/* OPTIONAL */
	QoSMaxSDUsize_t	*maxSDUsize;	/* OPTIONAL */
	QoSSDUErrorRatio_t	*sduErrorRatio;	/* OPTIONAL */
	QoSResidualBER_t	*residualBER;	/* OPTIONAL */
	QoSErroneousSDUs_t	*erroneousSDUs;	/* OPTIONAL */
	QoSTransferDelay_t	*transferDelay;	/* OPTIONAL */
	QoSHandlingpriority_t	*handlingPriority;	/* OPTIONAL */
	QoSAllocRetenPriority_t	*allocRetenPriority;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UMTSQoSInformation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UMTSQoSInformation;
extern asn_SEQUENCE_specifics_t asn_SPC_UMTSQoSInformation_specs_1;
extern asn_TYPE_member_t asn_MBR_UMTSQoSInformation_1[11];

#ifdef __cplusplus
}
#endif

#endif	/* _UMTSQoSInformation_H_ */
#include <asn_internal.h>
