/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0304"
 * 	found in "TAP0304.asn1"
 * 	`asn1c -D E:/repos/tap3reader/src/pdus/tap/3_04`
 */

#include "UMTSQoSInformation.h"

asn_TYPE_member_t asn_MBR_UMTSQoSInformation_1[] = {
	{ ATF_POINTER, 11, offsetof(struct UMTSQoSInformation, trafficClass),
		(ASN_TAG_CLASS_APPLICATION | (268 << 2)),
		0,
		&asn_DEF_QoSTrafficClass,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"trafficClass"
		},
	{ ATF_POINTER, 10, offsetof(struct UMTSQoSInformation, maxBitRateUplink),
		(ASN_TAG_CLASS_APPLICATION | (264 << 2)),
		0,
		&asn_DEF_QoSMaxBitRateUplink,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"maxBitRateUplink"
		},
	{ ATF_POINTER, 9, offsetof(struct UMTSQoSInformation, maxBitRateDownlink),
		(ASN_TAG_CLASS_APPLICATION | (274 << 2)),
		0,
		&asn_DEF_QoSMaxBitRateDownlink,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"maxBitRateDownlink"
		},
	{ ATF_POINTER, 8, offsetof(struct UMTSQoSInformation, deliveryOrder),
		(ASN_TAG_CLASS_APPLICATION | (278 << 2)),
		0,
		&asn_DEF_QoSDeliveryOrder,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"deliveryOrder"
		},
	{ ATF_POINTER, 7, offsetof(struct UMTSQoSInformation, maxSDUsize),
		(ASN_TAG_CLASS_APPLICATION | (265 << 2)),
		0,
		&asn_DEF_QoSMaxSDUsize,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"maxSDUsize"
		},
	{ ATF_POINTER, 6, offsetof(struct UMTSQoSInformation, sduErrorRatio),
		(ASN_TAG_CLASS_APPLICATION | (267 << 2)),
		0,
		&asn_DEF_QoSSDUErrorRatio,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"sduErrorRatio"
		},
	{ ATF_POINTER, 5, offsetof(struct UMTSQoSInformation, residualBER),
		(ASN_TAG_CLASS_APPLICATION | (266 << 2)),
		0,
		&asn_DEF_QoSResidualBER,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"residualBER"
		},
	{ ATF_POINTER, 4, offsetof(struct UMTSQoSInformation, erroneousSDUs),
		(ASN_TAG_CLASS_APPLICATION | (277 << 2)),
		0,
		&asn_DEF_QoSErroneousSDUs,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"erroneousSDUs"
		},
	{ ATF_POINTER, 3, offsetof(struct UMTSQoSInformation, transferDelay),
		(ASN_TAG_CLASS_APPLICATION | (269 << 2)),
		0,
		&asn_DEF_QoSTransferDelay,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"transferDelay"
		},
	{ ATF_POINTER, 2, offsetof(struct UMTSQoSInformation, handlingPriority),
		(ASN_TAG_CLASS_APPLICATION | (276 << 2)),
		0,
		&asn_DEF_QoSHandlingpriority,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"handlingPriority"
		},
	{ ATF_POINTER, 1, offsetof(struct UMTSQoSInformation, allocRetenPriority),
		(ASN_TAG_CLASS_APPLICATION | (275 << 2)),
		0,
		&asn_DEF_QoSAllocRetenPriority,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"allocRetenPriority"
		},
};
static const int asn_MAP_UMTSQoSInformation_oms_1[] = { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 };
static const ber_tlv_tag_t asn_DEF_UMTSQoSInformation_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_UMTSQoSInformation_tag2el_1[] = {
    { (ASN_TAG_CLASS_APPLICATION | (264 << 2)), 1, 0, 0 }, /* maxBitRateUplink */
    { (ASN_TAG_CLASS_APPLICATION | (265 << 2)), 4, 0, 0 }, /* maxSDUsize */
    { (ASN_TAG_CLASS_APPLICATION | (266 << 2)), 6, 0, 0 }, /* residualBER */
    { (ASN_TAG_CLASS_APPLICATION | (267 << 2)), 5, 0, 0 }, /* sduErrorRatio */
    { (ASN_TAG_CLASS_APPLICATION | (268 << 2)), 0, 0, 0 }, /* trafficClass */
    { (ASN_TAG_CLASS_APPLICATION | (269 << 2)), 8, 0, 0 }, /* transferDelay */
    { (ASN_TAG_CLASS_APPLICATION | (274 << 2)), 2, 0, 0 }, /* maxBitRateDownlink */
    { (ASN_TAG_CLASS_APPLICATION | (275 << 2)), 10, 0, 0 }, /* allocRetenPriority */
    { (ASN_TAG_CLASS_APPLICATION | (276 << 2)), 9, 0, 0 }, /* handlingPriority */
    { (ASN_TAG_CLASS_APPLICATION | (277 << 2)), 7, 0, 0 }, /* erroneousSDUs */
    { (ASN_TAG_CLASS_APPLICATION | (278 << 2)), 3, 0, 0 } /* deliveryOrder */
};
asn_SEQUENCE_specifics_t asn_SPC_UMTSQoSInformation_specs_1 = {
	sizeof(struct UMTSQoSInformation),
	offsetof(struct UMTSQoSInformation, _asn_ctx),
	asn_MAP_UMTSQoSInformation_tag2el_1,
	11,	/* Count of tags in the map */
	asn_MAP_UMTSQoSInformation_oms_1,	/* Optional members */
	11, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_UMTSQoSInformation = {
	"UMTSQoSInformation",
	"UMTSQoSInformation",
	&asn_OP_SEQUENCE,
	asn_DEF_UMTSQoSInformation_tags_1,
	sizeof(asn_DEF_UMTSQoSInformation_tags_1)
		/sizeof(asn_DEF_UMTSQoSInformation_tags_1[0]), /* 1 */
	asn_DEF_UMTSQoSInformation_tags_1,	/* Same as above */
	sizeof(asn_DEF_UMTSQoSInformation_tags_1)
		/sizeof(asn_DEF_UMTSQoSInformation_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_UMTSQoSInformation_1,
	11,	/* Elements count */
	&asn_SPC_UMTSQoSInformation_specs_1	/* Additional specs */
};

