/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0302"
 * 	found in "TAP0303.asn1"
 * 	`asn1c -D E:/repos/tap3reader/src/pdus/tap/3_03`
 */

#ifndef	_CalledNumAnalysisCode_H_
#define	_CalledNumAnalysisCode_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Code.h"

#ifdef __cplusplus
extern "C" {
#endif

/* CalledNumAnalysisCode */
typedef Code_t	 CalledNumAnalysisCode_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CalledNumAnalysisCode;
asn_struct_free_f CalledNumAnalysisCode_free;
asn_struct_print_f CalledNumAnalysisCode_print;
asn_constr_check_f CalledNumAnalysisCode_constraint;
ber_type_decoder_f CalledNumAnalysisCode_decode_ber;
der_type_encoder_f CalledNumAnalysisCode_encode_der;
xer_type_decoder_f CalledNumAnalysisCode_decode_xer;
xer_type_encoder_f CalledNumAnalysisCode_encode_xer;
jer_type_encoder_f CalledNumAnalysisCode_encode_jer;
oer_type_decoder_f CalledNumAnalysisCode_decode_oer;
oer_type_encoder_f CalledNumAnalysisCode_encode_oer;
per_type_decoder_f CalledNumAnalysisCode_decode_uper;
per_type_encoder_f CalledNumAnalysisCode_encode_uper;
per_type_decoder_f CalledNumAnalysisCode_decode_aper;
per_type_encoder_f CalledNumAnalysisCode_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _CalledNumAnalysisCode_H_ */
#include <asn_internal.h>
