/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0302"
 * 	found in "TAP0303.asn1"
 * 	`asn1c -D E:/repos/tap3reader/src/pdus/tap/3_03`
 */

#include "QoSInformation.h"

asn_TYPE_member_t asn_MBR_QoSInformation_1[] = {
	{ ATF_POINTER, 5, offsetof(struct QoSInformation, delay),
		(ASN_TAG_CLASS_APPLICATION | (171 << 2)),
		0,
		&asn_DEF_QoSDelay,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"delay"
		},
	{ ATF_POINTER, 4, offsetof(struct QoSInformation, meanThroughput),
		(ASN_TAG_CLASS_APPLICATION | (173 << 2)),
		0,
		&asn_DEF_QoSMeanThroughput,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"meanThroughput"
		},
	{ ATF_POINTER, 3, offsetof(struct QoSInformation, peakThroughput),
		(ASN_TAG_CLASS_APPLICATION | (174 << 2)),
		0,
		&asn_DEF_QoSPeakThroughput,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"peakThroughput"
		},
	{ ATF_POINTER, 2, offsetof(struct QoSInformation, precedence),
		(ASN_TAG_CLASS_APPLICATION | (175 << 2)),
		0,
		&asn_DEF_QoSPrecedence,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"precedence"
		},
	{ ATF_POINTER, 1, offsetof(struct QoSInformation, reliability),
		(ASN_TAG_CLASS_APPLICATION | (176 << 2)),
		0,
		&asn_DEF_QoSReliability,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"reliability"
		},
};
static const int asn_MAP_QoSInformation_oms_1[] = { 0, 1, 2, 3, 4 };
static const ber_tlv_tag_t asn_DEF_QoSInformation_tags_1[] = {
	(ASN_TAG_CLASS_APPLICATION | (172 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_QoSInformation_tag2el_1[] = {
    { (ASN_TAG_CLASS_APPLICATION | (171 << 2)), 0, 0, 0 }, /* delay */
    { (ASN_TAG_CLASS_APPLICATION | (173 << 2)), 1, 0, 0 }, /* meanThroughput */
    { (ASN_TAG_CLASS_APPLICATION | (174 << 2)), 2, 0, 0 }, /* peakThroughput */
    { (ASN_TAG_CLASS_APPLICATION | (175 << 2)), 3, 0, 0 }, /* precedence */
    { (ASN_TAG_CLASS_APPLICATION | (176 << 2)), 4, 0, 0 } /* reliability */
};
asn_SEQUENCE_specifics_t asn_SPC_QoSInformation_specs_1 = {
	sizeof(struct QoSInformation),
	offsetof(struct QoSInformation, _asn_ctx),
	asn_MAP_QoSInformation_tag2el_1,
	5,	/* Count of tags in the map */
	asn_MAP_QoSInformation_oms_1,	/* Optional members */
	5, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_QoSInformation = {
	"QoSInformation",
	"QoSInformation",
	&asn_OP_SEQUENCE,
	asn_DEF_QoSInformation_tags_1,
	sizeof(asn_DEF_QoSInformation_tags_1)
		/sizeof(asn_DEF_QoSInformation_tags_1[0]) - 1, /* 1 */
	asn_DEF_QoSInformation_tags_1,	/* Same as above */
	sizeof(asn_DEF_QoSInformation_tags_1)
		/sizeof(asn_DEF_QoSInformation_tags_1[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_QoSInformation_1,
	5,	/* Elements count */
	&asn_SPC_QoSInformation_specs_1	/* Additional specs */
};

