/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0302"
 * 	found in "TAP0303.asn1"
 * 	`asn1c -D E:/repos/tap3reader/src/pdus/tap/3_03`
 */

#ifndef	_ServiceCentreUsage_H_
#define	_ServiceCentreUsage_H_


#include <asn_application.h>

/* Including external dependencies */
#include "FraudMonitorIndicator.h"
#include "RapFileSequenceNumber.h"
#include "NetworkType.h"
#include "RecEntityCode.h"
#include "OperatorSpecInformation.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ScuBasicInformation;
struct ChargeInformation;
struct ScuChargeType;
struct ScuTimeStamps;

/* ServiceCentreUsage */
typedef struct ServiceCentreUsage {
	FraudMonitorIndicator_t	*fraudMonitorIndicator;	/* OPTIONAL */
	struct ScuBasicInformation	*basicInformation;	/* OPTIONAL */
	RapFileSequenceNumber_t	*rapFileSequenceNumber;	/* OPTIONAL */
	NetworkType_t	*networkType;	/* OPTIONAL */
	RecEntityCode_t	*recEntityCode;	/* OPTIONAL */
	struct ChargeInformation	*chargeInformation;	/* OPTIONAL */
	struct ScuChargeType	*scuChargeType;	/* OPTIONAL */
	struct ScuTimeStamps	*scuTimeStamps;	/* OPTIONAL */
	OperatorSpecInformation_t	*operatorSpecInformation;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ServiceCentreUsage_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ServiceCentreUsage;
extern asn_SEQUENCE_specifics_t asn_SPC_ServiceCentreUsage_specs_1;
extern asn_TYPE_member_t asn_MBR_ServiceCentreUsage_1[9];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ScuBasicInformation.h"
#include "ChargeInformation.h"
#include "ScuChargeType.h"
#include "ScuTimeStamps.h"

#endif	/* _ServiceCentreUsage_H_ */
#include <asn_internal.h>
