/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0301"
 * 	found in "TAP0301.asn1"
 * 	`asn1c -D E:/repos/tap3reader/src/pdus/tap/3_01`
 */

#include "GprsBasicCallInformation.h"

asn_TYPE_member_t asn_MBR_GprsBasicCallInformation_1[] = {
	{ ATF_POINTER, 11, offsetof(struct GprsBasicCallInformation, fraudMonitorIndicator),
		(ASN_TAG_CLASS_APPLICATION | (112 << 2)),
		0,
		&asn_DEF_FraudMonitorIndicator,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"fraudMonitorIndicator"
		},
	{ ATF_POINTER, 10, offsetof(struct GprsBasicCallInformation, chargeableSubscriber),
		(ASN_TAG_CLASS_APPLICATION | (115 << 2)),
		0,
		&asn_DEF_GprsChargeableSubscriber,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"chargeableSubscriber"
		},
	{ ATF_POINTER, 9, offsetof(struct GprsBasicCallInformation, rapFileSequenceNumber),
		(ASN_TAG_CLASS_APPLICATION | (181 << 2)),
		0,
		&asn_DEF_RapFileSequenceNumber,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"rapFileSequenceNumber"
		},
	{ ATF_POINTER, 8, offsetof(struct GprsBasicCallInformation, networkType),
		(ASN_TAG_CLASS_APPLICATION | (157 << 2)),
		0,
		&asn_DEF_NetworkType,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"networkType"
		},
	{ ATF_POINTER, 7, offsetof(struct GprsBasicCallInformation, gprsDestination),
		(ASN_TAG_CLASS_APPLICATION | (116 << 2)),
		0,
		&asn_DEF_GprsDestination,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"gprsDestination"
		},
	{ ATF_POINTER, 6, offsetof(struct GprsBasicCallInformation, callEventStartTimeStamp),
		(ASN_TAG_CLASS_APPLICATION | (44 << 2)),
		0,
		&asn_DEF_CallEventStartTimeStamp,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"callEventStartTimeStamp"
		},
	{ ATF_POINTER, 5, offsetof(struct GprsBasicCallInformation, totalCallEventDuration),
		(ASN_TAG_CLASS_APPLICATION | (223 << 2)),
		0,
		&asn_DEF_TotalCallEventDuration,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"totalCallEventDuration"
		},
	{ ATF_POINTER, 4, offsetof(struct GprsBasicCallInformation, causeForTerm),
		(ASN_TAG_CLASS_APPLICATION | (58 << 2)),
		0,
		&asn_DEF_CauseForTerm,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"causeForTerm"
		},
	{ ATF_POINTER, 3, offsetof(struct GprsBasicCallInformation, partialTypeIndicator),
		(ASN_TAG_CLASS_APPLICATION | (166 << 2)),
		0,
		&asn_DEF_PartialTypeIndicator,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"partialTypeIndicator"
		},
	{ ATF_POINTER, 2, offsetof(struct GprsBasicCallInformation, networkInitPDPContext),
		(ASN_TAG_CLASS_APPLICATION | (245 << 2)),
		0,
		&asn_DEF_NetworkInitPDPContext,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"networkInitPDPContext"
		},
	{ ATF_POINTER, 1, offsetof(struct GprsBasicCallInformation, chargingId),
		(ASN_TAG_CLASS_APPLICATION | (72 << 2)),
		0,
		&asn_DEF_ChargingId,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"chargingId"
		},
};
static const int asn_MAP_GprsBasicCallInformation_oms_1[] = { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 };
static const ber_tlv_tag_t asn_DEF_GprsBasicCallInformation_tags_1[] = {
	(ASN_TAG_CLASS_APPLICATION | (114 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_GprsBasicCallInformation_tag2el_1[] = {
    { (ASN_TAG_CLASS_APPLICATION | (44 << 2)), 5, 0, 0 }, /* callEventStartTimeStamp */
    { (ASN_TAG_CLASS_APPLICATION | (58 << 2)), 7, 0, 0 }, /* causeForTerm */
    { (ASN_TAG_CLASS_APPLICATION | (72 << 2)), 10, 0, 0 }, /* chargingId */
    { (ASN_TAG_CLASS_APPLICATION | (112 << 2)), 0, 0, 0 }, /* fraudMonitorIndicator */
    { (ASN_TAG_CLASS_APPLICATION | (115 << 2)), 1, 0, 0 }, /* chargeableSubscriber */
    { (ASN_TAG_CLASS_APPLICATION | (116 << 2)), 4, 0, 0 }, /* gprsDestination */
    { (ASN_TAG_CLASS_APPLICATION | (157 << 2)), 3, 0, 0 }, /* networkType */
    { (ASN_TAG_CLASS_APPLICATION | (166 << 2)), 8, 0, 0 }, /* partialTypeIndicator */
    { (ASN_TAG_CLASS_APPLICATION | (181 << 2)), 2, 0, 0 }, /* rapFileSequenceNumber */
    { (ASN_TAG_CLASS_APPLICATION | (223 << 2)), 6, 0, 0 }, /* totalCallEventDuration */
    { (ASN_TAG_CLASS_APPLICATION | (245 << 2)), 9, 0, 0 } /* networkInitPDPContext */
};
asn_SEQUENCE_specifics_t asn_SPC_GprsBasicCallInformation_specs_1 = {
	sizeof(struct GprsBasicCallInformation),
	offsetof(struct GprsBasicCallInformation, _asn_ctx),
	asn_MAP_GprsBasicCallInformation_tag2el_1,
	11,	/* Count of tags in the map */
	asn_MAP_GprsBasicCallInformation_oms_1,	/* Optional members */
	11, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_GprsBasicCallInformation = {
	"GprsBasicCallInformation",
	"GprsBasicCallInformation",
	&asn_OP_SEQUENCE,
	asn_DEF_GprsBasicCallInformation_tags_1,
	sizeof(asn_DEF_GprsBasicCallInformation_tags_1)
		/sizeof(asn_DEF_GprsBasicCallInformation_tags_1[0]) - 1, /* 1 */
	asn_DEF_GprsBasicCallInformation_tags_1,	/* Same as above */
	sizeof(asn_DEF_GprsBasicCallInformation_tags_1)
		/sizeof(asn_DEF_GprsBasicCallInformation_tags_1[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_GprsBasicCallInformation_1,
	11,	/* Elements count */
	&asn_SPC_GprsBasicCallInformation_specs_1	/* Additional specs */
};

