/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0301"
 * 	found in "TAP0301.asn1"
 * 	`asn1c -D E:/repos/tap3reader/src/pdus/tap/3_01`
 */

#include "MobileOriginatedCall.h"

asn_TYPE_member_t asn_MBR_MobileOriginatedCall_1[] = {
	{ ATF_POINTER, 9, offsetof(struct MobileOriginatedCall, basicCallInformation),
		(ASN_TAG_CLASS_APPLICATION | (147 << 2)),
		0,
		&asn_DEF_MoBasicCallInformation,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"basicCallInformation"
		},
	{ ATF_POINTER, 8, offsetof(struct MobileOriginatedCall, locationInformation),
		(ASN_TAG_CLASS_APPLICATION | (138 << 2)),
		0,
		&asn_DEF_LocationInformation,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"locationInformation"
		},
	{ ATF_POINTER, 7, offsetof(struct MobileOriginatedCall, equipmentInformation),
		(ASN_TAG_CLASS_APPLICATION | (102 << 2)),
		0,
		&asn_DEF_EquipmentInformation,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"equipmentInformation"
		},
	{ ATF_POINTER, 6, offsetof(struct MobileOriginatedCall, basicServiceUsedList),
		(ASN_TAG_CLASS_APPLICATION | (38 << 2)),
		0,
		&asn_DEF_BasicServiceUsedList,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"basicServiceUsedList"
		},
	{ ATF_POINTER, 5, offsetof(struct MobileOriginatedCall, supplServiceUsedList),
		(ASN_TAG_CLASS_APPLICATION | (207 << 2)),
		0,
		&asn_DEF_SupplServiceUsedList,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"supplServiceUsedList"
		},
	{ ATF_POINTER, 4, offsetof(struct MobileOriginatedCall, camelServiceUsed),
		(ASN_TAG_CLASS_APPLICATION | (57 << 2)),
		0,
		&asn_DEF_CamelServiceUsed,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"camelServiceUsed"
		},
	{ ATF_POINTER, 3, offsetof(struct MobileOriginatedCall, valueAddedServiceUsedList),
		(ASN_TAG_CLASS_APPLICATION | (235 << 2)),
		0,
		&asn_DEF_ValueAddedServiceUsedList,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"valueAddedServiceUsedList"
		},
	{ ATF_POINTER, 2, offsetof(struct MobileOriginatedCall, dualServiceRequested),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_DualServiceCode,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"dualServiceRequested"
		},
	{ ATF_POINTER, 1, offsetof(struct MobileOriginatedCall, operatorSpecInformation),
		(ASN_TAG_CLASS_APPLICATION | (163 << 2)),
		0,
		&asn_DEF_OperatorSpecInformation,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"operatorSpecInformation"
		},
};
static const int asn_MAP_MobileOriginatedCall_oms_1[] = { 0, 1, 2, 3, 4, 5, 6, 7, 8 };
static const ber_tlv_tag_t asn_DEF_MobileOriginatedCall_tags_1[] = {
	(ASN_TAG_CLASS_APPLICATION | (9 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_MobileOriginatedCall_tag2el_1[] = {
    { (ASN_TAG_CLASS_APPLICATION | (38 << 2)), 3, 0, 0 }, /* basicServiceUsedList */
    { (ASN_TAG_CLASS_APPLICATION | (57 << 2)), 5, 0, 0 }, /* camelServiceUsed */
    { (ASN_TAG_CLASS_APPLICATION | (99 << 2)), 7, 0, 0 }, /* dualBearerServiceCode */
    { (ASN_TAG_CLASS_APPLICATION | (100 << 2)), 7, 0, 0 }, /* dualTeleServiceCode */
    { (ASN_TAG_CLASS_APPLICATION | (102 << 2)), 2, 0, 0 }, /* equipmentInformation */
    { (ASN_TAG_CLASS_APPLICATION | (138 << 2)), 1, 0, 0 }, /* locationInformation */
    { (ASN_TAG_CLASS_APPLICATION | (147 << 2)), 0, 0, 0 }, /* basicCallInformation */
    { (ASN_TAG_CLASS_APPLICATION | (163 << 2)), 8, 0, 0 }, /* operatorSpecInformation */
    { (ASN_TAG_CLASS_APPLICATION | (207 << 2)), 4, 0, 0 }, /* supplServiceUsedList */
    { (ASN_TAG_CLASS_APPLICATION | (235 << 2)), 6, 0, 0 } /* valueAddedServiceUsedList */
};
asn_SEQUENCE_specifics_t asn_SPC_MobileOriginatedCall_specs_1 = {
	sizeof(struct MobileOriginatedCall),
	offsetof(struct MobileOriginatedCall, _asn_ctx),
	asn_MAP_MobileOriginatedCall_tag2el_1,
	10,	/* Count of tags in the map */
	asn_MAP_MobileOriginatedCall_oms_1,	/* Optional members */
	9, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_MobileOriginatedCall = {
	"MobileOriginatedCall",
	"MobileOriginatedCall",
	&asn_OP_SEQUENCE,
	asn_DEF_MobileOriginatedCall_tags_1,
	sizeof(asn_DEF_MobileOriginatedCall_tags_1)
		/sizeof(asn_DEF_MobileOriginatedCall_tags_1[0]) - 1, /* 1 */
	asn_DEF_MobileOriginatedCall_tags_1,	/* Same as above */
	sizeof(asn_DEF_MobileOriginatedCall_tags_1)
		/sizeof(asn_DEF_MobileOriginatedCall_tags_1[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_MobileOriginatedCall_1,
	9,	/* Elements count */
	&asn_SPC_MobileOriginatedCall_specs_1	/* Additional specs */
};

