/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 */

struct asn_TYPE_descriptor_s;	/* Forward declaration */

extern struct asn_TYPE_descriptor_s asn_DEF_DataInterChange;
extern struct asn_TYPE_descriptor_s asn_DEF_DiscountInformationList;
extern struct asn_TYPE_descriptor_s asn_DEF_ServiceCentreIdentity;
extern struct asn_TYPE_descriptor_s asn_DEF_EXTERNAL;


struct asn_TYPE_descriptor_s *asn_pdu_collection[] = {
	/* From module TAP-0301 in TAP0301.asn1 */
	&asn_DEF_DataInterChange,	
	&asn_DEF_DiscountInformationList,	
	&asn_DEF_ServiceCentreIdentity,	
	/* From module ASN1C-UsefulInformationObjectClasses in C:/msys64/mingw64/share/asn1c/standard-modules/ASN1C-UsefulInformationObjectClasses.asn1 */
	&asn_DEF_EXTERNAL,	
	0
};

