/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0301"
 * 	found in "TAP0301.asn1"
 * 	`asn1c -D E:/repos/tap3reader/src/pdus/tap/3_01`
 */

#include "QoSUsed.h"

/*
 * This type is implemented using QoSInformation,
 * so here we adjust the DEF accordingly.
 */
static const ber_tlv_tag_t asn_DEF_QoSUsed_tags_1[] = {
	(ASN_TAG_CLASS_APPLICATION | (178 << 2)),
	(ASN_TAG_CLASS_APPLICATION | (172 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_QoSUsed = {
	"QoSUsed",
	"QoSUsed",
	&asn_OP_SEQUENCE,
	asn_DEF_QoSUsed_tags_1,
	sizeof(asn_DEF_QoSUsed_tags_1)
		/sizeof(asn_DEF_QoSUsed_tags_1[0]) - 2, /* 1 */
	asn_DEF_QoSUsed_tags_1,	/* Same as above */
	sizeof(asn_DEF_QoSUsed_tags_1)
		/sizeof(asn_DEF_QoSUsed_tags_1[0]), /* 3 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_QoSInformation_1,
	5,	/* Elements count */
	&asn_SPC_QoSInformation_specs_1	/* Additional specs */
};

