/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0301"
 * 	found in "TAP0301.asn1"
 * 	`asn1c -D E:/repos/tap3reader/src/pdus/tap/3_01`
 */

#ifndef	_RemotePdpAddressList_H_
#define	_RemotePdpAddressList_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PacketDataProtocolAddress.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RemotePdpAddressList */
typedef struct RemotePdpAddressList {
	A_SEQUENCE_OF(PacketDataProtocolAddress_t) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RemotePdpAddressList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RemotePdpAddressList;
extern asn_SET_OF_specifics_t asn_SPC_RemotePdpAddressList_specs_1;
extern asn_TYPE_member_t asn_MBR_RemotePdpAddressList_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _RemotePdpAddressList_H_ */
#include <asn_internal.h>
