/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0309"
 * 	found in "TAP0309.asn1"
 * 	`asn1c -D E:/repos/tap3reader/src/pdus/tap/3_09`
 */

#include "AuditControlInfo.h"

asn_TYPE_member_t asn_MBR_AuditControlInfo_1[] = {
	{ ATF_POINTER, 10, offsetof(struct AuditControlInfo, earliestCallTimeStamp),
		(ASN_TAG_CLASS_APPLICATION | (101 << 2)),
		0,
		&asn_DEF_EarliestCallTimeStamp,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"earliestCallTimeStamp"
		},
	{ ATF_POINTER, 9, offsetof(struct AuditControlInfo, latestCallTimeStamp),
		(ASN_TAG_CLASS_APPLICATION | (133 << 2)),
		0,
		&asn_DEF_LatestCallTimeStamp,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"latestCallTimeStamp"
		},
	{ ATF_POINTER, 8, offsetof(struct AuditControlInfo, totalChargeValueList),
		(ASN_TAG_CLASS_APPLICATION | (224 << 2)),
		0,
		&asn_DEF_TotalChargeValueList,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"totalChargeValueList"
		},
	{ ATF_POINTER, 7, offsetof(struct AuditControlInfo, totalTaxRefund),
		(ASN_TAG_CLASS_APPLICATION | (353 << 2)),
		0,
		&asn_DEF_TotalTaxRefund,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"totalTaxRefund"
		},
	{ ATF_POINTER, 6, offsetof(struct AuditControlInfo, totalTaxValue),
		(ASN_TAG_CLASS_APPLICATION | (226 << 2)),
		0,
		&asn_DEF_TotalTaxValue,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"totalTaxValue"
		},
	{ ATF_POINTER, 5, offsetof(struct AuditControlInfo, totalDiscountValue),
		(ASN_TAG_CLASS_APPLICATION | (225 << 2)),
		0,
		&asn_DEF_TotalDiscountValue,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"totalDiscountValue"
		},
	{ ATF_POINTER, 4, offsetof(struct AuditControlInfo, totalDiscountRefund),
		(ASN_TAG_CLASS_APPLICATION | (354 << 2)),
		0,
		&asn_DEF_TotalDiscountRefund,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"totalDiscountRefund"
		},
	{ ATF_POINTER, 3, offsetof(struct AuditControlInfo, totalAdvisedChargeValueList),
		(ASN_TAG_CLASS_APPLICATION | (361 << 2)),
		0,
		&asn_DEF_TotalAdvisedChargeValueList,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"totalAdvisedChargeValueList"
		},
	{ ATF_POINTER, 2, offsetof(struct AuditControlInfo, callEventDetailsCount),
		(ASN_TAG_CLASS_APPLICATION | (43 << 2)),
		0,
		&asn_DEF_CallEventDetailsCount,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"callEventDetailsCount"
		},
	{ ATF_POINTER, 1, offsetof(struct AuditControlInfo, operatorSpecInformation),
		(ASN_TAG_CLASS_APPLICATION | (162 << 2)),
		0,
		&asn_DEF_OperatorSpecInfoList,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"operatorSpecInformation"
		},
};
static const int asn_MAP_AuditControlInfo_oms_1[] = { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 };
static const ber_tlv_tag_t asn_DEF_AuditControlInfo_tags_1[] = {
	(ASN_TAG_CLASS_APPLICATION | (15 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_AuditControlInfo_tag2el_1[] = {
    { (ASN_TAG_CLASS_APPLICATION | (43 << 2)), 8, 0, 0 }, /* callEventDetailsCount */
    { (ASN_TAG_CLASS_APPLICATION | (101 << 2)), 0, 0, 0 }, /* earliestCallTimeStamp */
    { (ASN_TAG_CLASS_APPLICATION | (133 << 2)), 1, 0, 0 }, /* latestCallTimeStamp */
    { (ASN_TAG_CLASS_APPLICATION | (162 << 2)), 9, 0, 0 }, /* operatorSpecInformation */
    { (ASN_TAG_CLASS_APPLICATION | (224 << 2)), 2, 0, 0 }, /* totalChargeValueList */
    { (ASN_TAG_CLASS_APPLICATION | (225 << 2)), 5, 0, 0 }, /* totalDiscountValue */
    { (ASN_TAG_CLASS_APPLICATION | (226 << 2)), 4, 0, 0 }, /* totalTaxValue */
    { (ASN_TAG_CLASS_APPLICATION | (353 << 2)), 3, 0, 0 }, /* totalTaxRefund */
    { (ASN_TAG_CLASS_APPLICATION | (354 << 2)), 6, 0, 0 }, /* totalDiscountRefund */
    { (ASN_TAG_CLASS_APPLICATION | (361 << 2)), 7, 0, 0 } /* totalAdvisedChargeValueList */
};
asn_SEQUENCE_specifics_t asn_SPC_AuditControlInfo_specs_1 = {
	sizeof(struct AuditControlInfo),
	offsetof(struct AuditControlInfo, _asn_ctx),
	asn_MAP_AuditControlInfo_tag2el_1,
	10,	/* Count of tags in the map */
	asn_MAP_AuditControlInfo_oms_1,	/* Optional members */
	10, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_AuditControlInfo = {
	"AuditControlInfo",
	"AuditControlInfo",
	&asn_OP_SEQUENCE,
	asn_DEF_AuditControlInfo_tags_1,
	sizeof(asn_DEF_AuditControlInfo_tags_1)
		/sizeof(asn_DEF_AuditControlInfo_tags_1[0]) - 1, /* 1 */
	asn_DEF_AuditControlInfo_tags_1,	/* Same as above */
	sizeof(asn_DEF_AuditControlInfo_tags_1)
		/sizeof(asn_DEF_AuditControlInfo_tags_1[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_AuditControlInfo_1,
	10,	/* Elements count */
	&asn_SPC_AuditControlInfo_specs_1	/* Additional specs */
};

