/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0309"
 * 	found in "TAP0309.asn1"
 * 	`asn1c -D E:/repos/tap3reader/src/pdus/tap/3_09`
 */

#include "CallTypeGroup.h"

asn_TYPE_member_t asn_MBR_CallTypeGroup_1[] = {
	{ ATF_POINTER, 4, offsetof(struct CallTypeGroup, callTypeLevel1),
		(ASN_TAG_CLASS_APPLICATION | (259 << 2)),
		0,
		&asn_DEF_CallTypeLevel1,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"callTypeLevel1"
		},
	{ ATF_POINTER, 3, offsetof(struct CallTypeGroup, callTypeLevel2),
		(ASN_TAG_CLASS_APPLICATION | (255 << 2)),
		0,
		&asn_DEF_CallTypeLevel2,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"callTypeLevel2"
		},
	{ ATF_POINTER, 2, offsetof(struct CallTypeGroup, callTypeLevel3),
		(ASN_TAG_CLASS_APPLICATION | (256 << 2)),
		0,
		&asn_DEF_CallTypeLevel3,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"callTypeLevel3"
		},
	{ ATF_POINTER, 1, offsetof(struct CallTypeGroup, calledCountryCode),
		(ASN_TAG_CLASS_APPLICATION | (257 << 2)),
		0,
		&asn_DEF_CalledCountryCode,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"calledCountryCode"
		},
};
static const int asn_MAP_CallTypeGroup_oms_1[] = { 0, 1, 2, 3 };
static const ber_tlv_tag_t asn_DEF_CallTypeGroup_tags_1[] = {
	(ASN_TAG_CLASS_APPLICATION | (258 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_CallTypeGroup_tag2el_1[] = {
    { (ASN_TAG_CLASS_APPLICATION | (255 << 2)), 1, 0, 0 }, /* callTypeLevel2 */
    { (ASN_TAG_CLASS_APPLICATION | (256 << 2)), 2, 0, 0 }, /* callTypeLevel3 */
    { (ASN_TAG_CLASS_APPLICATION | (257 << 2)), 3, 0, 0 }, /* calledCountryCode */
    { (ASN_TAG_CLASS_APPLICATION | (259 << 2)), 0, 0, 0 } /* callTypeLevel1 */
};
asn_SEQUENCE_specifics_t asn_SPC_CallTypeGroup_specs_1 = {
	sizeof(struct CallTypeGroup),
	offsetof(struct CallTypeGroup, _asn_ctx),
	asn_MAP_CallTypeGroup_tag2el_1,
	4,	/* Count of tags in the map */
	asn_MAP_CallTypeGroup_oms_1,	/* Optional members */
	4, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_CallTypeGroup = {
	"CallTypeGroup",
	"CallTypeGroup",
	&asn_OP_SEQUENCE,
	asn_DEF_CallTypeGroup_tags_1,
	sizeof(asn_DEF_CallTypeGroup_tags_1)
		/sizeof(asn_DEF_CallTypeGroup_tags_1[0]) - 1, /* 1 */
	asn_DEF_CallTypeGroup_tags_1,	/* Same as above */
	sizeof(asn_DEF_CallTypeGroup_tags_1)
		/sizeof(asn_DEF_CallTypeGroup_tags_1[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_CallTypeGroup_1,
	4,	/* Elements count */
	&asn_SPC_CallTypeGroup_specs_1	/* Additional specs */
};

