/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0309"
 * 	found in "TAP0309.asn1"
 * 	`asn1c -D E:/repos/tap3reader/src/pdus/tap/3_09`
 */

#include "CallEventDetail.h"

#if !defined(ASN_DISABLE_OER_SUPPORT)
static asn_oer_constraints_t asn_OER_type_CallEventDetail_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_CallEventDetail_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  6 }	/* (0..6) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
asn_TYPE_member_t asn_MBR_CallEventDetail_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct CallEventDetail, choice.mobileOriginatedCall),
		(ASN_TAG_CLASS_APPLICATION | (9 << 2)),
		0,
		&asn_DEF_MobileOriginatedCall,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"mobileOriginatedCall"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CallEventDetail, choice.mobileTerminatedCall),
		(ASN_TAG_CLASS_APPLICATION | (10 << 2)),
		0,
		&asn_DEF_MobileTerminatedCall,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"mobileTerminatedCall"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CallEventDetail, choice.supplServiceEvent),
		(ASN_TAG_CLASS_APPLICATION | (11 << 2)),
		0,
		&asn_DEF_SupplServiceEvent,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"supplServiceEvent"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CallEventDetail, choice.serviceCentreUsage),
		(ASN_TAG_CLASS_APPLICATION | (12 << 2)),
		0,
		&asn_DEF_ServiceCentreUsage,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"serviceCentreUsage"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CallEventDetail, choice.valueAddedService),
		(ASN_TAG_CLASS_APPLICATION | (13 << 2)),
		0,
		&asn_DEF_ValueAddedService,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"valueAddedService"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CallEventDetail, choice.gprsCall),
		(ASN_TAG_CLASS_APPLICATION | (14 << 2)),
		0,
		&asn_DEF_GprsCall,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"gprsCall"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CallEventDetail, choice.contentTransaction),
		(ASN_TAG_CLASS_APPLICATION | (17 << 2)),
		0,
		&asn_DEF_ContentTransaction,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"contentTransaction"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_CallEventDetail_tag2el_1[] = {
    { (ASN_TAG_CLASS_APPLICATION | (9 << 2)), 0, 0, 0 }, /* mobileOriginatedCall */
    { (ASN_TAG_CLASS_APPLICATION | (10 << 2)), 1, 0, 0 }, /* mobileTerminatedCall */
    { (ASN_TAG_CLASS_APPLICATION | (11 << 2)), 2, 0, 0 }, /* supplServiceEvent */
    { (ASN_TAG_CLASS_APPLICATION | (12 << 2)), 3, 0, 0 }, /* serviceCentreUsage */
    { (ASN_TAG_CLASS_APPLICATION | (13 << 2)), 4, 0, 0 }, /* valueAddedService */
    { (ASN_TAG_CLASS_APPLICATION | (14 << 2)), 5, 0, 0 }, /* gprsCall */
    { (ASN_TAG_CLASS_APPLICATION | (17 << 2)), 6, 0, 0 } /* contentTransaction */
};
asn_CHOICE_specifics_t asn_SPC_CallEventDetail_specs_1 = {
	sizeof(struct CallEventDetail),
	offsetof(struct CallEventDetail, _asn_ctx),
	offsetof(struct CallEventDetail, present),
	sizeof(((struct CallEventDetail *)0)->present),
	asn_MAP_CallEventDetail_tag2el_1,
	7,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_CallEventDetail = {
	"CallEventDetail",
	"CallEventDetail",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		&asn_OER_type_CallEventDetail_constr_1,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_CallEventDetail_constr_1,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		CHOICE_constraint
	},
	asn_MBR_CallEventDetail_1,
	7,	/* Elements count */
	&asn_SPC_CallEventDetail_specs_1	/* Additional specs */
};

