/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0309"
 * 	found in "TAP0309.asn1"
 * 	`asn1c -D E:/repos/tap3reader/src/pdus/tap/3_09`
 */

#include "ChargedPartyIdentification.h"

#if !defined(ASN_DISABLE_OER_SUPPORT)
static asn_oer_constraints_t asn_OER_type_ChargedPartyIdentification_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_ChargedPartyIdentification_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  6 }	/* (0..6) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
asn_TYPE_member_t asn_MBR_ChargedPartyIdentification_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ChargedPartyIdentification, choice.msisdn),
		(ASN_TAG_CLASS_APPLICATION | (152 << 2)),
		0,
		&asn_DEF_Msisdn,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"msisdn"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ChargedPartyIdentification, choice.imsi),
		(ASN_TAG_CLASS_APPLICATION | (129 << 2)),
		0,
		&asn_DEF_Imsi,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"imsi"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ChargedPartyIdentification, choice.min),
		(ASN_TAG_CLASS_APPLICATION | (146 << 2)),
		0,
		&asn_DEF_Min,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"min"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ChargedPartyIdentification, choice.ipAddress),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_IpAddress,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"ipAddress"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ChargedPartyIdentification, choice.loginName),
		(ASN_TAG_CLASS_APPLICATION | (306 << 2)),
		0,
		&asn_DEF_LoginName,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"loginName"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ChargedPartyIdentification, choice.accountNumber),
		(ASN_TAG_CLASS_APPLICATION | (307 << 2)),
		0,
		&asn_DEF_AccountNumber,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"accountNumber"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ChargedPartyIdentification, choice.emailAddress),
		(ASN_TAG_CLASS_APPLICATION | (308 << 2)),
		0,
		&asn_DEF_EmailAddress,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"emailAddress"
		},
};
static const unsigned asn_MAP_ChargedPartyIdentification_to_canonical_1[] = { 1, 3, 2, 0, 4, 5, 6 };
static const unsigned asn_MAP_ChargedPartyIdentification_from_canonical_1[] = { 3, 0, 2, 1, 4, 5, 6 };
static const asn_TYPE_tag2member_t asn_MAP_ChargedPartyIdentification_tag2el_1[] = {
    { (ASN_TAG_CLASS_APPLICATION | (129 << 2)), 1, 0, 0 }, /* imsi */
    { (ASN_TAG_CLASS_APPLICATION | (131 << 2)), 3, 0, 0 }, /* iPTextV4Address */
    { (ASN_TAG_CLASS_APPLICATION | (132 << 2)), 3, 0, 0 }, /* iPTextV6Address */
    { (ASN_TAG_CLASS_APPLICATION | (146 << 2)), 2, 0, 0 }, /* min */
    { (ASN_TAG_CLASS_APPLICATION | (152 << 2)), 0, 0, 0 }, /* msisdn */
    { (ASN_TAG_CLASS_APPLICATION | (306 << 2)), 4, 0, 0 }, /* loginName */
    { (ASN_TAG_CLASS_APPLICATION | (307 << 2)), 5, 0, 0 }, /* accountNumber */
    { (ASN_TAG_CLASS_APPLICATION | (308 << 2)), 6, 0, 0 } /* emailAddress */
};
asn_CHOICE_specifics_t asn_SPC_ChargedPartyIdentification_specs_1 = {
	sizeof(struct ChargedPartyIdentification),
	offsetof(struct ChargedPartyIdentification, _asn_ctx),
	offsetof(struct ChargedPartyIdentification, present),
	sizeof(((struct ChargedPartyIdentification *)0)->present),
	asn_MAP_ChargedPartyIdentification_tag2el_1,
	8,	/* Count of tags in the map */
	asn_MAP_ChargedPartyIdentification_to_canonical_1,
	asn_MAP_ChargedPartyIdentification_from_canonical_1,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_ChargedPartyIdentification = {
	"ChargedPartyIdentification",
	"ChargedPartyIdentification",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		&asn_OER_type_ChargedPartyIdentification_constr_1,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_ChargedPartyIdentification_constr_1,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		CHOICE_constraint
	},
	asn_MBR_ChargedPartyIdentification_1,
	7,	/* Elements count */
	&asn_SPC_ChargedPartyIdentification_specs_1	/* Additional specs */
};

