/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0309"
 * 	found in "TAP0309.asn1"
 * 	`asn1c -D E:/repos/tap3reader/src/pdus/tap/3_09`
 */

#include "ChargedPartyHomeId.h"

asn_TYPE_member_t asn_MBR_ChargedPartyHomeId_1[] = {
	{ ATF_POINTER, 2, offsetof(struct ChargedPartyHomeId, homeIdType),
		(ASN_TAG_CLASS_APPLICATION | (311 << 2)),
		0,
		&asn_DEF_HomeIdType,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"homeIdType"
		},
	{ ATF_POINTER, 1, offsetof(struct ChargedPartyHomeId, homeIdentifier),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_HomeIdentifier,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"homeIdentifier"
		},
};
static const int asn_MAP_ChargedPartyHomeId_oms_1[] = { 0, 1 };
static const ber_tlv_tag_t asn_DEF_ChargedPartyHomeId_tags_1[] = {
	(ASN_TAG_CLASS_APPLICATION | (313 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ChargedPartyHomeId_tag2el_1[] = {
    { (ASN_TAG_CLASS_APPLICATION | (122 << 2)), 1, 0, 0 }, /* homeBid */
    { (ASN_TAG_CLASS_APPLICATION | (137 << 2)), 1, 0, 0 }, /* homeLocationDescription */
    { (ASN_TAG_CLASS_APPLICATION | (169 << 2)), 1, 0, 0 }, /* tadigCode */
    { (ASN_TAG_CLASS_APPLICATION | (311 << 2)), 0, 0, 0 }, /* homeIdType */
    { (ASN_TAG_CLASS_APPLICATION | (312 << 2)), 1, 0, 0 } /* name */
};
asn_SEQUENCE_specifics_t asn_SPC_ChargedPartyHomeId_specs_1 = {
	sizeof(struct ChargedPartyHomeId),
	offsetof(struct ChargedPartyHomeId, _asn_ctx),
	asn_MAP_ChargedPartyHomeId_tag2el_1,
	5,	/* Count of tags in the map */
	asn_MAP_ChargedPartyHomeId_oms_1,	/* Optional members */
	2, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_ChargedPartyHomeId = {
	"ChargedPartyHomeId",
	"ChargedPartyHomeId",
	&asn_OP_SEQUENCE,
	asn_DEF_ChargedPartyHomeId_tags_1,
	sizeof(asn_DEF_ChargedPartyHomeId_tags_1)
		/sizeof(asn_DEF_ChargedPartyHomeId_tags_1[0]) - 1, /* 1 */
	asn_DEF_ChargedPartyHomeId_tags_1,	/* Same as above */
	sizeof(asn_DEF_ChargedPartyHomeId_tags_1)
		/sizeof(asn_DEF_ChargedPartyHomeId_tags_1[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_ChargedPartyHomeId_1,
	2,	/* Elements count */
	&asn_SPC_ChargedPartyHomeId_specs_1	/* Additional specs */
};

