/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0309"
 * 	found in "TAP0309.asn1"
 * 	`asn1c -D E:/repos/tap3reader/src/pdus/tap/3_09`
 */

#include "ChargeableSubscriber.h"

#if !defined(ASN_DISABLE_OER_SUPPORT)
static asn_oer_constraints_t asn_OER_type_ChargeableSubscriber_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_ChargeableSubscriber_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
asn_TYPE_member_t asn_MBR_ChargeableSubscriber_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ChargeableSubscriber, choice.simChargeableSubscriber),
		(ASN_TAG_CLASS_APPLICATION | (199 << 2)),
		0,
		&asn_DEF_SimChargeableSubscriber,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"simChargeableSubscriber"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ChargeableSubscriber, choice.minChargeableSubscriber),
		(ASN_TAG_CLASS_APPLICATION | (254 << 2)),
		0,
		&asn_DEF_MinChargeableSubscriber,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"minChargeableSubscriber"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_ChargeableSubscriber_tag2el_1[] = {
    { (ASN_TAG_CLASS_APPLICATION | (199 << 2)), 0, 0, 0 }, /* simChargeableSubscriber */
    { (ASN_TAG_CLASS_APPLICATION | (254 << 2)), 1, 0, 0 } /* minChargeableSubscriber */
};
asn_CHOICE_specifics_t asn_SPC_ChargeableSubscriber_specs_1 = {
	sizeof(struct ChargeableSubscriber),
	offsetof(struct ChargeableSubscriber, _asn_ctx),
	offsetof(struct ChargeableSubscriber, present),
	sizeof(((struct ChargeableSubscriber *)0)->present),
	asn_MAP_ChargeableSubscriber_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_ChargeableSubscriber = {
	"ChargeableSubscriber",
	"ChargeableSubscriber",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		&asn_OER_type_ChargeableSubscriber_constr_1,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_ChargeableSubscriber_constr_1,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		CHOICE_constraint
	},
	asn_MBR_ChargeableSubscriber_1,
	2,	/* Elements count */
	&asn_SPC_ChargeableSubscriber_specs_1	/* Additional specs */
};

