/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0309"
 * 	found in "TAP0309.asn1"
 * 	`asn1c -D E:/repos/tap3reader/src/pdus/tap/3_09`
 */

#ifndef	_ChargedPartyHomeIdList_H_
#define	_ChargedPartyHomeIdList_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ChargedPartyHomeId;

/* ChargedPartyHomeIdList */
typedef struct ChargedPartyHomeIdList {
	A_SEQUENCE_OF(struct ChargedPartyHomeId) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ChargedPartyHomeIdList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ChargedPartyHomeIdList;
extern asn_SET_OF_specifics_t asn_SPC_ChargedPartyHomeIdList_specs_1;
extern asn_TYPE_member_t asn_MBR_ChargedPartyHomeIdList_1[1];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ChargedPartyHomeId.h"

#endif	/* _ChargedPartyHomeIdList_H_ */
#include <asn_internal.h>
