/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0309"
 * 	found in "TAP0309.asn1"
 * 	`asn1c -D E:/repos/tap3reader/src/pdus/tap/3_09`
 */

#include "ContentTransaction.h"

asn_TYPE_member_t asn_MBR_ContentTransaction_1[] = {
	{ ATF_POINTER, 5, offsetof(struct ContentTransaction, contentTransactionBasicInfo),
		(ASN_TAG_CLASS_APPLICATION | (304 << 2)),
		0,
		&asn_DEF_ContentTransactionBasicInfo,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"contentTransactionBasicInfo"
		},
	{ ATF_POINTER, 4, offsetof(struct ContentTransaction, chargedPartyInformation),
		(ASN_TAG_CLASS_APPLICATION | (324 << 2)),
		0,
		&asn_DEF_ChargedPartyInformation,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"chargedPartyInformation"
		},
	{ ATF_POINTER, 3, offsetof(struct ContentTransaction, servingPartiesInformation),
		(ASN_TAG_CLASS_APPLICATION | (335 << 2)),
		0,
		&asn_DEF_ServingPartiesInformation,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"servingPartiesInformation"
		},
	{ ATF_POINTER, 2, offsetof(struct ContentTransaction, contentServiceUsed),
		(ASN_TAG_CLASS_APPLICATION | (352 << 2)),
		0,
		&asn_DEF_ContentServiceUsed,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"contentServiceUsed"
		},
	{ ATF_POINTER, 1, offsetof(struct ContentTransaction, operatorSpecInformation),
		(ASN_TAG_CLASS_APPLICATION | (162 << 2)),
		0,
		&asn_DEF_OperatorSpecInfoList,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"operatorSpecInformation"
		},
};
static const int asn_MAP_ContentTransaction_oms_1[] = { 0, 1, 2, 3, 4 };
static const ber_tlv_tag_t asn_DEF_ContentTransaction_tags_1[] = {
	(ASN_TAG_CLASS_APPLICATION | (17 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ContentTransaction_tag2el_1[] = {
    { (ASN_TAG_CLASS_APPLICATION | (162 << 2)), 4, 0, 0 }, /* operatorSpecInformation */
    { (ASN_TAG_CLASS_APPLICATION | (304 << 2)), 0, 0, 0 }, /* contentTransactionBasicInfo */
    { (ASN_TAG_CLASS_APPLICATION | (324 << 2)), 1, 0, 0 }, /* chargedPartyInformation */
    { (ASN_TAG_CLASS_APPLICATION | (335 << 2)), 2, 0, 0 }, /* servingPartiesInformation */
    { (ASN_TAG_CLASS_APPLICATION | (352 << 2)), 3, 0, 0 } /* contentServiceUsed */
};
asn_SEQUENCE_specifics_t asn_SPC_ContentTransaction_specs_1 = {
	sizeof(struct ContentTransaction),
	offsetof(struct ContentTransaction, _asn_ctx),
	asn_MAP_ContentTransaction_tag2el_1,
	5,	/* Count of tags in the map */
	asn_MAP_ContentTransaction_oms_1,	/* Optional members */
	5, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_ContentTransaction = {
	"ContentTransaction",
	"ContentTransaction",
	&asn_OP_SEQUENCE,
	asn_DEF_ContentTransaction_tags_1,
	sizeof(asn_DEF_ContentTransaction_tags_1)
		/sizeof(asn_DEF_ContentTransaction_tags_1[0]) - 1, /* 1 */
	asn_DEF_ContentTransaction_tags_1,	/* Same as above */
	sizeof(asn_DEF_ContentTransaction_tags_1)
		/sizeof(asn_DEF_ContentTransaction_tags_1[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_ContentTransaction_1,
	5,	/* Elements count */
	&asn_SPC_ContentTransaction_specs_1	/* Additional specs */
};

