/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0309"
 * 	found in "TAP0309.asn1"
 * 	`asn1c -D E:/repos/tap3reader/src/pdus/tap/3_09`
 */

#include "GprsDestination.h"

asn_TYPE_member_t asn_MBR_GprsDestination_1[] = {
	{ ATF_POINTER, 3, offsetof(struct GprsDestination, accessPointNameNI),
		(ASN_TAG_CLASS_APPLICATION | (261 << 2)),
		0,
		&asn_DEF_AccessPointNameNI,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"accessPointNameNI"
		},
	{ ATF_POINTER, 2, offsetof(struct GprsDestination, accessPointNameOI),
		(ASN_TAG_CLASS_APPLICATION | (262 << 2)),
		0,
		&asn_DEF_AccessPointNameOI,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"accessPointNameOI"
		},
	{ ATF_POINTER, 1, offsetof(struct GprsDestination, remotePdpAddressList),
		(ASN_TAG_CLASS_APPLICATION | (190 << 2)),
		0,
		&asn_DEF_RemotePdpAddressList,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"remotePdpAddressList"
		},
};
static const int asn_MAP_GprsDestination_oms_1[] = { 0, 1, 2 };
static const ber_tlv_tag_t asn_DEF_GprsDestination_tags_1[] = {
	(ASN_TAG_CLASS_APPLICATION | (116 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_GprsDestination_tag2el_1[] = {
    { (ASN_TAG_CLASS_APPLICATION | (190 << 2)), 2, 0, 0 }, /* remotePdpAddressList */
    { (ASN_TAG_CLASS_APPLICATION | (261 << 2)), 0, 0, 0 }, /* accessPointNameNI */
    { (ASN_TAG_CLASS_APPLICATION | (262 << 2)), 1, 0, 0 } /* accessPointNameOI */
};
asn_SEQUENCE_specifics_t asn_SPC_GprsDestination_specs_1 = {
	sizeof(struct GprsDestination),
	offsetof(struct GprsDestination, _asn_ctx),
	asn_MAP_GprsDestination_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_GprsDestination_oms_1,	/* Optional members */
	3, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_GprsDestination = {
	"GprsDestination",
	"GprsDestination",
	&asn_OP_SEQUENCE,
	asn_DEF_GprsDestination_tags_1,
	sizeof(asn_DEF_GprsDestination_tags_1)
		/sizeof(asn_DEF_GprsDestination_tags_1[0]) - 1, /* 1 */
	asn_DEF_GprsDestination_tags_1,	/* Same as above */
	sizeof(asn_DEF_GprsDestination_tags_1)
		/sizeof(asn_DEF_GprsDestination_tags_1[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_GprsDestination_1,
	3,	/* Elements count */
	&asn_SPC_GprsDestination_specs_1	/* Additional specs */
};

