/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0309"
 * 	found in "TAP0309.asn1"
 * 	`asn1c -D E:/repos/tap3reader/src/pdus/tap/3_09`
 */

#include "InternetServiceProviderId.h"

asn_TYPE_member_t asn_MBR_InternetServiceProviderId_1[] = {
	{ ATF_POINTER, 2, offsetof(struct InternetServiceProviderId, internetServiceProviderIdType),
		(ASN_TAG_CLASS_APPLICATION | (325 << 2)),
		0,
		&asn_DEF_ProviderIdType,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"internetServiceProviderIdType"
		},
	{ ATF_POINTER, 1, offsetof(struct InternetServiceProviderId, internetServiceProviderId),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_ProviderId,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"internetServiceProviderId"
		},
};
static const int asn_MAP_InternetServiceProviderId_oms_1[] = { 0, 1 };
static const ber_tlv_tag_t asn_DEF_InternetServiceProviderId_tags_1[] = {
	(ASN_TAG_CLASS_APPLICATION | (329 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_InternetServiceProviderId_tag2el_1[] = {
    { (ASN_TAG_CLASS_APPLICATION | (131 << 2)), 1, 0, 0 }, /* iPTextV4Address */
    { (ASN_TAG_CLASS_APPLICATION | (132 << 2)), 1, 0, 0 }, /* iPTextV6Address */
    { (ASN_TAG_CLASS_APPLICATION | (169 << 2)), 1, 0, 0 }, /* tadigCode */
    { (ASN_TAG_CLASS_APPLICATION | (312 << 2)), 1, 0, 0 }, /* name */
    { (ASN_TAG_CLASS_APPLICATION | (325 << 2)), 0, 0, 0 }, /* internetServiceProviderIdType */
    { (ASN_TAG_CLASS_APPLICATION | (326 << 2)), 1, 0, 0 } /* url */
};
asn_SEQUENCE_specifics_t asn_SPC_InternetServiceProviderId_specs_1 = {
	sizeof(struct InternetServiceProviderId),
	offsetof(struct InternetServiceProviderId, _asn_ctx),
	asn_MAP_InternetServiceProviderId_tag2el_1,
	6,	/* Count of tags in the map */
	asn_MAP_InternetServiceProviderId_oms_1,	/* Optional members */
	2, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_InternetServiceProviderId = {
	"InternetServiceProviderId",
	"InternetServiceProviderId",
	&asn_OP_SEQUENCE,
	asn_DEF_InternetServiceProviderId_tags_1,
	sizeof(asn_DEF_InternetServiceProviderId_tags_1)
		/sizeof(asn_DEF_InternetServiceProviderId_tags_1[0]) - 1, /* 1 */
	asn_DEF_InternetServiceProviderId_tags_1,	/* Same as above */
	sizeof(asn_DEF_InternetServiceProviderId_tags_1)
		/sizeof(asn_DEF_InternetServiceProviderId_tags_1[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_InternetServiceProviderId_1,
	2,	/* Elements count */
	&asn_SPC_InternetServiceProviderId_specs_1	/* Additional specs */
};

