/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0309"
 * 	found in "TAP0309.asn1"
 * 	`asn1c -D E:/repos/tap3reader/src/pdus/tap/3_09`
 */

#include "NetworkDesc.h"

#if !defined(ASN_DISABLE_OER_SUPPORT)
static asn_oer_constraints_t asn_OER_type_NetworkDesc_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_NetworkDesc_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  4 }	/* (0..4) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
asn_TYPE_member_t asn_MBR_NetworkDesc_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct NetworkDesc, choice.name),
		(ASN_TAG_CLASS_APPLICATION | (312 << 2)),
		0,
		&asn_DEF_Name,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"name"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct NetworkDesc, choice.tadigCode),
		(ASN_TAG_CLASS_APPLICATION | (169 << 2)),
		0,
		&asn_DEF_PlmnId,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"tadigCode"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct NetworkDesc, choice.homeBid),
		(ASN_TAG_CLASS_APPLICATION | (122 << 2)),
		0,
		&asn_DEF_HomeBid,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"homeBid"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct NetworkDesc, choice.homeLocationDescription),
		(ASN_TAG_CLASS_APPLICATION | (137 << 2)),
		0,
		&asn_DEF_LocationDescription,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"homeLocationDescription"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct NetworkDesc, choice.apn),
		(ASN_TAG_CLASS_APPLICATION | (32 << 2)),
		0,
		&asn_DEF_AccessPointName,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"apn"
		},
};
static const unsigned asn_MAP_NetworkDesc_to_canonical_1[] = { 4, 2, 3, 1, 0 };
static const unsigned asn_MAP_NetworkDesc_from_canonical_1[] = { 4, 3, 1, 2, 0 };
static const asn_TYPE_tag2member_t asn_MAP_NetworkDesc_tag2el_1[] = {
    { (ASN_TAG_CLASS_APPLICATION | (32 << 2)), 4, 0, 0 }, /* apn */
    { (ASN_TAG_CLASS_APPLICATION | (122 << 2)), 2, 0, 0 }, /* homeBid */
    { (ASN_TAG_CLASS_APPLICATION | (137 << 2)), 3, 0, 0 }, /* homeLocationDescription */
    { (ASN_TAG_CLASS_APPLICATION | (169 << 2)), 1, 0, 0 }, /* tadigCode */
    { (ASN_TAG_CLASS_APPLICATION | (312 << 2)), 0, 0, 0 } /* name */
};
asn_CHOICE_specifics_t asn_SPC_NetworkDesc_specs_1 = {
	sizeof(struct NetworkDesc),
	offsetof(struct NetworkDesc, _asn_ctx),
	offsetof(struct NetworkDesc, present),
	sizeof(((struct NetworkDesc *)0)->present),
	asn_MAP_NetworkDesc_tag2el_1,
	5,	/* Count of tags in the map */
	asn_MAP_NetworkDesc_to_canonical_1,
	asn_MAP_NetworkDesc_from_canonical_1,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_NetworkDesc = {
	"NetworkDesc",
	"NetworkDesc",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		&asn_OER_type_NetworkDesc_constr_1,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_NetworkDesc_constr_1,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		CHOICE_constraint
	},
	asn_MBR_NetworkDesc_1,
	5,	/* Elements count */
	&asn_SPC_NetworkDesc_specs_1	/* Additional specs */
};

