/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0309"
 * 	found in "TAP0309.asn1"
 * 	`asn1c -D E:/repos/tap3reader/src/pdus/tap/3_09`
 */

#ifndef	_ServingPartiesInformation_H_
#define	_ServingPartiesInformation_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ContentProviderName.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ContentProviderIdList;
struct InternetServiceProviderIdList;
struct NetworkIdList;

/* ServingPartiesInformation */
typedef struct ServingPartiesInformation {
	ContentProviderName_t	*contentProviderName;	/* OPTIONAL */
	struct ContentProviderIdList	*contentProviderIdList;	/* OPTIONAL */
	struct InternetServiceProviderIdList	*internetServiceProviderIdList;	/* OPTIONAL */
	struct NetworkIdList	*networkIdList;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ServingPartiesInformation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ServingPartiesInformation;
extern asn_SEQUENCE_specifics_t asn_SPC_ServingPartiesInformation_specs_1;
extern asn_TYPE_member_t asn_MBR_ServingPartiesInformation_1[4];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ContentProviderIdList.h"
#include "InternetServiceProviderIdList.h"
#include "NetworkIdList.h"

#endif	/* _ServingPartiesInformation_H_ */
#include <asn_internal.h>
