/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0309"
 * 	found in "TAP0309.asn1"
 * 	`asn1c -D E:/repos/tap3reader/src/pdus/tap/3_09`
 */

#include "ThreeGcamelDestination.h"

#if !defined(ASN_DISABLE_OER_SUPPORT)
static asn_oer_constraints_t asn_OER_type_ThreeGcamelDestination_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_ThreeGcamelDestination_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
asn_TYPE_member_t asn_MBR_ThreeGcamelDestination_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ThreeGcamelDestination, choice.camelDestination),
		(ASN_TAG_CLASS_APPLICATION | (51 << 2)),
		0,
		&asn_DEF_CamelDestination,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"camelDestination"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ThreeGcamelDestination, choice.gprsDestination),
		(ASN_TAG_CLASS_APPLICATION | (116 << 2)),
		0,
		&asn_DEF_GprsDestination,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"gprsDestination"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_ThreeGcamelDestination_tag2el_1[] = {
    { (ASN_TAG_CLASS_APPLICATION | (51 << 2)), 0, 0, 0 }, /* camelDestination */
    { (ASN_TAG_CLASS_APPLICATION | (116 << 2)), 1, 0, 0 } /* gprsDestination */
};
asn_CHOICE_specifics_t asn_SPC_ThreeGcamelDestination_specs_1 = {
	sizeof(struct ThreeGcamelDestination),
	offsetof(struct ThreeGcamelDestination, _asn_ctx),
	offsetof(struct ThreeGcamelDestination, present),
	sizeof(((struct ThreeGcamelDestination *)0)->present),
	asn_MAP_ThreeGcamelDestination_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_ThreeGcamelDestination = {
	"ThreeGcamelDestination",
	"ThreeGcamelDestination",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		&asn_OER_type_ThreeGcamelDestination_constr_1,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_ThreeGcamelDestination_constr_1,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		CHOICE_constraint
	},
	asn_MBR_ThreeGcamelDestination_1,
	2,	/* Elements count */
	&asn_SPC_ThreeGcamelDestination_specs_1	/* Additional specs */
};

