/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0309"
 * 	found in "TAP0309.asn1"
 * 	`asn1c -D E:/repos/tap3reader/src/pdus/tap/3_09`
 */

#ifndef	_TotalAdvisedChargeRefund_H_
#define	_TotalAdvisedChargeRefund_H_


#include <asn_application.h>

/* Including external dependencies */
#include "AbsoluteAmount.h"

#ifdef __cplusplus
extern "C" {
#endif

/* TotalAdvisedChargeRefund */
typedef AbsoluteAmount_t	 TotalAdvisedChargeRefund_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TotalAdvisedChargeRefund;
asn_struct_free_f TotalAdvisedChargeRefund_free;
asn_struct_print_f TotalAdvisedChargeRefund_print;
asn_constr_check_f TotalAdvisedChargeRefund_constraint;
ber_type_decoder_f TotalAdvisedChargeRefund_decode_ber;
der_type_encoder_f TotalAdvisedChargeRefund_encode_der;
xer_type_decoder_f TotalAdvisedChargeRefund_decode_xer;
xer_type_encoder_f TotalAdvisedChargeRefund_encode_xer;
jer_type_encoder_f TotalAdvisedChargeRefund_encode_jer;
oer_type_decoder_f TotalAdvisedChargeRefund_decode_oer;
oer_type_encoder_f TotalAdvisedChargeRefund_encode_oer;
per_type_decoder_f TotalAdvisedChargeRefund_decode_uper;
per_type_encoder_f TotalAdvisedChargeRefund_encode_uper;
per_type_decoder_f TotalAdvisedChargeRefund_decode_aper;
per_type_encoder_f TotalAdvisedChargeRefund_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _TotalAdvisedChargeRefund_H_ */
#include <asn_internal.h>
