/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0302"
 * 	found in "TAP0302.asn1"
 * 	`asn1c -D E:/repos/tap3reader/src/pdus/tap/3_02`
 */

#ifndef	_CamelServiceUsed_H_
#define	_CamelServiceUsed_H_


#include <asn_application.h>

/* Including external dependencies */
#include "TypeOfNumber.h"
#include "NumberingPlan.h"
#include "AddressStringDigits.h"
#include "CamelServiceLevel.h"
#include "CamelServiceKey.h"
#include "DefaultCallHandlingIndicator.h"
#include "CamelInitiatedCFIndicator.h"
#include "CseInformation.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct CamelCallReference;
struct ChargeInformation;
struct CamelModificationList;
struct CamelDestination;

/* CamelServiceUsed */
typedef struct CamelServiceUsed {
	TypeOfNumber_t	*typeOfNumber;	/* OPTIONAL */
	NumberingPlan_t	*numberingPlan;	/* OPTIONAL */
	AddressStringDigits_t	*camelServerAddress;	/* OPTIONAL */
	CamelServiceLevel_t	*camelServiceLevel;	/* OPTIONAL */
	CamelServiceKey_t	*camelServiceKey;	/* OPTIONAL */
	DefaultCallHandlingIndicator_t	*defaultCallHandling;	/* OPTIONAL */
	struct CamelCallReference	*camelCallReference;	/* OPTIONAL */
	struct ChargeInformation	*camelChargeInformation;	/* OPTIONAL */
	CamelInitiatedCFIndicator_t	*camelInitiatedCFIndicator;	/* OPTIONAL */
	struct CamelModificationList	*camelModificationList;	/* OPTIONAL */
	struct CamelDestination	*camelDestination;	/* OPTIONAL */
	CseInformation_t	*cseInformation;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CamelServiceUsed_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CamelServiceUsed;
extern asn_SEQUENCE_specifics_t asn_SPC_CamelServiceUsed_specs_1;
extern asn_TYPE_member_t asn_MBR_CamelServiceUsed_1[12];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "CamelCallReference.h"
#include "ChargeInformation.h"
#include "CamelModificationList.h"
#include "CamelDestination.h"

#endif	/* _CamelServiceUsed_H_ */
#include <asn_internal.h>
