/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0302"
 * 	found in "TAP0302.asn1"
 * 	`asn1c -D E:/repos/tap3reader/src/pdus/tap/3_02`
 */

#ifndef	_ExchangeRateDefinition_H_
#define	_ExchangeRateDefinition_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ExchangeRateCode.h"
#include "NumberOfDecimalPlaces.h"
#include "ExchangeRate.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ExchangeRateDefinition */
typedef struct ExchangeRateDefinition {
	ExchangeRateCode_t	*exchangeRateCode;	/* OPTIONAL */
	NumberOfDecimalPlaces_t	*numberOfDecimalPlaces;	/* OPTIONAL */
	ExchangeRate_t	*exchangeRate;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ExchangeRateDefinition_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ExchangeRateDefinition;
extern asn_SEQUENCE_specifics_t asn_SPC_ExchangeRateDefinition_specs_1;
extern asn_TYPE_member_t asn_MBR_ExchangeRateDefinition_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _ExchangeRateDefinition_H_ */
#include <asn_internal.h>
