/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0302"
 * 	found in "TAP0302.asn1"
 * 	`asn1c -D E:/repos/tap3reader/src/pdus/tap/3_02`
 */

#ifndef	_NetworkInfo_H_
#define	_NetworkInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include "NetworkType.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct UtcTimeOffsetInfo;
struct RecEntityTable;
struct CalledNumAnalysisList;

/* NetworkInfo */
typedef struct NetworkInfo {
	struct UtcTimeOffsetInfo	*utcTimeOffsetInfo;	/* OPTIONAL */
	struct RecEntityTable	*recEntityInfo;	/* OPTIONAL */
	NetworkType_t	*networkType;	/* OPTIONAL */
	struct CalledNumAnalysisList	*calledNumAnalysis;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NetworkInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NetworkInfo;
extern asn_SEQUENCE_specifics_t asn_SPC_NetworkInfo_specs_1;
extern asn_TYPE_member_t asn_MBR_NetworkInfo_1[4];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "UtcTimeOffsetInfo.h"
#include "RecEntityTable.h"
#include "CalledNumAnalysisList.h"

#endif	/* _NetworkInfo_H_ */
#include <asn_internal.h>
