/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0302"
 * 	found in "TAP0302.asn1"
 * 	`asn1c -D E:/repos/tap3reader/src/pdus/tap/3_02`
 */

#ifndef	_RadioChannelRequested_H_
#define	_RadioChannelRequested_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RadioChannelRequested */
typedef long	 RadioChannelRequested_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RadioChannelRequested;
asn_struct_free_f RadioChannelRequested_free;
asn_struct_print_f RadioChannelRequested_print;
asn_constr_check_f RadioChannelRequested_constraint;
ber_type_decoder_f RadioChannelRequested_decode_ber;
der_type_encoder_f RadioChannelRequested_encode_der;
xer_type_decoder_f RadioChannelRequested_decode_xer;
xer_type_encoder_f RadioChannelRequested_encode_xer;
jer_type_encoder_f RadioChannelRequested_encode_jer;
oer_type_decoder_f RadioChannelRequested_decode_oer;
oer_type_encoder_f RadioChannelRequested_encode_oer;
per_type_decoder_f RadioChannelRequested_decode_uper;
per_type_encoder_f RadioChannelRequested_encode_uper;
per_type_decoder_f RadioChannelRequested_decode_aper;
per_type_encoder_f RadioChannelRequested_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _RadioChannelRequested_H_ */
#include <asn_internal.h>
