/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0302"
 * 	found in "TAP0302.asn1"
 * 	`asn1c -D E:/repos/tap3reader/src/pdus/tap/3_02`
 */

#include "ScuBasicInformation.h"

asn_TYPE_member_t asn_MBR_ScuBasicInformation_1[] = {
	{ ATF_POINTER, 6, offsetof(struct ScuBasicInformation, chargeableSubscriber),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_ScuVasChargeableSubscriber,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"chargeableSubscriber"
		},
	{ ATF_POINTER, 5, offsetof(struct ScuBasicInformation, chargedPartyStatus),
		(ASN_TAG_CLASS_APPLICATION | (67 << 2)),
		0,
		&asn_DEF_ChargedPartyStatus,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"chargedPartyStatus"
		},
	{ ATF_POINTER, 4, offsetof(struct ScuBasicInformation, nonChargedParty),
		(ASN_TAG_CLASS_APPLICATION | (158 << 2)),
		0,
		&asn_DEF_NonChargedParty,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"nonChargedParty"
		},
	{ ATF_POINTER, 3, offsetof(struct ScuBasicInformation, clirIndicator),
		(ASN_TAG_CLASS_APPLICATION | (75 << 2)),
		0,
		&asn_DEF_ClirIndicator,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"clirIndicator"
		},
	{ ATF_POINTER, 2, offsetof(struct ScuBasicInformation, originatingNetwork),
		(ASN_TAG_CLASS_APPLICATION | (164 << 2)),
		0,
		&asn_DEF_OriginatingNetwork,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"originatingNetwork"
		},
	{ ATF_POINTER, 1, offsetof(struct ScuBasicInformation, destinationNetwork),
		(ASN_TAG_CLASS_APPLICATION | (90 << 2)),
		0,
		&asn_DEF_DestinationNetwork,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"destinationNetwork"
		},
};
static const int asn_MAP_ScuBasicInformation_oms_1[] = { 0, 1, 2, 3, 4, 5 };
static const ber_tlv_tag_t asn_DEF_ScuBasicInformation_tags_1[] = {
	(ASN_TAG_CLASS_APPLICATION | (191 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ScuBasicInformation_tag2el_1[] = {
    { (ASN_TAG_CLASS_APPLICATION | (67 << 2)), 1, 0, 0 }, /* chargedPartyStatus */
    { (ASN_TAG_CLASS_APPLICATION | (75 << 2)), 3, 0, 0 }, /* clirIndicator */
    { (ASN_TAG_CLASS_APPLICATION | (90 << 2)), 5, 0, 0 }, /* destinationNetwork */
    { (ASN_TAG_CLASS_APPLICATION | (146 << 2)), 0, 0, 0 }, /* min */
    { (ASN_TAG_CLASS_APPLICATION | (152 << 2)), 0, 0, 0 }, /* msisdn */
    { (ASN_TAG_CLASS_APPLICATION | (158 << 2)), 2, 0, 0 }, /* nonChargedParty */
    { (ASN_TAG_CLASS_APPLICATION | (164 << 2)), 4, 0, 0 }, /* originatingNetwork */
    { (ASN_TAG_CLASS_APPLICATION | (199 << 2)), 0, 0, 0 } /* simChargeableSubscriber */
};
asn_SEQUENCE_specifics_t asn_SPC_ScuBasicInformation_specs_1 = {
	sizeof(struct ScuBasicInformation),
	offsetof(struct ScuBasicInformation, _asn_ctx),
	asn_MAP_ScuBasicInformation_tag2el_1,
	8,	/* Count of tags in the map */
	asn_MAP_ScuBasicInformation_oms_1,	/* Optional members */
	6, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_ScuBasicInformation = {
	"ScuBasicInformation",
	"ScuBasicInformation",
	&asn_OP_SEQUENCE,
	asn_DEF_ScuBasicInformation_tags_1,
	sizeof(asn_DEF_ScuBasicInformation_tags_1)
		/sizeof(asn_DEF_ScuBasicInformation_tags_1[0]) - 1, /* 1 */
	asn_DEF_ScuBasicInformation_tags_1,	/* Same as above */
	sizeof(asn_DEF_ScuBasicInformation_tags_1)
		/sizeof(asn_DEF_ScuBasicInformation_tags_1[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_ScuBasicInformation_1,
	6,	/* Elements count */
	&asn_SPC_ScuBasicInformation_specs_1	/* Additional specs */
};

