SET(TAP0311_MODULE_SOURCES
	${CMAKE_CURRENT_LIST_DIR}/AbsoluteAmount.c
	${CMAKE_CURRENT_LIST_DIR}/AccessPointNameNI.c
	${CMAKE_CURRENT_LIST_DIR}/AccessPointNameOI.c
	${CMAKE_CURRENT_LIST_DIR}/AccountingInfo.c
	${CMAKE_CURRENT_LIST_DIR}/ActualDeliveryTimeStamp.c
	${CMAKE_CURRENT_LIST_DIR}/AddressStringDigits.c
	${CMAKE_CURRENT_LIST_DIR}/AdvisedCharge.c
	${CMAKE_CURRENT_LIST_DIR}/AdvisedChargeCurrency.c
	${CMAKE_CURRENT_LIST_DIR}/AdvisedChargeInformation.c
	${CMAKE_CURRENT_LIST_DIR}/AgeOfLocation.c
	${CMAKE_CURRENT_LIST_DIR}/ANY.c
	${CMAKE_CURRENT_LIST_DIR}/ANY_aper.c
	${CMAKE_CURRENT_LIST_DIR}/ANY_ber.c
	${CMAKE_CURRENT_LIST_DIR}/ANY_jer.c
	${CMAKE_CURRENT_LIST_DIR}/ANY_uper.c
	${CMAKE_CURRENT_LIST_DIR}/ANY_xer.c
	${CMAKE_CURRENT_LIST_DIR}/aper_decoder.c
	${CMAKE_CURRENT_LIST_DIR}/aper_encoder.c
	${CMAKE_CURRENT_LIST_DIR}/aper_opentype.c
	${CMAKE_CURRENT_LIST_DIR}/aper_support.c
	${CMAKE_CURRENT_LIST_DIR}/AsciiString.c
	${CMAKE_CURRENT_LIST_DIR}/asn_application.c
	${CMAKE_CURRENT_LIST_DIR}/asn_bit_data.c
	${CMAKE_CURRENT_LIST_DIR}/asn_codecs_prim.c
	${CMAKE_CURRENT_LIST_DIR}/asn_codecs_prim_ber.c
	${CMAKE_CURRENT_LIST_DIR}/asn_codecs_prim_xer.c
	${CMAKE_CURRENT_LIST_DIR}/asn_internal.c
	${CMAKE_CURRENT_LIST_DIR}/asn_random_fill.c
	${CMAKE_CURRENT_LIST_DIR}/asn_SEQUENCE_OF.c
	${CMAKE_CURRENT_LIST_DIR}/asn_SET_OF.c
	${CMAKE_CURRENT_LIST_DIR}/AuditControlInfo.c
	${CMAKE_CURRENT_LIST_DIR}/BasicService.c
	${CMAKE_CURRENT_LIST_DIR}/BasicServiceCode.c
	${CMAKE_CURRENT_LIST_DIR}/BasicServiceCodeList.c
	${CMAKE_CURRENT_LIST_DIR}/BasicServiceUsed.c
	${CMAKE_CURRENT_LIST_DIR}/BasicServiceUsedList.c
	${CMAKE_CURRENT_LIST_DIR}/BatchControlInfo.c
	${CMAKE_CURRENT_LIST_DIR}/BCDString.c
	${CMAKE_CURRENT_LIST_DIR}/BearerServiceCode.c
	${CMAKE_CURRENT_LIST_DIR}/ber_decoder.c
	${CMAKE_CURRENT_LIST_DIR}/ber_tlv_length.c
	${CMAKE_CURRENT_LIST_DIR}/ber_tlv_tag.c
	${CMAKE_CURRENT_LIST_DIR}/Bid.c
	${CMAKE_CURRENT_LIST_DIR}/BIT_STRING.c
	${CMAKE_CURRENT_LIST_DIR}/BIT_STRING_jer.c
	${CMAKE_CURRENT_LIST_DIR}/BIT_STRING_oer.c
	${CMAKE_CURRENT_LIST_DIR}/BIT_STRING_print.c
	${CMAKE_CURRENT_LIST_DIR}/BIT_STRING_rfill.c
	${CMAKE_CURRENT_LIST_DIR}/BIT_STRING_uper.c
	${CMAKE_CURRENT_LIST_DIR}/BIT_STRING_xer.c
	${CMAKE_CURRENT_LIST_DIR}/CalledNumber.c
	${CMAKE_CURRENT_LIST_DIR}/CalledPlace.c
	${CMAKE_CURRENT_LIST_DIR}/CalledRegion.c
	${CMAKE_CURRENT_LIST_DIR}/CallEventDetail.c
	${CMAKE_CURRENT_LIST_DIR}/CallEventDetailList.c
	${CMAKE_CURRENT_LIST_DIR}/CallEventDetailsCount.c
	${CMAKE_CURRENT_LIST_DIR}/CallEventStartTimeStamp.c
	${CMAKE_CURRENT_LIST_DIR}/CallingNumber.c
	${CMAKE_CURRENT_LIST_DIR}/CallOriginator.c
	${CMAKE_CURRENT_LIST_DIR}/CallReference.c
	${CMAKE_CURRENT_LIST_DIR}/CallTypeGroup.c
	${CMAKE_CURRENT_LIST_DIR}/CallTypeLevel1.c
	${CMAKE_CURRENT_LIST_DIR}/CallTypeLevel2.c
	${CMAKE_CURRENT_LIST_DIR}/CallTypeLevel3.c
	${CMAKE_CURRENT_LIST_DIR}/CamelDestinationNumber.c
	${CMAKE_CURRENT_LIST_DIR}/CamelInvocationFee.c
	${CMAKE_CURRENT_LIST_DIR}/CamelServiceKey.c
	${CMAKE_CURRENT_LIST_DIR}/CamelServiceLevel.c
	${CMAKE_CURRENT_LIST_DIR}/CamelServiceUsed.c
	${CMAKE_CURRENT_LIST_DIR}/CauseForTerm.c
	${CMAKE_CURRENT_LIST_DIR}/CellId.c
	${CMAKE_CURRENT_LIST_DIR}/Charge.c
	${CMAKE_CURRENT_LIST_DIR}/ChargeableSubscriber.c
	${CMAKE_CURRENT_LIST_DIR}/ChargeableUnits.c
	${CMAKE_CURRENT_LIST_DIR}/ChargeDetail.c
	${CMAKE_CURRENT_LIST_DIR}/ChargeDetailList.c
	${CMAKE_CURRENT_LIST_DIR}/ChargeDetailTimeStamp.c
	${CMAKE_CURRENT_LIST_DIR}/ChargedItem.c
	${CMAKE_CURRENT_LIST_DIR}/ChargedPartyEquipment.c
	${CMAKE_CURRENT_LIST_DIR}/ChargedPartyHomeIdentification.c
	${CMAKE_CURRENT_LIST_DIR}/ChargedPartyHomeIdList.c
	${CMAKE_CURRENT_LIST_DIR}/ChargedPartyIdentification.c
	${CMAKE_CURRENT_LIST_DIR}/ChargedPartyIdentifier.c
	${CMAKE_CURRENT_LIST_DIR}/ChargedPartyIdList.c
	${CMAKE_CURRENT_LIST_DIR}/ChargedPartyIdType.c
	${CMAKE_CURRENT_LIST_DIR}/ChargedPartyInformation.c
	${CMAKE_CURRENT_LIST_DIR}/ChargedPartyLocation.c
	${CMAKE_CURRENT_LIST_DIR}/ChargedPartyLocationList.c
	${CMAKE_CURRENT_LIST_DIR}/ChargedPartyStatus.c
	${CMAKE_CURRENT_LIST_DIR}/ChargedUnits.c
	${CMAKE_CURRENT_LIST_DIR}/ChargeInformation.c
	${CMAKE_CURRENT_LIST_DIR}/ChargeInformationList.c
	${CMAKE_CURRENT_LIST_DIR}/ChargeRefundIndicator.c
	${CMAKE_CURRENT_LIST_DIR}/ChargeType.c
	${CMAKE_CURRENT_LIST_DIR}/ChargingId.c
	${CMAKE_CURRENT_LIST_DIR}/ChargingPoint.c
	${CMAKE_CURRENT_LIST_DIR}/ChargingTimeStamp.c
	${CMAKE_CURRENT_LIST_DIR}/ClirIndicator.c
	${CMAKE_CURRENT_LIST_DIR}/Code.c
	${CMAKE_CURRENT_LIST_DIR}/Commission.c
	${CMAKE_CURRENT_LIST_DIR}/CompletionTimeStamp.c
	${CMAKE_CURRENT_LIST_DIR}/constraints.c
	${CMAKE_CURRENT_LIST_DIR}/constr_CHOICE.c
	${CMAKE_CURRENT_LIST_DIR}/constr_CHOICE_aper.c
	${CMAKE_CURRENT_LIST_DIR}/constr_CHOICE_ber.c
	${CMAKE_CURRENT_LIST_DIR}/constr_CHOICE_jer.c
	${CMAKE_CURRENT_LIST_DIR}/constr_CHOICE_oer.c
	${CMAKE_CURRENT_LIST_DIR}/constr_CHOICE_print.c
	${CMAKE_CURRENT_LIST_DIR}/constr_CHOICE_rfill.c
	${CMAKE_CURRENT_LIST_DIR}/constr_CHOICE_uper.c
	${CMAKE_CURRENT_LIST_DIR}/constr_CHOICE_xer.c
	${CMAKE_CURRENT_LIST_DIR}/constr_SEQUENCE.c
	${CMAKE_CURRENT_LIST_DIR}/constr_SEQUENCE_aper.c
	${CMAKE_CURRENT_LIST_DIR}/constr_SEQUENCE_ber.c
	${CMAKE_CURRENT_LIST_DIR}/constr_SEQUENCE_jer.c
	${CMAKE_CURRENT_LIST_DIR}/constr_SEQUENCE_oer.c
	${CMAKE_CURRENT_LIST_DIR}/constr_SEQUENCE_OF.c
	${CMAKE_CURRENT_LIST_DIR}/constr_SEQUENCE_OF_aper.c
	${CMAKE_CURRENT_LIST_DIR}/constr_SEQUENCE_OF_ber.c
	${CMAKE_CURRENT_LIST_DIR}/constr_SEQUENCE_OF_jer.c
	${CMAKE_CURRENT_LIST_DIR}/constr_SEQUENCE_OF_uper.c
	${CMAKE_CURRENT_LIST_DIR}/constr_SEQUENCE_OF_xer.c
	${CMAKE_CURRENT_LIST_DIR}/constr_SEQUENCE_print.c
	${CMAKE_CURRENT_LIST_DIR}/constr_SEQUENCE_rfill.c
	${CMAKE_CURRENT_LIST_DIR}/constr_SEQUENCE_uper.c
	${CMAKE_CURRENT_LIST_DIR}/constr_SEQUENCE_xer.c
	${CMAKE_CURRENT_LIST_DIR}/constr_SET_OF.c
	${CMAKE_CURRENT_LIST_DIR}/constr_SET_OF_aper.c
	${CMAKE_CURRENT_LIST_DIR}/constr_SET_OF_ber.c
	${CMAKE_CURRENT_LIST_DIR}/constr_SET_OF_jer.c
	${CMAKE_CURRENT_LIST_DIR}/constr_SET_OF_oer.c
	${CMAKE_CURRENT_LIST_DIR}/constr_SET_OF_print.c
	${CMAKE_CURRENT_LIST_DIR}/constr_SET_OF_rfill.c
	${CMAKE_CURRENT_LIST_DIR}/constr_SET_OF_uper.c
	${CMAKE_CURRENT_LIST_DIR}/constr_SET_OF_xer.c
	${CMAKE_CURRENT_LIST_DIR}/constr_TYPE.c
	${CMAKE_CURRENT_LIST_DIR}/ContentChargingPoint.c
	${CMAKE_CURRENT_LIST_DIR}/ContentProvider.c
	${CMAKE_CURRENT_LIST_DIR}/ContentProviderIdentifier.c
	${CMAKE_CURRENT_LIST_DIR}/ContentProviderIdList.c
	${CMAKE_CURRENT_LIST_DIR}/ContentProviderIdType.c
	${CMAKE_CURRENT_LIST_DIR}/ContentProviderName.c
	${CMAKE_CURRENT_LIST_DIR}/ContentServiceUsed.c
	${CMAKE_CURRENT_LIST_DIR}/ContentServiceUsedList.c
	${CMAKE_CURRENT_LIST_DIR}/ContentTransaction.c
	${CMAKE_CURRENT_LIST_DIR}/ContentTransactionBasicInfo.c
	${CMAKE_CURRENT_LIST_DIR}/ContentTransactionCode.c
	${CMAKE_CURRENT_LIST_DIR}/ContentTransactionType.c
	${CMAKE_CURRENT_LIST_DIR}/CseInformation.c
	${CMAKE_CURRENT_LIST_DIR}/Currency.c
	${CMAKE_CURRENT_LIST_DIR}/CurrencyConversion.c
	${CMAKE_CURRENT_LIST_DIR}/CurrencyConversionList.c
	${CMAKE_CURRENT_LIST_DIR}/CustomerIdentifier.c
	${CMAKE_CURRENT_LIST_DIR}/CustomerIdType.c
	${CMAKE_CURRENT_LIST_DIR}/DataInterChange.c
	${CMAKE_CURRENT_LIST_DIR}/DataVolume.c
	${CMAKE_CURRENT_LIST_DIR}/DataVolumeIncoming.c
	${CMAKE_CURRENT_LIST_DIR}/DataVolumeOutgoing.c
	${CMAKE_CURRENT_LIST_DIR}/DateTime.c
	${CMAKE_CURRENT_LIST_DIR}/DateTimeLong.c
	${CMAKE_CURRENT_LIST_DIR}/DefaultCallHandlingIndicator.c
	${CMAKE_CURRENT_LIST_DIR}/DepositTimeStamp.c
	${CMAKE_CURRENT_LIST_DIR}/der_encoder.c
	${CMAKE_CURRENT_LIST_DIR}/Destination.c
	${CMAKE_CURRENT_LIST_DIR}/DestinationNetwork.c
	${CMAKE_CURRENT_LIST_DIR}/DialledDigits.c
	${CMAKE_CURRENT_LIST_DIR}/Discount.c
	${CMAKE_CURRENT_LIST_DIR}/DiscountableAmount.c
	${CMAKE_CURRENT_LIST_DIR}/DiscountApplied.c
	${CMAKE_CURRENT_LIST_DIR}/DiscountCode.c
	${CMAKE_CURRENT_LIST_DIR}/DiscountInformation.c
	${CMAKE_CURRENT_LIST_DIR}/Discounting.c
	${CMAKE_CURRENT_LIST_DIR}/DiscountingList.c
	${CMAKE_CURRENT_LIST_DIR}/DiscountRate.c
	${CMAKE_CURRENT_LIST_DIR}/DiscountValue.c
	${CMAKE_CURRENT_LIST_DIR}/DistanceChargeBandCode.c
	${CMAKE_CURRENT_LIST_DIR}/EarliestCallTimeStamp.c
	${CMAKE_CURRENT_LIST_DIR}/EquipmentId.c
	${CMAKE_CURRENT_LIST_DIR}/EquipmentIdType.c
	${CMAKE_CURRENT_LIST_DIR}/Esn.c
	${CMAKE_CURRENT_LIST_DIR}/ExchangeRate.c
	${CMAKE_CURRENT_LIST_DIR}/ExchangeRateCode.c
	${CMAKE_CURRENT_LIST_DIR}/EXTERNAL.c
	${CMAKE_CURRENT_LIST_DIR}/FileAvailableTimeStamp.c
	${CMAKE_CURRENT_LIST_DIR}/FileCreationTimeStamp.c
	${CMAKE_CURRENT_LIST_DIR}/FileSequenceNumber.c
	${CMAKE_CURRENT_LIST_DIR}/FileTypeIndicator.c
	${CMAKE_CURRENT_LIST_DIR}/FixedDiscountValue.c
	${CMAKE_CURRENT_LIST_DIR}/Fnur.c
	${CMAKE_CURRENT_LIST_DIR}/GeographicalLocation.c
	${CMAKE_CURRENT_LIST_DIR}/GprsBasicCallInformation.c
	${CMAKE_CURRENT_LIST_DIR}/GprsCall.c
	${CMAKE_CURRENT_LIST_DIR}/GprsChargeableSubscriber.c
	${CMAKE_CURRENT_LIST_DIR}/GprsDestination.c
	${CMAKE_CURRENT_LIST_DIR}/GprsLocationInformation.c
	${CMAKE_CURRENT_LIST_DIR}/GprsNetworkLocation.c
	${CMAKE_CURRENT_LIST_DIR}/GprsServiceUsed.c
	${CMAKE_CURRENT_LIST_DIR}/GraphicString.c
	${CMAKE_CURRENT_LIST_DIR}/GsmChargeableSubscriber.c
	${CMAKE_CURRENT_LIST_DIR}/GuaranteedBitRate.c
	${CMAKE_CURRENT_LIST_DIR}/HexString.c
	${CMAKE_CURRENT_LIST_DIR}/HomeBid.c
	${CMAKE_CURRENT_LIST_DIR}/HomeIdentifier.c
	${CMAKE_CURRENT_LIST_DIR}/HomeIdType.c
	${CMAKE_CURRENT_LIST_DIR}/HomeLocationDescription.c
	${CMAKE_CURRENT_LIST_DIR}/HomeLocationInformation.c
	${CMAKE_CURRENT_LIST_DIR}/HorizontalAccuracyDelivered.c
	${CMAKE_CURRENT_LIST_DIR}/HorizontalAccuracyRequested.c
	${CMAKE_CURRENT_LIST_DIR}/HSCSDIndicator.c
	${CMAKE_CURRENT_LIST_DIR}/Imei.c
	${CMAKE_CURRENT_LIST_DIR}/ImeiOrEsn.c
	${CMAKE_CURRENT_LIST_DIR}/Imsi.c
	${CMAKE_CURRENT_LIST_DIR}/IMSSignallingContext.c
	${CMAKE_CURRENT_LIST_DIR}/INTEGER.c
	${CMAKE_CURRENT_LIST_DIR}/INTEGER_aper.c
	${CMAKE_CURRENT_LIST_DIR}/INTEGER_ber.c
	${CMAKE_CURRENT_LIST_DIR}/INTEGER_jer.c
	${CMAKE_CURRENT_LIST_DIR}/INTEGER_oer.c
	${CMAKE_CURRENT_LIST_DIR}/INTEGER_print.c
	${CMAKE_CURRENT_LIST_DIR}/INTEGER_rfill.c
	${CMAKE_CURRENT_LIST_DIR}/INTEGER_uper.c
	${CMAKE_CURRENT_LIST_DIR}/INTEGER_xer.c
	${CMAKE_CURRENT_LIST_DIR}/InternetServiceProvider.c
	${CMAKE_CURRENT_LIST_DIR}/InternetServiceProviderIdList.c
	${CMAKE_CURRENT_LIST_DIR}/IspIdentifier.c
	${CMAKE_CURRENT_LIST_DIR}/IspIdType.c
	${CMAKE_CURRENT_LIST_DIR}/ISPList.c
	${CMAKE_CURRENT_LIST_DIR}/jer_encoder.c
	${CMAKE_CURRENT_LIST_DIR}/LatestCallTimeStamp.c
	${CMAKE_CURRENT_LIST_DIR}/LCSQosDelivered.c
	${CMAKE_CURRENT_LIST_DIR}/LCSQosRequested.c
	${CMAKE_CURRENT_LIST_DIR}/LCSRequestTimestamp.c
	${CMAKE_CURRENT_LIST_DIR}/LCSSPIdentification.c
	${CMAKE_CURRENT_LIST_DIR}/LCSSPIdentificationList.c
	${CMAKE_CURRENT_LIST_DIR}/LCSSPInformation.c
	${CMAKE_CURRENT_LIST_DIR}/LCSTransactionStatus.c
	${CMAKE_CURRENT_LIST_DIR}/LocalCurrency.c
	${CMAKE_CURRENT_LIST_DIR}/LocalTimeStamp.c
	${CMAKE_CURRENT_LIST_DIR}/LocationArea.c
	${CMAKE_CURRENT_LIST_DIR}/LocationDescription.c
	${CMAKE_CURRENT_LIST_DIR}/LocationIdentifier.c
	${CMAKE_CURRENT_LIST_DIR}/LocationIdType.c
	${CMAKE_CURRENT_LIST_DIR}/LocationInformation.c
	${CMAKE_CURRENT_LIST_DIR}/LocationService.c
	${CMAKE_CURRENT_LIST_DIR}/LocationServiceUsage.c
	${CMAKE_CURRENT_LIST_DIR}/MaximumBitRate.c
	${CMAKE_CURRENT_LIST_DIR}/Mdn.c
	${CMAKE_CURRENT_LIST_DIR}/MessageDescription.c
	${CMAKE_CURRENT_LIST_DIR}/MessageDescriptionCode.c
	${CMAKE_CURRENT_LIST_DIR}/MessageDescriptionInfoList.c
	${CMAKE_CURRENT_LIST_DIR}/MessageDescriptionInformation.c
	${CMAKE_CURRENT_LIST_DIR}/MessageStatus.c
	${CMAKE_CURRENT_LIST_DIR}/MessageType.c
	${CMAKE_CURRENT_LIST_DIR}/Min.c
	${CMAKE_CURRENT_LIST_DIR}/MinChargeableSubscriber.c
	${CMAKE_CURRENT_LIST_DIR}/MoBasicCallInformation.c
	${CMAKE_CURRENT_LIST_DIR}/MobileOriginatedCall.c
	${CMAKE_CURRENT_LIST_DIR}/MobileTerminatedCall.c
	${CMAKE_CURRENT_LIST_DIR}/Msisdn.c
	${CMAKE_CURRENT_LIST_DIR}/MtBasicCallInformation.c
	${CMAKE_CURRENT_LIST_DIR}/NativeInteger.c
	${CMAKE_CURRENT_LIST_DIR}/NativeInteger_aper.c
	${CMAKE_CURRENT_LIST_DIR}/NativeInteger_ber.c
	${CMAKE_CURRENT_LIST_DIR}/NativeInteger_jer.c
	${CMAKE_CURRENT_LIST_DIR}/NativeInteger_oer.c
	${CMAKE_CURRENT_LIST_DIR}/NativeInteger_print.c
	${CMAKE_CURRENT_LIST_DIR}/NativeInteger_rfill.c
	${CMAKE_CURRENT_LIST_DIR}/NativeInteger_uper.c
	${CMAKE_CURRENT_LIST_DIR}/NativeInteger_xer.c
	${CMAKE_CURRENT_LIST_DIR}/Network.c
	${CMAKE_CURRENT_LIST_DIR}/NetworkAccessIdentifier.c
	${CMAKE_CURRENT_LIST_DIR}/NetworkId.c
	${CMAKE_CURRENT_LIST_DIR}/NetworkIdentifier.c
	${CMAKE_CURRENT_LIST_DIR}/NetworkIdType.c
	${CMAKE_CURRENT_LIST_DIR}/NetworkInfo.c
	${CMAKE_CURRENT_LIST_DIR}/NetworkInitPDPContext.c
	${CMAKE_CURRENT_LIST_DIR}/NetworkList.c
	${CMAKE_CURRENT_LIST_DIR}/NetworkLocation.c
	${CMAKE_CURRENT_LIST_DIR}/NonChargedNumber.c
	${CMAKE_CURRENT_LIST_DIR}/Notification.c
	${CMAKE_CURRENT_LIST_DIR}/NumberOfDecimalPlaces.c
	${CMAKE_CURRENT_LIST_DIR}/NumberString.c
	${CMAKE_CURRENT_LIST_DIR}/ObjectDescriptor.c
	${CMAKE_CURRENT_LIST_DIR}/ObjectType.c
	${CMAKE_CURRENT_LIST_DIR}/OBJECT_IDENTIFIER.c
	${CMAKE_CURRENT_LIST_DIR}/OBJECT_IDENTIFIER_jer.c
	${CMAKE_CURRENT_LIST_DIR}/OBJECT_IDENTIFIER_print.c
	${CMAKE_CURRENT_LIST_DIR}/OBJECT_IDENTIFIER_rfill.c
	${CMAKE_CURRENT_LIST_DIR}/OBJECT_IDENTIFIER_xer.c
	${CMAKE_CURRENT_LIST_DIR}/OCTET_STRING.c
	${CMAKE_CURRENT_LIST_DIR}/OCTET_STRING_aper.c
	${CMAKE_CURRENT_LIST_DIR}/OCTET_STRING_ber.c
	${CMAKE_CURRENT_LIST_DIR}/OCTET_STRING_jer.c
	${CMAKE_CURRENT_LIST_DIR}/OCTET_STRING_oer.c
	${CMAKE_CURRENT_LIST_DIR}/OCTET_STRING_print.c
	${CMAKE_CURRENT_LIST_DIR}/OCTET_STRING_rfill.c
	${CMAKE_CURRENT_LIST_DIR}/OCTET_STRING_uper.c
	${CMAKE_CURRENT_LIST_DIR}/OCTET_STRING_xer.c
	${CMAKE_CURRENT_LIST_DIR}/oer_decoder.c
	${CMAKE_CURRENT_LIST_DIR}/oer_encoder.c
	${CMAKE_CURRENT_LIST_DIR}/oer_support.c
	${CMAKE_CURRENT_LIST_DIR}/OPEN_TYPE.c
	${CMAKE_CURRENT_LIST_DIR}/OPEN_TYPE_aper.c
	${CMAKE_CURRENT_LIST_DIR}/OPEN_TYPE_ber.c
	${CMAKE_CURRENT_LIST_DIR}/OPEN_TYPE_oer.c
	${CMAKE_CURRENT_LIST_DIR}/OPEN_TYPE_uper.c
	${CMAKE_CURRENT_LIST_DIR}/OPEN_TYPE_xer.c
	${CMAKE_CURRENT_LIST_DIR}/OperatorSpecInfoList.c
	${CMAKE_CURRENT_LIST_DIR}/OperatorSpecInformation.c
	${CMAKE_CURRENT_LIST_DIR}/OrderPlacedTimeStamp.c
	${CMAKE_CURRENT_LIST_DIR}/OriginatingNetwork.c
	${CMAKE_CURRENT_LIST_DIR}/PacketDataProtocolAddress.c
	${CMAKE_CURRENT_LIST_DIR}/PaidIndicator.c
	${CMAKE_CURRENT_LIST_DIR}/PartialTypeIndicator.c
	${CMAKE_CURRENT_LIST_DIR}/PaymentMethod.c
	${CMAKE_CURRENT_LIST_DIR}/PdpAddress.c
	${CMAKE_CURRENT_LIST_DIR}/PDPContextStartTimestamp.c
	${CMAKE_CURRENT_LIST_DIR}/pdu_collection.c
	${CMAKE_CURRENT_LIST_DIR}/PercentageRate.c
	${CMAKE_CURRENT_LIST_DIR}/per_decoder.c
	${CMAKE_CURRENT_LIST_DIR}/per_encoder.c
	${CMAKE_CURRENT_LIST_DIR}/per_opentype.c
	${CMAKE_CURRENT_LIST_DIR}/per_support.c
	${CMAKE_CURRENT_LIST_DIR}/PlmnId.c
	${CMAKE_CURRENT_LIST_DIR}/PositioningMethod.c
	${CMAKE_CURRENT_LIST_DIR}/PriorityCode.c
	${CMAKE_CURRENT_LIST_DIR}/RapFileSequenceNumber.c
	${CMAKE_CURRENT_LIST_DIR}/RecEntityCode.c
	${CMAKE_CURRENT_LIST_DIR}/RecEntityCodeList.c
	${CMAKE_CURRENT_LIST_DIR}/RecEntityId.c
	${CMAKE_CURRENT_LIST_DIR}/RecEntityInfoList.c
	${CMAKE_CURRENT_LIST_DIR}/RecEntityInformation.c
	${CMAKE_CURRENT_LIST_DIR}/RecEntityType.c
	${CMAKE_CURRENT_LIST_DIR}/Recipient.c
	${CMAKE_CURRENT_LIST_DIR}/ReleaseVersionNumber.c
	${CMAKE_CURRENT_LIST_DIR}/RequestedDeliveryTimeStamp.c
	${CMAKE_CURRENT_LIST_DIR}/ResponseTime.c
	${CMAKE_CURRENT_LIST_DIR}/ResponseTimeCategory.c
	${CMAKE_CURRENT_LIST_DIR}/ScuBasicInformation.c
	${CMAKE_CURRENT_LIST_DIR}/ScuChargeableSubscriber.c
	${CMAKE_CURRENT_LIST_DIR}/ScuChargeType.c
	${CMAKE_CURRENT_LIST_DIR}/ScuTimeStamps.c
	${CMAKE_CURRENT_LIST_DIR}/Sender.c
	${CMAKE_CURRENT_LIST_DIR}/ServiceCentreUsage.c
	${CMAKE_CURRENT_LIST_DIR}/ServingBid.c
	${CMAKE_CURRENT_LIST_DIR}/ServingLocationDescription.c
	${CMAKE_CURRENT_LIST_DIR}/ServingNetwork.c
	${CMAKE_CURRENT_LIST_DIR}/ServingPartiesInformation.c
	${CMAKE_CURRENT_LIST_DIR}/SimChargeableSubscriber.c
	${CMAKE_CURRENT_LIST_DIR}/SimToolkitIndicator.c
	${CMAKE_CURRENT_LIST_DIR}/SMSDestinationNumber.c
	${CMAKE_CURRENT_LIST_DIR}/SMSOriginator.c
	${CMAKE_CURRENT_LIST_DIR}/SpecificationVersionNumber.c
	${CMAKE_CURRENT_LIST_DIR}/SsParameters.c
	${CMAKE_CURRENT_LIST_DIR}/SupplServiceActionCode.c
	${CMAKE_CURRENT_LIST_DIR}/SupplServiceCode.c
	${CMAKE_CURRENT_LIST_DIR}/SupplServiceEvent.c
	${CMAKE_CURRENT_LIST_DIR}/SupplServiceUsed.c
	${CMAKE_CURRENT_LIST_DIR}/TapCurrency.c
	${CMAKE_CURRENT_LIST_DIR}/TapDecimalPlaces.c
	${CMAKE_CURRENT_LIST_DIR}/TaxableAmount.c
	${CMAKE_CURRENT_LIST_DIR}/Taxation.c
	${CMAKE_CURRENT_LIST_DIR}/TaxationList.c
	${CMAKE_CURRENT_LIST_DIR}/TaxCode.c
	${CMAKE_CURRENT_LIST_DIR}/TaxIndicator.c
	${CMAKE_CURRENT_LIST_DIR}/TaxInformation.c
	${CMAKE_CURRENT_LIST_DIR}/TaxInformationList.c
	${CMAKE_CURRENT_LIST_DIR}/TaxRate.c
	${CMAKE_CURRENT_LIST_DIR}/TaxType.c
	${CMAKE_CURRENT_LIST_DIR}/TaxValue.c
	${CMAKE_CURRENT_LIST_DIR}/TeleServiceCode.c
	${CMAKE_CURRENT_LIST_DIR}/ThirdPartyInformation.c
	${CMAKE_CURRENT_LIST_DIR}/ThirdPartyNumber.c
	${CMAKE_CURRENT_LIST_DIR}/ThreeGcamelDestination.c
	${CMAKE_CURRENT_LIST_DIR}/TotalAdvisedCharge.c
	${CMAKE_CURRENT_LIST_DIR}/TotalAdvisedChargeRefund.c
	${CMAKE_CURRENT_LIST_DIR}/TotalAdvisedChargeValue.c
	${CMAKE_CURRENT_LIST_DIR}/TotalAdvisedChargeValueList.c
	${CMAKE_CURRENT_LIST_DIR}/TotalCallEventDuration.c
	${CMAKE_CURRENT_LIST_DIR}/TotalCharge.c
	${CMAKE_CURRENT_LIST_DIR}/TotalChargeRefund.c
	${CMAKE_CURRENT_LIST_DIR}/TotalCommission.c
	${CMAKE_CURRENT_LIST_DIR}/TotalCommissionRefund.c
	${CMAKE_CURRENT_LIST_DIR}/TotalDataVolume.c
	${CMAKE_CURRENT_LIST_DIR}/TotalDiscountRefund.c
	${CMAKE_CURRENT_LIST_DIR}/TotalDiscountValue.c
	${CMAKE_CURRENT_LIST_DIR}/TotalTaxRefund.c
	${CMAKE_CURRENT_LIST_DIR}/TotalTaxValue.c
	${CMAKE_CURRENT_LIST_DIR}/TotalTransactionDuration.c
	${CMAKE_CURRENT_LIST_DIR}/TrackedCustomerEquipment.c
	${CMAKE_CURRENT_LIST_DIR}/TrackedCustomerHomeId.c
	${CMAKE_CURRENT_LIST_DIR}/TrackedCustomerHomeIdList.c
	${CMAKE_CURRENT_LIST_DIR}/TrackedCustomerIdentification.c
	${CMAKE_CURRENT_LIST_DIR}/TrackedCustomerIdList.c
	${CMAKE_CURRENT_LIST_DIR}/TrackedCustomerInformation.c
	${CMAKE_CURRENT_LIST_DIR}/TrackedCustomerLocation.c
	${CMAKE_CURRENT_LIST_DIR}/TrackedCustomerLocList.c
	${CMAKE_CURRENT_LIST_DIR}/TrackingCustomerEquipment.c
	${CMAKE_CURRENT_LIST_DIR}/TrackingCustomerHomeId.c
	${CMAKE_CURRENT_LIST_DIR}/TrackingCustomerHomeIdList.c
	${CMAKE_CURRENT_LIST_DIR}/TrackingCustomerIdentification.c
	${CMAKE_CURRENT_LIST_DIR}/TrackingCustomerIdList.c
	${CMAKE_CURRENT_LIST_DIR}/TrackingCustomerInformation.c
	${CMAKE_CURRENT_LIST_DIR}/TrackingCustomerLocation.c
	${CMAKE_CURRENT_LIST_DIR}/TrackingCustomerLocList.c
	${CMAKE_CURRENT_LIST_DIR}/TrackingFrequency.c
	${CMAKE_CURRENT_LIST_DIR}/TrackingPeriod.c
	${CMAKE_CURRENT_LIST_DIR}/TransactionAuthCode.c
	${CMAKE_CURRENT_LIST_DIR}/TransactionDescriptionSupp.c
	${CMAKE_CURRENT_LIST_DIR}/TransactionDetailDescription.c
	${CMAKE_CURRENT_LIST_DIR}/TransactionIdentifier.c
	${CMAKE_CURRENT_LIST_DIR}/TransactionShortDescription.c
	${CMAKE_CURRENT_LIST_DIR}/TransactionStatus.c
	${CMAKE_CURRENT_LIST_DIR}/TransferBatch.c
	${CMAKE_CURRENT_LIST_DIR}/TransferCutOffTimeStamp.c
	${CMAKE_CURRENT_LIST_DIR}/TransparencyIndicator.c
	${CMAKE_CURRENT_LIST_DIR}/uper_decoder.c
	${CMAKE_CURRENT_LIST_DIR}/uper_encoder.c
	${CMAKE_CURRENT_LIST_DIR}/uper_opentype.c
	${CMAKE_CURRENT_LIST_DIR}/uper_support.c
	${CMAKE_CURRENT_LIST_DIR}/UserProtocolIndicator.c
	${CMAKE_CURRENT_LIST_DIR}/UtcTimeOffset.c
	${CMAKE_CURRENT_LIST_DIR}/UtcTimeOffsetCode.c
	${CMAKE_CURRENT_LIST_DIR}/UtcTimeOffsetInfo.c
	${CMAKE_CURRENT_LIST_DIR}/UtcTimeOffsetInfoList.c
	${CMAKE_CURRENT_LIST_DIR}/VerticalAccuracyDelivered.c
	${CMAKE_CURRENT_LIST_DIR}/VerticalAccuracyRequested.c
	${CMAKE_CURRENT_LIST_DIR}/xer_decoder.c
	${CMAKE_CURRENT_LIST_DIR}/xer_encoder.c
	${CMAKE_CURRENT_LIST_DIR}/xer_support.c
)

SET(TAP0311_MODULE_HEADERS
	${CMAKE_CURRENT_LIST_DIR}/AbsoluteAmount.h
	${CMAKE_CURRENT_LIST_DIR}/AccessPointNameNI.h
	${CMAKE_CURRENT_LIST_DIR}/AccessPointNameOI.h
	${CMAKE_CURRENT_LIST_DIR}/AccountingInfo.h
	${CMAKE_CURRENT_LIST_DIR}/ActualDeliveryTimeStamp.h
	${CMAKE_CURRENT_LIST_DIR}/AddressStringDigits.h
	${CMAKE_CURRENT_LIST_DIR}/AdvisedCharge.h
	${CMAKE_CURRENT_LIST_DIR}/AdvisedChargeCurrency.h
	${CMAKE_CURRENT_LIST_DIR}/AdvisedChargeInformation.h
	${CMAKE_CURRENT_LIST_DIR}/AgeOfLocation.h
	${CMAKE_CURRENT_LIST_DIR}/ANY.h
	${CMAKE_CURRENT_LIST_DIR}/aper_decoder.h
	${CMAKE_CURRENT_LIST_DIR}/aper_encoder.h
	${CMAKE_CURRENT_LIST_DIR}/aper_opentype.h
	${CMAKE_CURRENT_LIST_DIR}/aper_support.h
	${CMAKE_CURRENT_LIST_DIR}/AsciiString.h
	${CMAKE_CURRENT_LIST_DIR}/asn_application.h
	${CMAKE_CURRENT_LIST_DIR}/asn_bit_data.h
	${CMAKE_CURRENT_LIST_DIR}/asn_codecs.h
	${CMAKE_CURRENT_LIST_DIR}/asn_codecs_prim.h
	${CMAKE_CURRENT_LIST_DIR}/asn_config.h
	${CMAKE_CURRENT_LIST_DIR}/asn_internal.h
	${CMAKE_CURRENT_LIST_DIR}/asn_ioc.h
	${CMAKE_CURRENT_LIST_DIR}/asn_random_fill.h
	${CMAKE_CURRENT_LIST_DIR}/asn_SEQUENCE_OF.h
	${CMAKE_CURRENT_LIST_DIR}/asn_SET_OF.h
	${CMAKE_CURRENT_LIST_DIR}/asn_system.h
	${CMAKE_CURRENT_LIST_DIR}/AuditControlInfo.h
	${CMAKE_CURRENT_LIST_DIR}/BasicService.h
	${CMAKE_CURRENT_LIST_DIR}/BasicServiceCode.h
	${CMAKE_CURRENT_LIST_DIR}/BasicServiceCodeList.h
	${CMAKE_CURRENT_LIST_DIR}/BasicServiceUsed.h
	${CMAKE_CURRENT_LIST_DIR}/BasicServiceUsedList.h
	${CMAKE_CURRENT_LIST_DIR}/BatchControlInfo.h
	${CMAKE_CURRENT_LIST_DIR}/BCDString.h
	${CMAKE_CURRENT_LIST_DIR}/BearerServiceCode.h
	${CMAKE_CURRENT_LIST_DIR}/ber_decoder.h
	${CMAKE_CURRENT_LIST_DIR}/ber_tlv_length.h
	${CMAKE_CURRENT_LIST_DIR}/ber_tlv_tag.h
	${CMAKE_CURRENT_LIST_DIR}/Bid.h
	${CMAKE_CURRENT_LIST_DIR}/BIT_STRING.h
	${CMAKE_CURRENT_LIST_DIR}/CalledNumber.h
	${CMAKE_CURRENT_LIST_DIR}/CalledPlace.h
	${CMAKE_CURRENT_LIST_DIR}/CalledRegion.h
	${CMAKE_CURRENT_LIST_DIR}/CallEventDetail.h
	${CMAKE_CURRENT_LIST_DIR}/CallEventDetailList.h
	${CMAKE_CURRENT_LIST_DIR}/CallEventDetailsCount.h
	${CMAKE_CURRENT_LIST_DIR}/CallEventStartTimeStamp.h
	${CMAKE_CURRENT_LIST_DIR}/CallingNumber.h
	${CMAKE_CURRENT_LIST_DIR}/CallOriginator.h
	${CMAKE_CURRENT_LIST_DIR}/CallReference.h
	${CMAKE_CURRENT_LIST_DIR}/CallTypeGroup.h
	${CMAKE_CURRENT_LIST_DIR}/CallTypeLevel1.h
	${CMAKE_CURRENT_LIST_DIR}/CallTypeLevel2.h
	${CMAKE_CURRENT_LIST_DIR}/CallTypeLevel3.h
	${CMAKE_CURRENT_LIST_DIR}/CamelDestinationNumber.h
	${CMAKE_CURRENT_LIST_DIR}/CamelInvocationFee.h
	${CMAKE_CURRENT_LIST_DIR}/CamelServiceKey.h
	${CMAKE_CURRENT_LIST_DIR}/CamelServiceLevel.h
	${CMAKE_CURRENT_LIST_DIR}/CamelServiceUsed.h
	${CMAKE_CURRENT_LIST_DIR}/CauseForTerm.h
	${CMAKE_CURRENT_LIST_DIR}/CellId.h
	${CMAKE_CURRENT_LIST_DIR}/Charge.h
	${CMAKE_CURRENT_LIST_DIR}/ChargeableSubscriber.h
	${CMAKE_CURRENT_LIST_DIR}/ChargeableUnits.h
	${CMAKE_CURRENT_LIST_DIR}/ChargeDetail.h
	${CMAKE_CURRENT_LIST_DIR}/ChargeDetailList.h
	${CMAKE_CURRENT_LIST_DIR}/ChargeDetailTimeStamp.h
	${CMAKE_CURRENT_LIST_DIR}/ChargedItem.h
	${CMAKE_CURRENT_LIST_DIR}/ChargedPartyEquipment.h
	${CMAKE_CURRENT_LIST_DIR}/ChargedPartyHomeIdentification.h
	${CMAKE_CURRENT_LIST_DIR}/ChargedPartyHomeIdList.h
	${CMAKE_CURRENT_LIST_DIR}/ChargedPartyIdentification.h
	${CMAKE_CURRENT_LIST_DIR}/ChargedPartyIdentifier.h
	${CMAKE_CURRENT_LIST_DIR}/ChargedPartyIdList.h
	${CMAKE_CURRENT_LIST_DIR}/ChargedPartyIdType.h
	${CMAKE_CURRENT_LIST_DIR}/ChargedPartyInformation.h
	${CMAKE_CURRENT_LIST_DIR}/ChargedPartyLocation.h
	${CMAKE_CURRENT_LIST_DIR}/ChargedPartyLocationList.h
	${CMAKE_CURRENT_LIST_DIR}/ChargedPartyStatus.h
	${CMAKE_CURRENT_LIST_DIR}/ChargedUnits.h
	${CMAKE_CURRENT_LIST_DIR}/ChargeInformation.h
	${CMAKE_CURRENT_LIST_DIR}/ChargeInformationList.h
	${CMAKE_CURRENT_LIST_DIR}/ChargeRefundIndicator.h
	${CMAKE_CURRENT_LIST_DIR}/ChargeType.h
	${CMAKE_CURRENT_LIST_DIR}/ChargingId.h
	${CMAKE_CURRENT_LIST_DIR}/ChargingPoint.h
	${CMAKE_CURRENT_LIST_DIR}/ChargingTimeStamp.h
	${CMAKE_CURRENT_LIST_DIR}/ClirIndicator.h
	${CMAKE_CURRENT_LIST_DIR}/Code.h
	${CMAKE_CURRENT_LIST_DIR}/Commission.h
	${CMAKE_CURRENT_LIST_DIR}/CompletionTimeStamp.h
	${CMAKE_CURRENT_LIST_DIR}/constraints.h
	${CMAKE_CURRENT_LIST_DIR}/constr_CHOICE.h
	${CMAKE_CURRENT_LIST_DIR}/constr_SEQUENCE.h
	${CMAKE_CURRENT_LIST_DIR}/constr_SEQUENCE_OF.h
	${CMAKE_CURRENT_LIST_DIR}/constr_SET_OF.h
	${CMAKE_CURRENT_LIST_DIR}/constr_TYPE.h
	${CMAKE_CURRENT_LIST_DIR}/ContentChargingPoint.h
	${CMAKE_CURRENT_LIST_DIR}/ContentProvider.h
	${CMAKE_CURRENT_LIST_DIR}/ContentProviderIdentifier.h
	${CMAKE_CURRENT_LIST_DIR}/ContentProviderIdList.h
	${CMAKE_CURRENT_LIST_DIR}/ContentProviderIdType.h
	${CMAKE_CURRENT_LIST_DIR}/ContentProviderName.h
	${CMAKE_CURRENT_LIST_DIR}/ContentServiceUsed.h
	${CMAKE_CURRENT_LIST_DIR}/ContentServiceUsedList.h
	${CMAKE_CURRENT_LIST_DIR}/ContentTransaction.h
	${CMAKE_CURRENT_LIST_DIR}/ContentTransactionBasicInfo.h
	${CMAKE_CURRENT_LIST_DIR}/ContentTransactionCode.h
	${CMAKE_CURRENT_LIST_DIR}/ContentTransactionType.h
	${CMAKE_CURRENT_LIST_DIR}/CseInformation.h
	${CMAKE_CURRENT_LIST_DIR}/Currency.h
	${CMAKE_CURRENT_LIST_DIR}/CurrencyConversion.h
	${CMAKE_CURRENT_LIST_DIR}/CurrencyConversionList.h
	${CMAKE_CURRENT_LIST_DIR}/CustomerIdentifier.h
	${CMAKE_CURRENT_LIST_DIR}/CustomerIdType.h
	${CMAKE_CURRENT_LIST_DIR}/DataInterChange.h
	${CMAKE_CURRENT_LIST_DIR}/DataVolume.h
	${CMAKE_CURRENT_LIST_DIR}/DataVolumeIncoming.h
	${CMAKE_CURRENT_LIST_DIR}/DataVolumeOutgoing.h
	${CMAKE_CURRENT_LIST_DIR}/DateTime.h
	${CMAKE_CURRENT_LIST_DIR}/DateTimeLong.h
	${CMAKE_CURRENT_LIST_DIR}/DefaultCallHandlingIndicator.h
	${CMAKE_CURRENT_LIST_DIR}/DepositTimeStamp.h
	${CMAKE_CURRENT_LIST_DIR}/der_encoder.h
	${CMAKE_CURRENT_LIST_DIR}/Destination.h
	${CMAKE_CURRENT_LIST_DIR}/DestinationNetwork.h
	${CMAKE_CURRENT_LIST_DIR}/DialledDigits.h
	${CMAKE_CURRENT_LIST_DIR}/Discount.h
	${CMAKE_CURRENT_LIST_DIR}/DiscountableAmount.h
	${CMAKE_CURRENT_LIST_DIR}/DiscountApplied.h
	${CMAKE_CURRENT_LIST_DIR}/DiscountCode.h
	${CMAKE_CURRENT_LIST_DIR}/DiscountInformation.h
	${CMAKE_CURRENT_LIST_DIR}/Discounting.h
	${CMAKE_CURRENT_LIST_DIR}/DiscountingList.h
	${CMAKE_CURRENT_LIST_DIR}/DiscountRate.h
	${CMAKE_CURRENT_LIST_DIR}/DiscountValue.h
	${CMAKE_CURRENT_LIST_DIR}/DistanceChargeBandCode.h
	${CMAKE_CURRENT_LIST_DIR}/EarliestCallTimeStamp.h
	${CMAKE_CURRENT_LIST_DIR}/EquipmentId.h
	${CMAKE_CURRENT_LIST_DIR}/EquipmentIdType.h
	${CMAKE_CURRENT_LIST_DIR}/Esn.h
	${CMAKE_CURRENT_LIST_DIR}/ExchangeRate.h
	${CMAKE_CURRENT_LIST_DIR}/ExchangeRateCode.h
	${CMAKE_CURRENT_LIST_DIR}/EXTERNAL.h
	${CMAKE_CURRENT_LIST_DIR}/FileAvailableTimeStamp.h
	${CMAKE_CURRENT_LIST_DIR}/FileCreationTimeStamp.h
	${CMAKE_CURRENT_LIST_DIR}/FileSequenceNumber.h
	${CMAKE_CURRENT_LIST_DIR}/FileTypeIndicator.h
	${CMAKE_CURRENT_LIST_DIR}/FixedDiscountValue.h
	${CMAKE_CURRENT_LIST_DIR}/Fnur.h
	${CMAKE_CURRENT_LIST_DIR}/GeographicalLocation.h
	${CMAKE_CURRENT_LIST_DIR}/GprsBasicCallInformation.h
	${CMAKE_CURRENT_LIST_DIR}/GprsCall.h
	${CMAKE_CURRENT_LIST_DIR}/GprsChargeableSubscriber.h
	${CMAKE_CURRENT_LIST_DIR}/GprsDestination.h
	${CMAKE_CURRENT_LIST_DIR}/GprsLocationInformation.h
	${CMAKE_CURRENT_LIST_DIR}/GprsNetworkLocation.h
	${CMAKE_CURRENT_LIST_DIR}/GprsServiceUsed.h
	${CMAKE_CURRENT_LIST_DIR}/GraphicString.h
	${CMAKE_CURRENT_LIST_DIR}/GsmChargeableSubscriber.h
	${CMAKE_CURRENT_LIST_DIR}/GuaranteedBitRate.h
	${CMAKE_CURRENT_LIST_DIR}/HexString.h
	${CMAKE_CURRENT_LIST_DIR}/HomeBid.h
	${CMAKE_CURRENT_LIST_DIR}/HomeIdentifier.h
	${CMAKE_CURRENT_LIST_DIR}/HomeIdType.h
	${CMAKE_CURRENT_LIST_DIR}/HomeLocationDescription.h
	${CMAKE_CURRENT_LIST_DIR}/HomeLocationInformation.h
	${CMAKE_CURRENT_LIST_DIR}/HorizontalAccuracyDelivered.h
	${CMAKE_CURRENT_LIST_DIR}/HorizontalAccuracyRequested.h
	${CMAKE_CURRENT_LIST_DIR}/HSCSDIndicator.h
	${CMAKE_CURRENT_LIST_DIR}/Imei.h
	${CMAKE_CURRENT_LIST_DIR}/ImeiOrEsn.h
	${CMAKE_CURRENT_LIST_DIR}/Imsi.h
	${CMAKE_CURRENT_LIST_DIR}/IMSSignallingContext.h
	${CMAKE_CURRENT_LIST_DIR}/INTEGER.h
	${CMAKE_CURRENT_LIST_DIR}/InternetServiceProvider.h
	${CMAKE_CURRENT_LIST_DIR}/InternetServiceProviderIdList.h
	${CMAKE_CURRENT_LIST_DIR}/IspIdentifier.h
	${CMAKE_CURRENT_LIST_DIR}/IspIdType.h
	${CMAKE_CURRENT_LIST_DIR}/ISPList.h
	${CMAKE_CURRENT_LIST_DIR}/jer_encoder.h
	${CMAKE_CURRENT_LIST_DIR}/LatestCallTimeStamp.h
	${CMAKE_CURRENT_LIST_DIR}/LCSQosDelivered.h
	${CMAKE_CURRENT_LIST_DIR}/LCSQosRequested.h
	${CMAKE_CURRENT_LIST_DIR}/LCSRequestTimestamp.h
	${CMAKE_CURRENT_LIST_DIR}/LCSSPIdentification.h
	${CMAKE_CURRENT_LIST_DIR}/LCSSPIdentificationList.h
	${CMAKE_CURRENT_LIST_DIR}/LCSSPInformation.h
	${CMAKE_CURRENT_LIST_DIR}/LCSTransactionStatus.h
	${CMAKE_CURRENT_LIST_DIR}/LocalCurrency.h
	${CMAKE_CURRENT_LIST_DIR}/LocalTimeStamp.h
	${CMAKE_CURRENT_LIST_DIR}/LocationArea.h
	${CMAKE_CURRENT_LIST_DIR}/LocationDescription.h
	${CMAKE_CURRENT_LIST_DIR}/LocationIdentifier.h
	${CMAKE_CURRENT_LIST_DIR}/LocationIdType.h
	${CMAKE_CURRENT_LIST_DIR}/LocationInformation.h
	${CMAKE_CURRENT_LIST_DIR}/LocationService.h
	${CMAKE_CURRENT_LIST_DIR}/LocationServiceUsage.h
	${CMAKE_CURRENT_LIST_DIR}/MaximumBitRate.h
	${CMAKE_CURRENT_LIST_DIR}/Mdn.h
	${CMAKE_CURRENT_LIST_DIR}/MessageDescription.h
	${CMAKE_CURRENT_LIST_DIR}/MessageDescriptionCode.h
	${CMAKE_CURRENT_LIST_DIR}/MessageDescriptionInfoList.h
	${CMAKE_CURRENT_LIST_DIR}/MessageDescriptionInformation.h
	${CMAKE_CURRENT_LIST_DIR}/MessageStatus.h
	${CMAKE_CURRENT_LIST_DIR}/MessageType.h
	${CMAKE_CURRENT_LIST_DIR}/Min.h
	${CMAKE_CURRENT_LIST_DIR}/MinChargeableSubscriber.h
	${CMAKE_CURRENT_LIST_DIR}/MoBasicCallInformation.h
	${CMAKE_CURRENT_LIST_DIR}/MobileOriginatedCall.h
	${CMAKE_CURRENT_LIST_DIR}/MobileTerminatedCall.h
	${CMAKE_CURRENT_LIST_DIR}/Msisdn.h
	${CMAKE_CURRENT_LIST_DIR}/MtBasicCallInformation.h
	${CMAKE_CURRENT_LIST_DIR}/NativeInteger.h
	${CMAKE_CURRENT_LIST_DIR}/Network.h
	${CMAKE_CURRENT_LIST_DIR}/NetworkAccessIdentifier.h
	${CMAKE_CURRENT_LIST_DIR}/NetworkId.h
	${CMAKE_CURRENT_LIST_DIR}/NetworkIdentifier.h
	${CMAKE_CURRENT_LIST_DIR}/NetworkIdType.h
	${CMAKE_CURRENT_LIST_DIR}/NetworkInfo.h
	${CMAKE_CURRENT_LIST_DIR}/NetworkInitPDPContext.h
	${CMAKE_CURRENT_LIST_DIR}/NetworkList.h
	${CMAKE_CURRENT_LIST_DIR}/NetworkLocation.h
	${CMAKE_CURRENT_LIST_DIR}/NonChargedNumber.h
	${CMAKE_CURRENT_LIST_DIR}/Notification.h
	${CMAKE_CURRENT_LIST_DIR}/NumberOfDecimalPlaces.h
	${CMAKE_CURRENT_LIST_DIR}/NumberString.h
	${CMAKE_CURRENT_LIST_DIR}/ObjectDescriptor.h
	${CMAKE_CURRENT_LIST_DIR}/ObjectType.h
	${CMAKE_CURRENT_LIST_DIR}/OBJECT_IDENTIFIER.h
	${CMAKE_CURRENT_LIST_DIR}/OCTET_STRING.h
	${CMAKE_CURRENT_LIST_DIR}/oer_decoder.h
	${CMAKE_CURRENT_LIST_DIR}/oer_encoder.h
	${CMAKE_CURRENT_LIST_DIR}/oer_support.h
	${CMAKE_CURRENT_LIST_DIR}/OPEN_TYPE.h
	${CMAKE_CURRENT_LIST_DIR}/OperatorSpecInfoList.h
	${CMAKE_CURRENT_LIST_DIR}/OperatorSpecInformation.h
	${CMAKE_CURRENT_LIST_DIR}/OrderPlacedTimeStamp.h
	${CMAKE_CURRENT_LIST_DIR}/OriginatingNetwork.h
	${CMAKE_CURRENT_LIST_DIR}/PacketDataProtocolAddress.h
	${CMAKE_CURRENT_LIST_DIR}/PaidIndicator.h
	${CMAKE_CURRENT_LIST_DIR}/PartialTypeIndicator.h
	${CMAKE_CURRENT_LIST_DIR}/PaymentMethod.h
	${CMAKE_CURRENT_LIST_DIR}/PdpAddress.h
	${CMAKE_CURRENT_LIST_DIR}/PDPContextStartTimestamp.h
	${CMAKE_CURRENT_LIST_DIR}/PercentageRate.h
	${CMAKE_CURRENT_LIST_DIR}/per_decoder.h
	${CMAKE_CURRENT_LIST_DIR}/per_encoder.h
	${CMAKE_CURRENT_LIST_DIR}/per_opentype.h
	${CMAKE_CURRENT_LIST_DIR}/per_support.h
	${CMAKE_CURRENT_LIST_DIR}/PlmnId.h
	${CMAKE_CURRENT_LIST_DIR}/PositioningMethod.h
	${CMAKE_CURRENT_LIST_DIR}/PriorityCode.h
	${CMAKE_CURRENT_LIST_DIR}/RapFileSequenceNumber.h
	${CMAKE_CURRENT_LIST_DIR}/RecEntityCode.h
	${CMAKE_CURRENT_LIST_DIR}/RecEntityCodeList.h
	${CMAKE_CURRENT_LIST_DIR}/RecEntityId.h
	${CMAKE_CURRENT_LIST_DIR}/RecEntityInfoList.h
	${CMAKE_CURRENT_LIST_DIR}/RecEntityInformation.h
	${CMAKE_CURRENT_LIST_DIR}/RecEntityType.h
	${CMAKE_CURRENT_LIST_DIR}/Recipient.h
	${CMAKE_CURRENT_LIST_DIR}/ReleaseVersionNumber.h
	${CMAKE_CURRENT_LIST_DIR}/RequestedDeliveryTimeStamp.h
	${CMAKE_CURRENT_LIST_DIR}/ResponseTime.h
	${CMAKE_CURRENT_LIST_DIR}/ResponseTimeCategory.h
	${CMAKE_CURRENT_LIST_DIR}/ScuBasicInformation.h
	${CMAKE_CURRENT_LIST_DIR}/ScuChargeableSubscriber.h
	${CMAKE_CURRENT_LIST_DIR}/ScuChargeType.h
	${CMAKE_CURRENT_LIST_DIR}/ScuTimeStamps.h
	${CMAKE_CURRENT_LIST_DIR}/Sender.h
	${CMAKE_CURRENT_LIST_DIR}/ServiceCentreUsage.h
	${CMAKE_CURRENT_LIST_DIR}/ServingBid.h
	${CMAKE_CURRENT_LIST_DIR}/ServingLocationDescription.h
	${CMAKE_CURRENT_LIST_DIR}/ServingNetwork.h
	${CMAKE_CURRENT_LIST_DIR}/ServingPartiesInformation.h
	${CMAKE_CURRENT_LIST_DIR}/SimChargeableSubscriber.h
	${CMAKE_CURRENT_LIST_DIR}/SimToolkitIndicator.h
	${CMAKE_CURRENT_LIST_DIR}/SMSDestinationNumber.h
	${CMAKE_CURRENT_LIST_DIR}/SMSOriginator.h
	${CMAKE_CURRENT_LIST_DIR}/SpecificationVersionNumber.h
	${CMAKE_CURRENT_LIST_DIR}/SsParameters.h
	${CMAKE_CURRENT_LIST_DIR}/SupplServiceActionCode.h
	${CMAKE_CURRENT_LIST_DIR}/SupplServiceCode.h
	${CMAKE_CURRENT_LIST_DIR}/SupplServiceEvent.h
	${CMAKE_CURRENT_LIST_DIR}/SupplServiceUsed.h
	${CMAKE_CURRENT_LIST_DIR}/TapCurrency.h
	${CMAKE_CURRENT_LIST_DIR}/TapDecimalPlaces.h
	${CMAKE_CURRENT_LIST_DIR}/TaxableAmount.h
	${CMAKE_CURRENT_LIST_DIR}/Taxation.h
	${CMAKE_CURRENT_LIST_DIR}/TaxationList.h
	${CMAKE_CURRENT_LIST_DIR}/TaxCode.h
	${CMAKE_CURRENT_LIST_DIR}/TaxIndicator.h
	${CMAKE_CURRENT_LIST_DIR}/TaxInformation.h
	${CMAKE_CURRENT_LIST_DIR}/TaxInformationList.h
	${CMAKE_CURRENT_LIST_DIR}/TaxRate.h
	${CMAKE_CURRENT_LIST_DIR}/TaxType.h
	${CMAKE_CURRENT_LIST_DIR}/TaxValue.h
	${CMAKE_CURRENT_LIST_DIR}/TeleServiceCode.h
	${CMAKE_CURRENT_LIST_DIR}/ThirdPartyInformation.h
	${CMAKE_CURRENT_LIST_DIR}/ThirdPartyNumber.h
	${CMAKE_CURRENT_LIST_DIR}/ThreeGcamelDestination.h
	${CMAKE_CURRENT_LIST_DIR}/TotalAdvisedCharge.h
	${CMAKE_CURRENT_LIST_DIR}/TotalAdvisedChargeRefund.h
	${CMAKE_CURRENT_LIST_DIR}/TotalAdvisedChargeValue.h
	${CMAKE_CURRENT_LIST_DIR}/TotalAdvisedChargeValueList.h
	${CMAKE_CURRENT_LIST_DIR}/TotalCallEventDuration.h
	${CMAKE_CURRENT_LIST_DIR}/TotalCharge.h
	${CMAKE_CURRENT_LIST_DIR}/TotalChargeRefund.h
	${CMAKE_CURRENT_LIST_DIR}/TotalCommission.h
	${CMAKE_CURRENT_LIST_DIR}/TotalCommissionRefund.h
	${CMAKE_CURRENT_LIST_DIR}/TotalDataVolume.h
	${CMAKE_CURRENT_LIST_DIR}/TotalDiscountRefund.h
	${CMAKE_CURRENT_LIST_DIR}/TotalDiscountValue.h
	${CMAKE_CURRENT_LIST_DIR}/TotalTaxRefund.h
	${CMAKE_CURRENT_LIST_DIR}/TotalTaxValue.h
	${CMAKE_CURRENT_LIST_DIR}/TotalTransactionDuration.h
	${CMAKE_CURRENT_LIST_DIR}/TrackedCustomerEquipment.h
	${CMAKE_CURRENT_LIST_DIR}/TrackedCustomerHomeId.h
	${CMAKE_CURRENT_LIST_DIR}/TrackedCustomerHomeIdList.h
	${CMAKE_CURRENT_LIST_DIR}/TrackedCustomerIdentification.h
	${CMAKE_CURRENT_LIST_DIR}/TrackedCustomerIdList.h
	${CMAKE_CURRENT_LIST_DIR}/TrackedCustomerInformation.h
	${CMAKE_CURRENT_LIST_DIR}/TrackedCustomerLocation.h
	${CMAKE_CURRENT_LIST_DIR}/TrackedCustomerLocList.h
	${CMAKE_CURRENT_LIST_DIR}/TrackingCustomerEquipment.h
	${CMAKE_CURRENT_LIST_DIR}/TrackingCustomerHomeId.h
	${CMAKE_CURRENT_LIST_DIR}/TrackingCustomerHomeIdList.h
	${CMAKE_CURRENT_LIST_DIR}/TrackingCustomerIdentification.h
	${CMAKE_CURRENT_LIST_DIR}/TrackingCustomerIdList.h
	${CMAKE_CURRENT_LIST_DIR}/TrackingCustomerInformation.h
	${CMAKE_CURRENT_LIST_DIR}/TrackingCustomerLocation.h
	${CMAKE_CURRENT_LIST_DIR}/TrackingCustomerLocList.h
	${CMAKE_CURRENT_LIST_DIR}/TrackingFrequency.h
	${CMAKE_CURRENT_LIST_DIR}/TrackingPeriod.h
	${CMAKE_CURRENT_LIST_DIR}/TransactionAuthCode.h
	${CMAKE_CURRENT_LIST_DIR}/TransactionDescriptionSupp.h
	${CMAKE_CURRENT_LIST_DIR}/TransactionDetailDescription.h
	${CMAKE_CURRENT_LIST_DIR}/TransactionIdentifier.h
	${CMAKE_CURRENT_LIST_DIR}/TransactionShortDescription.h
	${CMAKE_CURRENT_LIST_DIR}/TransactionStatus.h
	${CMAKE_CURRENT_LIST_DIR}/TransferBatch.h
	${CMAKE_CURRENT_LIST_DIR}/TransferCutOffTimeStamp.h
	${CMAKE_CURRENT_LIST_DIR}/TransparencyIndicator.h
	${CMAKE_CURRENT_LIST_DIR}/uper_decoder.h
	${CMAKE_CURRENT_LIST_DIR}/uper_encoder.h
	${CMAKE_CURRENT_LIST_DIR}/uper_opentype.h
	${CMAKE_CURRENT_LIST_DIR}/uper_support.h
	${CMAKE_CURRENT_LIST_DIR}/UserProtocolIndicator.h
	${CMAKE_CURRENT_LIST_DIR}/UtcTimeOffset.h
	${CMAKE_CURRENT_LIST_DIR}/UtcTimeOffsetCode.h
	${CMAKE_CURRENT_LIST_DIR}/UtcTimeOffsetInfo.h
	${CMAKE_CURRENT_LIST_DIR}/UtcTimeOffsetInfoList.h
	${CMAKE_CURRENT_LIST_DIR}/VerticalAccuracyDelivered.h
	${CMAKE_CURRENT_LIST_DIR}/VerticalAccuracyRequested.h
	${CMAKE_CURRENT_LIST_DIR}/xer_decoder.h
	${CMAKE_CURRENT_LIST_DIR}/xer_encoder.h
	${CMAKE_CURRENT_LIST_DIR}/xer_support.h
)

SET(libtap0311codec_la_SOURCES TAP0311_MODULE_SOURCES TAP0311_MODULE_HEADERS)