/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0311"
 * 	found in "TAP0311.asn1"
 * 	`asn1c -D E:/repos/tap3reader/src/pdus/tap/3_11`
 */

#include "AdvisedChargeInformation.h"

asn_TYPE_member_t asn_MBR_AdvisedChargeInformation_1[] = {
	{ ATF_POINTER, 5, offsetof(struct AdvisedChargeInformation, paidIndicator),
		(ASN_TAG_CLASS_APPLICATION | (346 << 2)),
		0,
		&asn_DEF_PaidIndicator,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"paidIndicator"
		},
	{ ATF_POINTER, 4, offsetof(struct AdvisedChargeInformation, paymentMethod),
		(ASN_TAG_CLASS_APPLICATION | (347 << 2)),
		0,
		&asn_DEF_PaymentMethod,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"paymentMethod"
		},
	{ ATF_POINTER, 3, offsetof(struct AdvisedChargeInformation, advisedChargeCurrency),
		(ASN_TAG_CLASS_APPLICATION | (348 << 2)),
		0,
		&asn_DEF_AdvisedChargeCurrency,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"advisedChargeCurrency"
		},
	{ ATF_POINTER, 2, offsetof(struct AdvisedChargeInformation, advisedCharge),
		(ASN_TAG_CLASS_APPLICATION | (349 << 2)),
		0,
		&asn_DEF_AdvisedCharge,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"advisedCharge"
		},
	{ ATF_POINTER, 1, offsetof(struct AdvisedChargeInformation, commission),
		(ASN_TAG_CLASS_APPLICATION | (350 << 2)),
		0,
		&asn_DEF_Commission,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"commission"
		},
};
static const int asn_MAP_AdvisedChargeInformation_oms_1[] = { 0, 1, 2, 3, 4 };
static const ber_tlv_tag_t asn_DEF_AdvisedChargeInformation_tags_1[] = {
	(ASN_TAG_CLASS_APPLICATION | (351 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_AdvisedChargeInformation_tag2el_1[] = {
    { (ASN_TAG_CLASS_APPLICATION | (346 << 2)), 0, 0, 0 }, /* paidIndicator */
    { (ASN_TAG_CLASS_APPLICATION | (347 << 2)), 1, 0, 0 }, /* paymentMethod */
    { (ASN_TAG_CLASS_APPLICATION | (348 << 2)), 2, 0, 0 }, /* advisedChargeCurrency */
    { (ASN_TAG_CLASS_APPLICATION | (349 << 2)), 3, 0, 0 }, /* advisedCharge */
    { (ASN_TAG_CLASS_APPLICATION | (350 << 2)), 4, 0, 0 } /* commission */
};
asn_SEQUENCE_specifics_t asn_SPC_AdvisedChargeInformation_specs_1 = {
	sizeof(struct AdvisedChargeInformation),
	offsetof(struct AdvisedChargeInformation, _asn_ctx),
	asn_MAP_AdvisedChargeInformation_tag2el_1,
	5,	/* Count of tags in the map */
	asn_MAP_AdvisedChargeInformation_oms_1,	/* Optional members */
	5, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_AdvisedChargeInformation = {
	"AdvisedChargeInformation",
	"AdvisedChargeInformation",
	&asn_OP_SEQUENCE,
	asn_DEF_AdvisedChargeInformation_tags_1,
	sizeof(asn_DEF_AdvisedChargeInformation_tags_1)
		/sizeof(asn_DEF_AdvisedChargeInformation_tags_1[0]) - 1, /* 1 */
	asn_DEF_AdvisedChargeInformation_tags_1,	/* Same as above */
	sizeof(asn_DEF_AdvisedChargeInformation_tags_1)
		/sizeof(asn_DEF_AdvisedChargeInformation_tags_1[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_AdvisedChargeInformation_1,
	5,	/* Elements count */
	&asn_SPC_AdvisedChargeInformation_specs_1	/* Additional specs */
};

