/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0311"
 * 	found in "TAP0311.asn1"
 * 	`asn1c -D E:/repos/tap3reader/src/pdus/tap/3_11`
 */

#include "ChargeInformation.h"

asn_TYPE_member_t asn_MBR_ChargeInformation_1[] = {
	{ ATF_POINTER, 6, offsetof(struct ChargeInformation, chargedItem),
		(ASN_TAG_CLASS_APPLICATION | (66 << 2)),
		0,
		&asn_DEF_ChargedItem,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"chargedItem"
		},
	{ ATF_POINTER, 5, offsetof(struct ChargeInformation, exchangeRateCode),
		(ASN_TAG_CLASS_APPLICATION | (105 << 2)),
		0,
		&asn_DEF_ExchangeRateCode,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"exchangeRateCode"
		},
	{ ATF_POINTER, 4, offsetof(struct ChargeInformation, callTypeGroup),
		(ASN_TAG_CLASS_APPLICATION | (258 << 2)),
		0,
		&asn_DEF_CallTypeGroup,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"callTypeGroup"
		},
	{ ATF_POINTER, 3, offsetof(struct ChargeInformation, chargeDetailList),
		(ASN_TAG_CLASS_APPLICATION | (64 << 2)),
		0,
		&asn_DEF_ChargeDetailList,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"chargeDetailList"
		},
	{ ATF_POINTER, 2, offsetof(struct ChargeInformation, taxInformation),
		(ASN_TAG_CLASS_APPLICATION | (214 << 2)),
		0,
		&asn_DEF_TaxInformationList,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"taxInformation"
		},
	{ ATF_POINTER, 1, offsetof(struct ChargeInformation, discountInformation),
		(ASN_TAG_CLASS_APPLICATION | (96 << 2)),
		0,
		&asn_DEF_DiscountInformation,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"discountInformation"
		},
};
static const int asn_MAP_ChargeInformation_oms_1[] = { 0, 1, 2, 3, 4, 5 };
static const ber_tlv_tag_t asn_DEF_ChargeInformation_tags_1[] = {
	(ASN_TAG_CLASS_APPLICATION | (69 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ChargeInformation_tag2el_1[] = {
    { (ASN_TAG_CLASS_APPLICATION | (64 << 2)), 3, 0, 0 }, /* chargeDetailList */
    { (ASN_TAG_CLASS_APPLICATION | (66 << 2)), 0, 0, 0 }, /* chargedItem */
    { (ASN_TAG_CLASS_APPLICATION | (96 << 2)), 5, 0, 0 }, /* discountInformation */
    { (ASN_TAG_CLASS_APPLICATION | (105 << 2)), 1, 0, 0 }, /* exchangeRateCode */
    { (ASN_TAG_CLASS_APPLICATION | (214 << 2)), 4, 0, 0 }, /* taxInformation */
    { (ASN_TAG_CLASS_APPLICATION | (258 << 2)), 2, 0, 0 } /* callTypeGroup */
};
asn_SEQUENCE_specifics_t asn_SPC_ChargeInformation_specs_1 = {
	sizeof(struct ChargeInformation),
	offsetof(struct ChargeInformation, _asn_ctx),
	asn_MAP_ChargeInformation_tag2el_1,
	6,	/* Count of tags in the map */
	asn_MAP_ChargeInformation_oms_1,	/* Optional members */
	6, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_ChargeInformation = {
	"ChargeInformation",
	"ChargeInformation",
	&asn_OP_SEQUENCE,
	asn_DEF_ChargeInformation_tags_1,
	sizeof(asn_DEF_ChargeInformation_tags_1)
		/sizeof(asn_DEF_ChargeInformation_tags_1[0]) - 1, /* 1 */
	asn_DEF_ChargeInformation_tags_1,	/* Same as above */
	sizeof(asn_DEF_ChargeInformation_tags_1)
		/sizeof(asn_DEF_ChargeInformation_tags_1[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_ChargeInformation_1,
	6,	/* Elements count */
	&asn_SPC_ChargeInformation_specs_1	/* Additional specs */
};

