/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0311"
 * 	found in "TAP0311.asn1"
 * 	`asn1c -D E:/repos/tap3reader/src/pdus/tap/3_11`
 */

#include "ChargeDetail.h"

asn_TYPE_member_t asn_MBR_ChargeDetail_1[] = {
	{ ATF_POINTER, 5, offsetof(struct ChargeDetail, chargeType),
		(ASN_TAG_CLASS_APPLICATION | (71 << 2)),
		0,
		&asn_DEF_ChargeType,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"chargeType"
		},
	{ ATF_POINTER, 4, offsetof(struct ChargeDetail, charge),
		(ASN_TAG_CLASS_APPLICATION | (62 << 2)),
		0,
		&asn_DEF_Charge,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"charge"
		},
	{ ATF_POINTER, 3, offsetof(struct ChargeDetail, chargeableUnits),
		(ASN_TAG_CLASS_APPLICATION | (65 << 2)),
		0,
		&asn_DEF_ChargeableUnits,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"chargeableUnits"
		},
	{ ATF_POINTER, 2, offsetof(struct ChargeDetail, chargedUnits),
		(ASN_TAG_CLASS_APPLICATION | (68 << 2)),
		0,
		&asn_DEF_ChargedUnits,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"chargedUnits"
		},
	{ ATF_POINTER, 1, offsetof(struct ChargeDetail, chargeDetailTimeStamp),
		(ASN_TAG_CLASS_APPLICATION | (410 << 2)),
		0,
		&asn_DEF_ChargeDetailTimeStamp,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"chargeDetailTimeStamp"
		},
};
static const int asn_MAP_ChargeDetail_oms_1[] = { 0, 1, 2, 3, 4 };
static const ber_tlv_tag_t asn_DEF_ChargeDetail_tags_1[] = {
	(ASN_TAG_CLASS_APPLICATION | (63 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ChargeDetail_tag2el_1[] = {
    { (ASN_TAG_CLASS_APPLICATION | (62 << 2)), 1, 0, 0 }, /* charge */
    { (ASN_TAG_CLASS_APPLICATION | (65 << 2)), 2, 0, 0 }, /* chargeableUnits */
    { (ASN_TAG_CLASS_APPLICATION | (68 << 2)), 3, 0, 0 }, /* chargedUnits */
    { (ASN_TAG_CLASS_APPLICATION | (71 << 2)), 0, 0, 0 }, /* chargeType */
    { (ASN_TAG_CLASS_APPLICATION | (410 << 2)), 4, 0, 0 } /* chargeDetailTimeStamp */
};
asn_SEQUENCE_specifics_t asn_SPC_ChargeDetail_specs_1 = {
	sizeof(struct ChargeDetail),
	offsetof(struct ChargeDetail, _asn_ctx),
	asn_MAP_ChargeDetail_tag2el_1,
	5,	/* Count of tags in the map */
	asn_MAP_ChargeDetail_oms_1,	/* Optional members */
	5, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_ChargeDetail = {
	"ChargeDetail",
	"ChargeDetail",
	&asn_OP_SEQUENCE,
	asn_DEF_ChargeDetail_tags_1,
	sizeof(asn_DEF_ChargeDetail_tags_1)
		/sizeof(asn_DEF_ChargeDetail_tags_1[0]) - 1, /* 1 */
	asn_DEF_ChargeDetail_tags_1,	/* Same as above */
	sizeof(asn_DEF_ChargeDetail_tags_1)
		/sizeof(asn_DEF_ChargeDetail_tags_1[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_ChargeDetail_1,
	5,	/* Elements count */
	&asn_SPC_ChargeDetail_specs_1	/* Additional specs */
};

