/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0311"
 * 	found in "TAP0311.asn1"
 * 	`asn1c -D E:/repos/tap3reader/src/pdus/tap/3_11`
 */

#include "Destination.h"

asn_TYPE_member_t asn_MBR_Destination_1[] = {
	{ ATF_POINTER, 5, offsetof(struct Destination, calledNumber),
		(ASN_TAG_CLASS_APPLICATION | (407 << 2)),
		0,
		&asn_DEF_CalledNumber,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"calledNumber"
		},
	{ ATF_POINTER, 4, offsetof(struct Destination, dialledDigits),
		(ASN_TAG_CLASS_APPLICATION | (279 << 2)),
		0,
		&asn_DEF_DialledDigits,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"dialledDigits"
		},
	{ ATF_POINTER, 3, offsetof(struct Destination, calledPlace),
		(ASN_TAG_CLASS_APPLICATION | (42 << 2)),
		0,
		&asn_DEF_CalledPlace,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"calledPlace"
		},
	{ ATF_POINTER, 2, offsetof(struct Destination, calledRegion),
		(ASN_TAG_CLASS_APPLICATION | (46 << 2)),
		0,
		&asn_DEF_CalledRegion,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"calledRegion"
		},
	{ ATF_POINTER, 1, offsetof(struct Destination, sMSDestinationNumber),
		(ASN_TAG_CLASS_APPLICATION | (419 << 2)),
		0,
		&asn_DEF_SMSDestinationNumber,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"sMSDestinationNumber"
		},
};
static const int asn_MAP_Destination_oms_1[] = { 0, 1, 2, 3, 4 };
static const ber_tlv_tag_t asn_DEF_Destination_tags_1[] = {
	(ASN_TAG_CLASS_APPLICATION | (89 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Destination_tag2el_1[] = {
    { (ASN_TAG_CLASS_APPLICATION | (42 << 2)), 2, 0, 0 }, /* calledPlace */
    { (ASN_TAG_CLASS_APPLICATION | (46 << 2)), 3, 0, 0 }, /* calledRegion */
    { (ASN_TAG_CLASS_APPLICATION | (279 << 2)), 1, 0, 0 }, /* dialledDigits */
    { (ASN_TAG_CLASS_APPLICATION | (407 << 2)), 0, 0, 0 }, /* calledNumber */
    { (ASN_TAG_CLASS_APPLICATION | (419 << 2)), 4, 0, 0 } /* sMSDestinationNumber */
};
asn_SEQUENCE_specifics_t asn_SPC_Destination_specs_1 = {
	sizeof(struct Destination),
	offsetof(struct Destination, _asn_ctx),
	asn_MAP_Destination_tag2el_1,
	5,	/* Count of tags in the map */
	asn_MAP_Destination_oms_1,	/* Optional members */
	5, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_Destination = {
	"Destination",
	"Destination",
	&asn_OP_SEQUENCE,
	asn_DEF_Destination_tags_1,
	sizeof(asn_DEF_Destination_tags_1)
		/sizeof(asn_DEF_Destination_tags_1[0]) - 1, /* 1 */
	asn_DEF_Destination_tags_1,	/* Same as above */
	sizeof(asn_DEF_Destination_tags_1)
		/sizeof(asn_DEF_Destination_tags_1[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_Destination_1,
	5,	/* Elements count */
	&asn_SPC_Destination_specs_1	/* Additional specs */
};

