/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0311"
 * 	found in "TAP0311.asn1"
 * 	`asn1c -D E:/repos/tap3reader/src/pdus/tap/3_11`
 */

#ifndef	_ThreeGcamelDestination_H_
#define	_ThreeGcamelDestination_H_


#include <asn_application.h>

/* Including external dependencies */
#include "CamelDestinationNumber.h"
#include "GprsDestination.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ThreeGcamelDestination_PR {
	ThreeGcamelDestination_PR_NOTHING,	/* No components present */
	ThreeGcamelDestination_PR_camelDestinationNumber,
	ThreeGcamelDestination_PR_gprsDestination
} ThreeGcamelDestination_PR;

/* ThreeGcamelDestination */
typedef struct ThreeGcamelDestination {
	ThreeGcamelDestination_PR present;
	union ThreeGcamelDestination_u {
		CamelDestinationNumber_t	 camelDestinationNumber;
		GprsDestination_t	 gprsDestination;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ThreeGcamelDestination_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ThreeGcamelDestination;
extern asn_CHOICE_specifics_t asn_SPC_ThreeGcamelDestination_specs_1;
extern asn_TYPE_member_t asn_MBR_ThreeGcamelDestination_1[2];
extern asn_per_constraints_t asn_PER_type_ThreeGcamelDestination_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _ThreeGcamelDestination_H_ */
#include <asn_internal.h>
