/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0311"
 * 	found in "TAP0311.asn1"
 * 	`asn1c -D E:/repos/tap3reader/src/pdus/tap/3_11`
 */

#ifndef	_TrackingFrequency_H_
#define	_TrackingFrequency_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* TrackingFrequency */
typedef long	 TrackingFrequency_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TrackingFrequency;
asn_struct_free_f TrackingFrequency_free;
asn_struct_print_f TrackingFrequency_print;
asn_constr_check_f TrackingFrequency_constraint;
ber_type_decoder_f TrackingFrequency_decode_ber;
der_type_encoder_f TrackingFrequency_encode_der;
xer_type_decoder_f TrackingFrequency_decode_xer;
xer_type_encoder_f TrackingFrequency_encode_xer;
jer_type_encoder_f TrackingFrequency_encode_jer;
oer_type_decoder_f TrackingFrequency_decode_oer;
oer_type_encoder_f TrackingFrequency_encode_oer;
per_type_decoder_f TrackingFrequency_decode_uper;
per_type_encoder_f TrackingFrequency_encode_uper;
per_type_decoder_f TrackingFrequency_decode_aper;
per_type_encoder_f TrackingFrequency_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _TrackingFrequency_H_ */
#include <asn_internal.h>
