/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP0312.asn1"
 * 	`asn1c -D E:/repos/tap3reader/src/pdus/tap/3_12`
 */

#ifndef	_BasicServiceUsed_H_
#define	_BasicServiceUsed_H_


#include <asn_application.h>

/* Including external dependencies */
#include "HSCSDIndicator.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct BasicService;
struct ChargingTimeStamp;
struct ChargeInformationList;

/* BasicServiceUsed */
typedef struct BasicServiceUsed {
	struct BasicService	*basicService;	/* OPTIONAL */
	struct ChargingTimeStamp	*chargingTimeStamp;	/* OPTIONAL */
	struct ChargeInformationList	*chargeInformationList;	/* OPTIONAL */
	HSCSDIndicator_t	*hSCSDIndicator;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} BasicServiceUsed_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_BasicServiceUsed;
extern asn_SEQUENCE_specifics_t asn_SPC_BasicServiceUsed_specs_1;
extern asn_TYPE_member_t asn_MBR_BasicServiceUsed_1[4];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "BasicService.h"
#include "ChargingTimeStamp.h"
#include "ChargeInformationList.h"

#endif	/* _BasicServiceUsed_H_ */
#include <asn_internal.h>
