/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP0312.asn1"
 * 	`asn1c -D E:/repos/tap3reader/src/pdus/tap/3_12`
 */

#include "ChargedParty.h"

asn_TYPE_member_t asn_MBR_ChargedParty_1[] = {
	{ ATF_POINTER, 6, offsetof(struct ChargedParty, imsi),
		(ASN_TAG_CLASS_APPLICATION | (129 << 2)),
		0,
		&asn_DEF_Imsi,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"imsi"
		},
	{ ATF_POINTER, 5, offsetof(struct ChargedParty, msisdn),
		(ASN_TAG_CLASS_APPLICATION | (152 << 2)),
		0,
		&asn_DEF_Msisdn,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"msisdn"
		},
	{ ATF_POINTER, 4, offsetof(struct ChargedParty, publicUserId),
		(ASN_TAG_CLASS_APPLICATION | (446 << 2)),
		0,
		&asn_DEF_PublicUserId,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"publicUserId"
		},
	{ ATF_POINTER, 3, offsetof(struct ChargedParty, homeBid),
		(ASN_TAG_CLASS_APPLICATION | (122 << 2)),
		0,
		&asn_DEF_HomeBid,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"homeBid"
		},
	{ ATF_POINTER, 2, offsetof(struct ChargedParty, homeLocationDescription),
		(ASN_TAG_CLASS_APPLICATION | (413 << 2)),
		0,
		&asn_DEF_HomeLocationDescription,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"homeLocationDescription"
		},
	{ ATF_POINTER, 1, offsetof(struct ChargedParty, imei),
		(ASN_TAG_CLASS_APPLICATION | (128 << 2)),
		0,
		&asn_DEF_Imei,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"imei"
		},
};
static const int asn_MAP_ChargedParty_oms_1[] = { 0, 1, 2, 3, 4, 5 };
static const ber_tlv_tag_t asn_DEF_ChargedParty_tags_1[] = {
	(ASN_TAG_CLASS_APPLICATION | (436 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ChargedParty_tag2el_1[] = {
    { (ASN_TAG_CLASS_APPLICATION | (122 << 2)), 3, 0, 0 }, /* homeBid */
    { (ASN_TAG_CLASS_APPLICATION | (128 << 2)), 5, 0, 0 }, /* imei */
    { (ASN_TAG_CLASS_APPLICATION | (129 << 2)), 0, 0, 0 }, /* imsi */
    { (ASN_TAG_CLASS_APPLICATION | (152 << 2)), 1, 0, 0 }, /* msisdn */
    { (ASN_TAG_CLASS_APPLICATION | (413 << 2)), 4, 0, 0 }, /* homeLocationDescription */
    { (ASN_TAG_CLASS_APPLICATION | (446 << 2)), 2, 0, 0 } /* publicUserId */
};
asn_SEQUENCE_specifics_t asn_SPC_ChargedParty_specs_1 = {
	sizeof(struct ChargedParty),
	offsetof(struct ChargedParty, _asn_ctx),
	asn_MAP_ChargedParty_tag2el_1,
	6,	/* Count of tags in the map */
	asn_MAP_ChargedParty_oms_1,	/* Optional members */
	6, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_ChargedParty = {
	"ChargedParty",
	"ChargedParty",
	&asn_OP_SEQUENCE,
	asn_DEF_ChargedParty_tags_1,
	sizeof(asn_DEF_ChargedParty_tags_1)
		/sizeof(asn_DEF_ChargedParty_tags_1[0]) - 1, /* 1 */
	asn_DEF_ChargedParty_tags_1,	/* Same as above */
	sizeof(asn_DEF_ChargedParty_tags_1)
		/sizeof(asn_DEF_ChargedParty_tags_1[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_ChargedParty_1,
	6,	/* Elements count */
	&asn_SPC_ChargedParty_specs_1	/* Additional specs */
};

