/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP0312.asn1"
 * 	`asn1c -D E:/repos/tap3reader/src/pdus/tap/3_12`
 */

#ifndef	_ChargedPartyLocationList_H_
#define	_ChargedPartyLocationList_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ChargedPartyLocation;

/* ChargedPartyLocationList */
typedef struct ChargedPartyLocationList {
	A_SEQUENCE_OF(struct ChargedPartyLocation) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ChargedPartyLocationList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ChargedPartyLocationList;
extern asn_SET_OF_specifics_t asn_SPC_ChargedPartyLocationList_specs_1;
extern asn_TYPE_member_t asn_MBR_ChargedPartyLocationList_1[1];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ChargedPartyLocation.h"

#endif	/* _ChargedPartyLocationList_H_ */
#include <asn_internal.h>
