/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP0312.asn1"
 * 	`asn1c -D E:/repos/tap3reader/src/pdus/tap/3_12`
 */

#ifndef	_MessagingEvent_H_
#define	_MessagingEvent_H_


#include <asn_application.h>

/* Including external dependencies */
#include "MessagingEventService.h"
#include "RapFileSequenceNumber.h"
#include "SimToolkitIndicator.h"
#include "EventReference.h"
#include "LocationArea.h"
#include "CellId.h"
#include "ExchangeRateCode.h"
#include "Charge.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ChargedParty;
struct GeographicalLocation;
struct RecEntityCodeList;
struct NetworkElementList;
struct ServiceStartTimestamp;
struct NonChargedParty;
struct CallTypeGroup;
struct TaxInformationList;
struct OperatorSpecInfoList;

/* MessagingEvent */
typedef struct MessagingEvent {
	MessagingEventService_t	*messagingEventService;	/* OPTIONAL */
	struct ChargedParty	*chargedParty;	/* OPTIONAL */
	RapFileSequenceNumber_t	*rapFileSequenceNumber;	/* OPTIONAL */
	SimToolkitIndicator_t	*simToolkitIndicator;	/* OPTIONAL */
	struct GeographicalLocation	*geographicalLocation;	/* OPTIONAL */
	EventReference_t	*eventReference;	/* OPTIONAL */
	struct RecEntityCodeList	*recEntityCodeList;	/* OPTIONAL */
	struct NetworkElementList	*networkElementList;	/* OPTIONAL */
	LocationArea_t	*locationArea;	/* OPTIONAL */
	CellId_t	*cellId;	/* OPTIONAL */
	struct ServiceStartTimestamp	*serviceStartTimestamp;	/* OPTIONAL */
	struct NonChargedParty	*nonChargedParty;	/* OPTIONAL */
	ExchangeRateCode_t	*exchangeRateCode;	/* OPTIONAL */
	struct CallTypeGroup	*callTypeGroup;	/* OPTIONAL */
	Charge_t	*charge;	/* OPTIONAL */
	struct TaxInformationList	*taxInformationList;	/* OPTIONAL */
	struct OperatorSpecInfoList	*operatorSpecInformation;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MessagingEvent_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MessagingEvent;
extern asn_SEQUENCE_specifics_t asn_SPC_MessagingEvent_specs_1;
extern asn_TYPE_member_t asn_MBR_MessagingEvent_1[17];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ChargedParty.h"
#include "GeographicalLocation.h"
#include "RecEntityCodeList.h"
#include "NetworkElementList.h"
#include "ServiceStartTimestamp.h"
#include "NonChargedParty.h"
#include "CallTypeGroup.h"
#include "TaxInformationList.h"
#include "OperatorSpecInfoList.h"

#endif	/* _MessagingEvent_H_ */
#include <asn_internal.h>
