/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP0312.asn1"
 * 	`asn1c -D E:/repos/tap3reader/src/pdus/tap/3_12`
 */

#include "MobileSession.h"

asn_TYPE_member_t asn_MBR_MobileSession_1[] = {
	{ ATF_POINTER, 16, offsetof(struct MobileSession, mobileSessionService),
		(ASN_TAG_CLASS_APPLICATION | (440 << 2)),
		0,
		&asn_DEF_MobileSessionService,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"mobileSessionService"
		},
	{ ATF_POINTER, 15, offsetof(struct MobileSession, chargedParty),
		(ASN_TAG_CLASS_APPLICATION | (436 << 2)),
		0,
		&asn_DEF_ChargedParty,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"chargedParty"
		},
	{ ATF_POINTER, 14, offsetof(struct MobileSession, rapFileSequenceNumber),
		(ASN_TAG_CLASS_APPLICATION | (181 << 2)),
		0,
		&asn_DEF_RapFileSequenceNumber,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"rapFileSequenceNumber"
		},
	{ ATF_POINTER, 13, offsetof(struct MobileSession, simToolkitIndicator),
		(ASN_TAG_CLASS_APPLICATION | (200 << 2)),
		0,
		&asn_DEF_SimToolkitIndicator,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"simToolkitIndicator"
		},
	{ ATF_POINTER, 12, offsetof(struct MobileSession, geographicalLocation),
		(ASN_TAG_CLASS_APPLICATION | (113 << 2)),
		0,
		&asn_DEF_GeographicalLocation,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"geographicalLocation"
		},
	{ ATF_POINTER, 11, offsetof(struct MobileSession, locationArea),
		(ASN_TAG_CLASS_APPLICATION | (136 << 2)),
		0,
		&asn_DEF_LocationArea,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"locationArea"
		},
	{ ATF_POINTER, 10, offsetof(struct MobileSession, cellId),
		(ASN_TAG_CLASS_APPLICATION | (59 << 2)),
		0,
		&asn_DEF_CellId,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"cellId"
		},
	{ ATF_POINTER, 9, offsetof(struct MobileSession, eventReference),
		(ASN_TAG_CLASS_APPLICATION | (435 << 2)),
		0,
		&asn_DEF_EventReference,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"eventReference"
		},
	{ ATF_POINTER, 8, offsetof(struct MobileSession, recEntityCodeList),
		(ASN_TAG_CLASS_APPLICATION | (185 << 2)),
		0,
		&asn_DEF_RecEntityCodeList,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"recEntityCodeList"
		},
	{ ATF_POINTER, 7, offsetof(struct MobileSession, serviceStartTimestamp),
		(ASN_TAG_CLASS_APPLICATION | (447 << 2)),
		0,
		&asn_DEF_ServiceStartTimestamp,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"serviceStartTimestamp"
		},
	{ ATF_POINTER, 6, offsetof(struct MobileSession, causeForTerm),
		(ASN_TAG_CLASS_APPLICATION | (58 << 2)),
		0,
		&asn_DEF_CauseForTerm,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"causeForTerm"
		},
	{ ATF_POINTER, 5, offsetof(struct MobileSession, totalCallEventDuration),
		(ASN_TAG_CLASS_APPLICATION | (223 << 2)),
		0,
		&asn_DEF_TotalCallEventDuration,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"totalCallEventDuration"
		},
	{ ATF_POINTER, 4, offsetof(struct MobileSession, nonChargedParty),
		(ASN_TAG_CLASS_APPLICATION | (443 << 2)),
		0,
		&asn_DEF_NonChargedParty,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"nonChargedParty"
		},
	{ ATF_POINTER, 3, offsetof(struct MobileSession, requestedDestination),
		(ASN_TAG_CLASS_APPLICATION | (450 << 2)),
		0,
		&asn_DEF_RequestedDestination,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"requestedDestination"
		},
	{ ATF_POINTER, 2, offsetof(struct MobileSession, sessionChargeInfoList),
		(ASN_TAG_CLASS_APPLICATION | (448 << 2)),
		0,
		&asn_DEF_SessionChargeInfoList,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"sessionChargeInfoList"
		},
	{ ATF_POINTER, 1, offsetof(struct MobileSession, operatorSpecInformation),
		(ASN_TAG_CLASS_APPLICATION | (162 << 2)),
		0,
		&asn_DEF_OperatorSpecInfoList,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"operatorSpecInformation"
		},
};
static const int asn_MAP_MobileSession_oms_1[] = { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15 };
static const ber_tlv_tag_t asn_DEF_MobileSession_tags_1[] = {
	(ASN_TAG_CLASS_APPLICATION | (434 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_MobileSession_tag2el_1[] = {
    { (ASN_TAG_CLASS_APPLICATION | (58 << 2)), 10, 0, 0 }, /* causeForTerm */
    { (ASN_TAG_CLASS_APPLICATION | (59 << 2)), 6, 0, 0 }, /* cellId */
    { (ASN_TAG_CLASS_APPLICATION | (113 << 2)), 4, 0, 0 }, /* geographicalLocation */
    { (ASN_TAG_CLASS_APPLICATION | (136 << 2)), 5, 0, 0 }, /* locationArea */
    { (ASN_TAG_CLASS_APPLICATION | (162 << 2)), 15, 0, 0 }, /* operatorSpecInformation */
    { (ASN_TAG_CLASS_APPLICATION | (181 << 2)), 2, 0, 0 }, /* rapFileSequenceNumber */
    { (ASN_TAG_CLASS_APPLICATION | (185 << 2)), 8, 0, 0 }, /* recEntityCodeList */
    { (ASN_TAG_CLASS_APPLICATION | (200 << 2)), 3, 0, 0 }, /* simToolkitIndicator */
    { (ASN_TAG_CLASS_APPLICATION | (223 << 2)), 11, 0, 0 }, /* totalCallEventDuration */
    { (ASN_TAG_CLASS_APPLICATION | (435 << 2)), 7, 0, 0 }, /* eventReference */
    { (ASN_TAG_CLASS_APPLICATION | (436 << 2)), 1, 0, 0 }, /* chargedParty */
    { (ASN_TAG_CLASS_APPLICATION | (440 << 2)), 0, 0, 0 }, /* mobileSessionService */
    { (ASN_TAG_CLASS_APPLICATION | (443 << 2)), 12, 0, 0 }, /* nonChargedParty */
    { (ASN_TAG_CLASS_APPLICATION | (447 << 2)), 9, 0, 0 }, /* serviceStartTimestamp */
    { (ASN_TAG_CLASS_APPLICATION | (448 << 2)), 14, 0, 0 }, /* sessionChargeInfoList */
    { (ASN_TAG_CLASS_APPLICATION | (450 << 2)), 13, 0, 0 } /* requestedDestination */
};
asn_SEQUENCE_specifics_t asn_SPC_MobileSession_specs_1 = {
	sizeof(struct MobileSession),
	offsetof(struct MobileSession, _asn_ctx),
	asn_MAP_MobileSession_tag2el_1,
	16,	/* Count of tags in the map */
	asn_MAP_MobileSession_oms_1,	/* Optional members */
	16, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_MobileSession = {
	"MobileSession",
	"MobileSession",
	&asn_OP_SEQUENCE,
	asn_DEF_MobileSession_tags_1,
	sizeof(asn_DEF_MobileSession_tags_1)
		/sizeof(asn_DEF_MobileSession_tags_1[0]) - 1, /* 1 */
	asn_DEF_MobileSession_tags_1,	/* Same as above */
	sizeof(asn_DEF_MobileSession_tags_1)
		/sizeof(asn_DEF_MobileSession_tags_1[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_MobileSession_1,
	16,	/* Elements count */
	&asn_SPC_MobileSession_specs_1	/* Additional specs */
};

