/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP0312.asn1"
 * 	`asn1c -D E:/repos/tap3reader/src/pdus/tap/3_12`
 */

#ifndef	_MobileSession_H_
#define	_MobileSession_H_


#include <asn_application.h>

/* Including external dependencies */
#include "MobileSessionService.h"
#include "RapFileSequenceNumber.h"
#include "SimToolkitIndicator.h"
#include "LocationArea.h"
#include "CellId.h"
#include "EventReference.h"
#include "CauseForTerm.h"
#include "TotalCallEventDuration.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ChargedParty;
struct GeographicalLocation;
struct RecEntityCodeList;
struct ServiceStartTimestamp;
struct NonChargedParty;
struct RequestedDestination;
struct SessionChargeInfoList;
struct OperatorSpecInfoList;

/* MobileSession */
typedef struct MobileSession {
	MobileSessionService_t	*mobileSessionService;	/* OPTIONAL */
	struct ChargedParty	*chargedParty;	/* OPTIONAL */
	RapFileSequenceNumber_t	*rapFileSequenceNumber;	/* OPTIONAL */
	SimToolkitIndicator_t	*simToolkitIndicator;	/* OPTIONAL */
	struct GeographicalLocation	*geographicalLocation;	/* OPTIONAL */
	LocationArea_t	*locationArea;	/* OPTIONAL */
	CellId_t	*cellId;	/* OPTIONAL */
	EventReference_t	*eventReference;	/* OPTIONAL */
	struct RecEntityCodeList	*recEntityCodeList;	/* OPTIONAL */
	struct ServiceStartTimestamp	*serviceStartTimestamp;	/* OPTIONAL */
	CauseForTerm_t	*causeForTerm;	/* OPTIONAL */
	TotalCallEventDuration_t	*totalCallEventDuration;	/* OPTIONAL */
	struct NonChargedParty	*nonChargedParty;	/* OPTIONAL */
	struct RequestedDestination	*requestedDestination;	/* OPTIONAL */
	struct SessionChargeInfoList	*sessionChargeInfoList;	/* OPTIONAL */
	struct OperatorSpecInfoList	*operatorSpecInformation;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MobileSession_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MobileSession;
extern asn_SEQUENCE_specifics_t asn_SPC_MobileSession_specs_1;
extern asn_TYPE_member_t asn_MBR_MobileSession_1[16];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ChargedParty.h"
#include "GeographicalLocation.h"
#include "RecEntityCodeList.h"
#include "ServiceStartTimestamp.h"
#include "NonChargedParty.h"
#include "RequestedDestination.h"
#include "SessionChargeInfoList.h"
#include "OperatorSpecInfoList.h"

#endif	/* _MobileSession_H_ */
#include <asn_internal.h>
