/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP0312.asn1"
 * 	`asn1c -D E:/repos/tap3reader/src/pdus/tap/3_12`
 */

#include "NonChargedParty.h"

asn_TYPE_member_t asn_MBR_NonChargedParty_1[] = {
	{ ATF_POINTER, 2, offsetof(struct NonChargedParty, nonChargedPartyNumber),
		(ASN_TAG_CLASS_APPLICATION | (444 << 2)),
		0,
		&asn_DEF_NonChargedPartyNumber,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"nonChargedPartyNumber"
		},
	{ ATF_POINTER, 1, offsetof(struct NonChargedParty, nonChargedPublicUserId),
		(ASN_TAG_CLASS_APPLICATION | (445 << 2)),
		0,
		&asn_DEF_NonChargedPublicUserId,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"nonChargedPublicUserId"
		},
};
static const int asn_MAP_NonChargedParty_oms_1[] = { 0, 1 };
static const ber_tlv_tag_t asn_DEF_NonChargedParty_tags_1[] = {
	(ASN_TAG_CLASS_APPLICATION | (443 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_NonChargedParty_tag2el_1[] = {
    { (ASN_TAG_CLASS_APPLICATION | (444 << 2)), 0, 0, 0 }, /* nonChargedPartyNumber */
    { (ASN_TAG_CLASS_APPLICATION | (445 << 2)), 1, 0, 0 } /* nonChargedPublicUserId */
};
asn_SEQUENCE_specifics_t asn_SPC_NonChargedParty_specs_1 = {
	sizeof(struct NonChargedParty),
	offsetof(struct NonChargedParty, _asn_ctx),
	asn_MAP_NonChargedParty_tag2el_1,
	2,	/* Count of tags in the map */
	asn_MAP_NonChargedParty_oms_1,	/* Optional members */
	2, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_NonChargedParty = {
	"NonChargedParty",
	"NonChargedParty",
	&asn_OP_SEQUENCE,
	asn_DEF_NonChargedParty_tags_1,
	sizeof(asn_DEF_NonChargedParty_tags_1)
		/sizeof(asn_DEF_NonChargedParty_tags_1[0]) - 1, /* 1 */
	asn_DEF_NonChargedParty_tags_1,	/* Same as above */
	sizeof(asn_DEF_NonChargedParty_tags_1)
		/sizeof(asn_DEF_NonChargedParty_tags_1[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_NonChargedParty_1,
	2,	/* Elements count */
	&asn_SPC_NonChargedParty_specs_1	/* Additional specs */
};

