/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP0312.asn1"
 * 	`asn1c -D E:/repos/tap3reader/src/pdus/tap/3_12`
 */

#include "RequestedDestination.h"

asn_TYPE_member_t asn_MBR_RequestedDestination_1[] = {
	{ ATF_POINTER, 2, offsetof(struct RequestedDestination, requestedNumber),
		(ASN_TAG_CLASS_APPLICATION | (451 << 2)),
		0,
		&asn_DEF_RequestedNumber,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"requestedNumber"
		},
	{ ATF_POINTER, 1, offsetof(struct RequestedDestination, requestedPublicUserId),
		(ASN_TAG_CLASS_APPLICATION | (452 << 2)),
		0,
		&asn_DEF_RequestedPublicUserId,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"requestedPublicUserId"
		},
};
static const int asn_MAP_RequestedDestination_oms_1[] = { 0, 1 };
static const ber_tlv_tag_t asn_DEF_RequestedDestination_tags_1[] = {
	(ASN_TAG_CLASS_APPLICATION | (450 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_RequestedDestination_tag2el_1[] = {
    { (ASN_TAG_CLASS_APPLICATION | (451 << 2)), 0, 0, 0 }, /* requestedNumber */
    { (ASN_TAG_CLASS_APPLICATION | (452 << 2)), 1, 0, 0 } /* requestedPublicUserId */
};
asn_SEQUENCE_specifics_t asn_SPC_RequestedDestination_specs_1 = {
	sizeof(struct RequestedDestination),
	offsetof(struct RequestedDestination, _asn_ctx),
	asn_MAP_RequestedDestination_tag2el_1,
	2,	/* Count of tags in the map */
	asn_MAP_RequestedDestination_oms_1,	/* Optional members */
	2, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_RequestedDestination = {
	"RequestedDestination",
	"RequestedDestination",
	&asn_OP_SEQUENCE,
	asn_DEF_RequestedDestination_tags_1,
	sizeof(asn_DEF_RequestedDestination_tags_1)
		/sizeof(asn_DEF_RequestedDestination_tags_1[0]) - 1, /* 1 */
	asn_DEF_RequestedDestination_tags_1,	/* Same as above */
	sizeof(asn_DEF_RequestedDestination_tags_1)
		/sizeof(asn_DEF_RequestedDestination_tags_1[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_RequestedDestination_1,
	2,	/* Elements count */
	&asn_SPC_RequestedDestination_specs_1	/* Additional specs */
};

