/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP0312.asn1"
 * 	`asn1c -D E:/repos/tap3reader/src/pdus/tap/3_12`
 */

#ifndef	_ScuChargeType_H_
#define	_ScuChargeType_H_


#include <asn_application.h>

/* Including external dependencies */
#include "MessageStatus.h"
#include "PriorityCode.h"
#include "DistanceChargeBandCode.h"
#include "MessageType.h"
#include "MessageDescriptionCode.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ScuChargeType */
typedef struct ScuChargeType {
	MessageStatus_t	*messageStatus;	/* OPTIONAL */
	PriorityCode_t	*priorityCode;	/* OPTIONAL */
	DistanceChargeBandCode_t	*distanceChargeBandCode;	/* OPTIONAL */
	MessageType_t	*messageType;	/* OPTIONAL */
	MessageDescriptionCode_t	*messageDescriptionCode;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ScuChargeType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ScuChargeType;
extern asn_SEQUENCE_specifics_t asn_SPC_ScuChargeType_specs_1;
extern asn_TYPE_member_t asn_MBR_ScuChargeType_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _ScuChargeType_H_ */
#include <asn_internal.h>
