/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP0312.asn1"
 * 	`asn1c -D E:/repos/tap3reader/src/pdus/tap/3_12`
 */

#ifndef	_SupplServiceUsed_H_
#define	_SupplServiceUsed_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SupplServiceCode.h"
#include "SupplServiceActionCode.h"
#include "SsParameters.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ChargingTimeStamp;
struct ChargeInformation;
struct BasicServiceCodeList;

/* SupplServiceUsed */
typedef struct SupplServiceUsed {
	SupplServiceCode_t	*supplServiceCode;	/* OPTIONAL */
	SupplServiceActionCode_t	*supplServiceActionCode;	/* OPTIONAL */
	SsParameters_t	*ssParameters;	/* OPTIONAL */
	struct ChargingTimeStamp	*chargingTimeStamp;	/* OPTIONAL */
	struct ChargeInformation	*chargeInformation;	/* OPTIONAL */
	struct BasicServiceCodeList	*basicServiceCodeList;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SupplServiceUsed_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SupplServiceUsed;
extern asn_SEQUENCE_specifics_t asn_SPC_SupplServiceUsed_specs_1;
extern asn_TYPE_member_t asn_MBR_SupplServiceUsed_1[6];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ChargingTimeStamp.h"
#include "ChargeInformation.h"
#include "BasicServiceCodeList.h"

#endif	/* _SupplServiceUsed_H_ */
#include <asn_internal.h>
