/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP0312.asn1"
 * 	`asn1c -D E:/repos/tap3reader/src/pdus/tap/3_12`
 */

#ifndef	_TotalTransactionDuration_H_
#define	_TotalTransactionDuration_H_


#include <asn_application.h>

/* Including external dependencies */
#include "TotalCallEventDuration.h"

#ifdef __cplusplus
extern "C" {
#endif

/* TotalTransactionDuration */
typedef TotalCallEventDuration_t	 TotalTransactionDuration_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TotalTransactionDuration;
asn_struct_free_f TotalTransactionDuration_free;
asn_struct_print_f TotalTransactionDuration_print;
asn_constr_check_f TotalTransactionDuration_constraint;
ber_type_decoder_f TotalTransactionDuration_decode_ber;
der_type_encoder_f TotalTransactionDuration_encode_der;
xer_type_decoder_f TotalTransactionDuration_decode_xer;
xer_type_encoder_f TotalTransactionDuration_encode_xer;
jer_type_encoder_f TotalTransactionDuration_encode_jer;
oer_type_decoder_f TotalTransactionDuration_decode_oer;
oer_type_encoder_f TotalTransactionDuration_encode_oer;
per_type_decoder_f TotalTransactionDuration_decode_uper;
per_type_encoder_f TotalTransactionDuration_encode_uper;
per_type_decoder_f TotalTransactionDuration_decode_aper;
per_type_encoder_f TotalTransactionDuration_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _TotalTransactionDuration_H_ */
#include <asn_internal.h>
