/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP0312.asn1"
 * 	`asn1c -D E:/repos/tap3reader/src/pdus/tap/3_12`
 */

#ifndef	_TrackedCustomerInformation_H_
#define	_TrackedCustomerInformation_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct TrackedCustomerIdList;
struct TrackedCustomerHomeIdList;
struct TrackedCustomerLocList;
struct TrackedCustomerEquipment;

/* TrackedCustomerInformation */
typedef struct TrackedCustomerInformation {
	struct TrackedCustomerIdList	*trackedCustomerIdList;	/* OPTIONAL */
	struct TrackedCustomerHomeIdList	*trackedCustomerHomeIdList;	/* OPTIONAL */
	struct TrackedCustomerLocList	*trackedCustomerLocList;	/* OPTIONAL */
	struct TrackedCustomerEquipment	*trackedCustomerEquipment;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TrackedCustomerInformation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TrackedCustomerInformation;
extern asn_SEQUENCE_specifics_t asn_SPC_TrackedCustomerInformation_specs_1;
extern asn_TYPE_member_t asn_MBR_TrackedCustomerInformation_1[4];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "TrackedCustomerIdList.h"
#include "TrackedCustomerHomeIdList.h"
#include "TrackedCustomerLocList.h"
#include "TrackedCustomerEquipment.h"

#endif	/* _TrackedCustomerInformation_H_ */
#include <asn_internal.h>
