/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TAP-0312"
 * 	found in "TAP0312.asn1"
 * 	`asn1c -D E:/repos/tap3reader/src/pdus/tap/3_12`
 */

#ifndef	_TransferBatch_H_
#define	_TransferBatch_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct BatchControlInfo;
struct AccountingInfo;
struct NetworkInfo;
struct MessageDescriptionInfoList;
struct CallEventDetailList;
struct AuditControlInfo;

/* TransferBatch */
typedef struct TransferBatch {
	struct BatchControlInfo	*batchControlInfo;	/* OPTIONAL */
	struct AccountingInfo	*accountingInfo;	/* OPTIONAL */
	struct NetworkInfo	*networkInfo;	/* OPTIONAL */
	struct MessageDescriptionInfoList	*messageDescriptionInfo;	/* OPTIONAL */
	struct CallEventDetailList	*callEventDetails;	/* OPTIONAL */
	struct AuditControlInfo	*auditControlInfo;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TransferBatch_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TransferBatch;
extern asn_SEQUENCE_specifics_t asn_SPC_TransferBatch_specs_1;
extern asn_TYPE_member_t asn_MBR_TransferBatch_1[6];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "BatchControlInfo.h"
#include "AccountingInfo.h"
#include "NetworkInfo.h"
#include "MessageDescriptionInfoList.h"
#include "CallEventDetailList.h"
#include "AuditControlInfo.h"

#endif	/* _TransferBatch_H_ */
#include <asn_internal.h>
